# DATASCI 267 - GenAI - Assignment 5
student: cpfrish@berkeley.edu
section: 002
semester: Spring 2026

### Overview

In Assignment 5 you will create and test a RAG system yourself as a proof of concept and then write a corresponding business report on your findings.

The overall scenario is as follows:

You work at a tech company that is looking for new ways to organize their question answering and search capabilities to accelerate both engineering activity and the marketing team's production.  Founded in 2018, your company has grown rapidly to 300 engineers across distributed teams in San Francisco, Austin, and remotely, plus a 40-person marketing organization split between demand generation, content, product marketing, and customer education. The company also wants to roll out new GenAI-based products, so a lot of the questions will center around Generative AI concepts. Product releases are done quarterly.

As a Senior ML Engineer on your company's newly formed AI Infrastructure team, you've been tapped to lead a four-week proof-of-concept (mini-POC) evaluating whether a Retrieval-Augmented Generation (RAG) system could address the challenges and support both the engineering and marketing organizations. Your executive sponsor is the VP of Engineering, who has secured buy-in from the CMO and allocated a small budget for this exploratory work.

Your POC needs to demonstrate:

**Engineering use case**: Can RAG effectively answer technical questions about GenAI concepts, internal system architecture, and implementation details by retrieving from diverse documentation sources?

**Marketing use case**: Can RAG help marketing staff quickly find accurate, approved messaging about GenAI features, competitive positioning, and technical capabilities to accelerate content production?

**Practical viability**: What are the implementation complexities, accuracy levels, and user experience considerations? Is this worth a larger investment?

Success will be measured by demonstrated accuracy compared to ground truth answers and a clear recommendation on whether to proceed with a full implementation.  If recommended, then a qualitative test will be conducted to get feedback from a small pilot group (5 engineers, 3 marketers).


You will receive a gold dataset with 'good' responses to questions from marketing and engineering teams. You need to develop metric(s) that help you to evaluate how well your RAG system performs relative to the gold data. You should work with the tunable hyperparameters of the setup (LLM, chunking, embeddings, ...) for your iterations.

You will also need to write up your findings as a short 4-5 page proposal.

(See instructions throughout this notebook.)

So overall, the goals of this assignment are for you to:

*  Implement a RAG system using LangChain
*  Be able to formulate metric(s) that you may want to choose as your evaluation of the degree to which your system replicates gold answers (labeled data) that we will provide.
* Try out various hyper-parameters, settings, and other techniques to see which configuration works the best (given your chosen metric)  
* Write a comprehensive evaluation report, which also includes risks and limitations (and a lot more)

The notebook is organized as follows:

1. Set-Up

2. Base RAG components

    We will provide a base LangChain-based framework for you to use as inspiration for your RAG system. The components we’ll need include:  

      - 2.1 Text Embeddings    
      - 2.2 Text Chunking   
      - 2.3 The Vector DB & Semantic Search  
      - 2.4 The Language Model   
      - 2.5 Testing the LLM in a LangChain Chain   
      - 2.6. Setting up a simple RAG Chain     


3. Using RAG  

    We will provide a collection of documents for you to use for your RAG system. We will also provide a test of questions with "Gold" answers.  

      - 3.1 Loading of Data  
      - 3.2 Test Queries
      - 3.3 Running Your Implemented Model(s) and Your Experiments


4.  Evaluations

    Here, you will develop your strategy and conduct your evaluations of your RAG system

      - 4.1 Metrics
      - 4.2 Best Runs with your Metrics


5. Final Results

    In this section, you will answer some questions and provide a link to your final report

      - 5.1 Model Specifications
      - 5.2 Three Test Questions (and Results)
      - 5.3 Five Other Questions
      - 5.4 Link To Your 4-5 Page Final POC Report and Recommendation

RULES:  

* You must only use the language models we specify here for the functions we specify
* You must only use the embedding models we specify here for the functions we specify
* You must use the vector store we specify here
* You must only use the document collection we provide. And they ALL must be in your vector store.   
* Apart from the provided specifications, you are free to experiment with a wide variety of hyperparameters (chunk sizes, prompts, etc.), langchain or langgraph components (text splitters, retrievers, etc.)


**To run this notebook** you should copy it to your personal Colab Pro Google account by uploading it into your Google Drive. From there you can open it as a Colab notebook and run it.  Note: it needs a T4 GPU to run when you are working with all our data.  You can run sections 1 and 2 without the GPU to orient yourself to how LangChain RAG systems work. You should also be able to run it in a free Colab notebook.

NOTES:
* The Open Source Model we use is not trained for safety. So unsafe answers could be returned.

# Final Assignment Detailed Guidelines

## Introduction

You will complete a final assignment that represents a significant implementation and/or application of Gen AI techniques. Here’s what to expect:

- You must work on this assignment alone.  There is **NO** group work.  
- We will provide a notebook with some partially working systems  
- We will provide a scenario for the system and its users  
- We will provide a set of documents that you must use in the system  
- You cannot add any additional documents to the collection  
- We will provide a set of validation question/answer pairs

Overall, the goals of this assignment are for you to:

* Implement a RAG system using LangChain (or LangGraph) and the LLMs we specify. You can extend starter architecture that we provide a bit to address some of the common failure points in RAG deployments. (See Week 9 Live slides page 34, or “Seven Failure Points When Engineering a Retrieval Augmented Generation System”, [https://arxiv.org/pdf/2401.05856](https://arxiv.org/pdf/2401.05856); page 3\)  
* Please stay within the boundaries of LangChain (or LangGraph), the LLMs, the embedding models, and the vector database we specify. (The focus of a PoC, which this assignment aims to emulate, would be to test more established approaches, rather than trying to develop completely novel ones.)  
* Be able to quantitatively evaluate the performance of your model(s)  
* Be able to formulate metric(s) \- that you choose\! \- as you evaluate to what degree your system replicates gold answers (labeled data) that we will provide.  
* Try out various hyper-parameters and settings to see which configuration works the best (given your chosen metric(s)). **Do NOT try a grid search**. (It is much more important to develop an intuition as to which parameters matter in which way.)  
* Write a comprehensive evaluation (‘the report’, see ReportOutline we posted to Ed Discussion), which also includes risks and limitations and a lot more. The audience of this evaluation/report are the stakeholders of the PoC, who would make the decision to go ahead with the RAG implementation or not.

RULES:

* You can only use the language models specified here (Mistral and Cohere) as the LLM in your chain to generate answers.  You may use Llama 3.1 or 3.2 or Qwen 2 or Qwen 3 or Gemma 2 in other capacities.  The **only exception** is that if you are using RAGAS, you may use an OpenAI model (GPT) as the evaluator.
* You can only use the embedding models we specify from the Sentence Transformers library to create embeddings in the vector store.
* You can only use the documents we provide. And they ALL must be retrievable from your vector store (which we will specify)  
* If you use less than the 75 gold answers we supply, you must justify your subset \- how and why did you pick them? Apart from the provided specifications, some of the things you can freely experiment with include prompts, chunk sizes, LLM hyperparameters, architecture, etc.  
* You must however provide **at least one run on ALL 75 examples** for your best model/model configuration (along with the corresponding metrics, of course.) This must include the question wording, your model's response, and your evaluation metric(s) for that question, and an overall score for the entire run.

As context, the overall scenario for this assignment is as follows:

As described earlier, you work at a tech company that is looking for new ways to organize their search and question answering capabilities to accelerate both engineering activity and the product/marketing teams. The company also wants to roll out new GenAI-based products, so a lot of the questions will center around Generative AI and LLM concepts. The company has about 300 engineers and a marketing staff of 40. Product releases are done quarterly.

Your role is to implement and conduct a (mini-)POC helping the company to evaluate RAG capabilities for the improvement of their document search (and corresponding question answering), supporting particularly the engineering and marketing organizations. You will receive a gold dataset with 'good' responses to questions from marketing and engineering teams. You need to develop a plan that helps you complete a RAG system within the constraints of the POC. Your answers must work for each of the two groups of users \-- engineers and marketing managers. You will need to develop a plan to evaluate how well your RAG system performs relative to the gold data we provide. You will need to decide which metric or metrics you want to combine to effectively measure how well your model is working.  You can experiment with the tunable hyperparameters of the setup (LLM, chunking, embeddings, ...) for your iterations.

You will need to write up your findings as a 4 page report following the outline we provide in our post to Ed Discussion.

(Also see instructions throughout the notebook.)

NOTES:

* The Open Source Language Model is not trained for safety. So unsafe answers could be returned.

## Cohere

If you do not already have a Cohere account, you will need to create one in order to get an API key.  You will not be able to complete the assignment without it.  Go to [cohere.com](https://dashboard.cohere.com).  Sign up for an account using your personal email address **NOT** your @berkeley.edu email account. Once you have signed up, login to your account and go to the dashboard.  Over in the left hand nav bar is an item 'API Keys.' Click on it and you will see an area on screen called Trial Keys.  You will need to create a "new trial key" for yourself. When you have that trial key, copy it and store a copy somewhere you can retrieve it (never in the open in a notebook).  You'll need to enter that key as a secret in the Google notebook associated with `COHERE_API_KEY.`  (See the ‘Secrets’ icon in the colab again, **DO NOT PRINT IT OUT IN THE NOTEBOOK\!**)

Cohere’s Trial Key is free.  However, be aware of the constraints and use the resource wisely.  Check the [limits on use of the API.](https://docs.cohere.com/docs/rate-limits)  You are responsible for staying within those limits. For example, the Trial Key permits only 1,000 API calls per month. Use this resource wisely. You need to either plan for their constraints,  or you can pay to upgrade your key.

## Assignment Grading

The final grade for this assignment consists of the following components:

- \[20%\] Implementation and Architecture of Model  
    
- \[15%\] Poor Man’s Evaluation Strategy  
    
- \[20%\] Experimentation  
    
- \[03%\] Three Specific Queries Test  
    
- \[05%\] Five Additional Questions  
    
- \[37%\] POC Report

### Our Expectations of You

As a student in a graduate level course, you are responsible for seeking out help when your project is stuck.  There is significant support available if you seek it out.  Do not wait for us to provide feedback on deliverables to take action.  

### Rubric Dimensions

Each of the following dimensions will be considered while grading.  An assignment significantly lacking in any dimension will receive a considerably lower grade.  Each dimension is illustrated by several bullet points.

Implementation and Architecture of Model (20%):

- A clearly functioning model that is able to address the problem you are trying to solve  (which should be the one we are giving...).

Poor Man’s Evaluation Strategy (15%):

- Suitability and thoughtfulness of your approach to the problem.  
- "How will I know when my project is successful?", usually in the form of an evaluation metric.  
- suitability of the metric(s) are you using, and how you combine them if necessary

Experimentation (20%):
   
- How much analysis did you do to drive your experimentation?
- How meaningful were the various run comparisons?
- How many of the possible tuning parameters did you use?

Three Specific Questions (03%):

- How well do your answers score against our gold ones?  
- More importantly, how reasonable are your assessments?

Five Additional Questions (05%):

- How thoughtful and incisive are your answers to these implementation questions?

POC Report (37%):

- Primarily:  
  - Succinct, interesting presentation explaining the above.    
  - Suitability of the report to guide the organization to a decision  
  - Suitability of the report to articulate the limitations and opportunities of the RAG approach for the orgaization
  - Do you provide data to support your conclusion(s)?
  - Is your report well organized?
- Table stakes:  
  - Did you run a spell check before submitting?  
  - Did you proofread it?

## Final Submission

This will be a final report on your POC following the outline we provide in our post on Ed Discussion. Aim for 4-5 pages in length with the following sections:

- **Executive Summary** (Quick summary of your report)  
- **Introduction** (overall system description)  
- **Key Findings** (five key findings)  
- **Methodology** (implementation and evaluation approach)  
- **Results and Findings** (challenges and limitations)

Please save your report as a PDF file in your Berkeley Google Drive, put a link at the end of this notebook and then submit your notebook (*complete with outputs of running*) to Gradescope.  You can also submit a copy of the pdf file to Gradescope along with your notebook. There is no autograder on this assignment.

**And remember: for many aspects there is no right or wrong answer\! Most important are reasonable, clearly-thought-out approaches\!**

# LLM Usage Clarification in A5

PLEASE READ THESE DIRECTIONS CAREFULLY

We want to clarify the boundaries for using LLMs (commercial and open source) in your completion of a5.  Beyond the obvious use of the Mistral and Cohere LLMs as the question answering portion of your RAG pipeline, you may use an LLM to assist in certain portions of the assignment.  For example, you may use an LLM to assist with re-writing portions of your report if you wish.  We would discourage you from using the LLM to write code.

**You MUST NOT:**

* You must **NOT** use an LLM to answer any questions we posed. For example, do not use it to answer the questions in sections 4 or 5 of the notebook.

* You must **NOT** use the LLM to generate the initial draft of your final report.

*  You must **NOT** use the LLM to generate or assist with your metrics justification. We want to know what you think in your own words.

**You CAN:**

* You can use an LLM to help you with the report writing as far as formulations and phrasing go, but obviously not to construct core content.

* You should turn off the use of your input to help with training commercial LLMs.  For example, in OpenAI’s ChatGPT you can go to Settings in your account and then Data Controls and then make sure that ‘Improve the model for everyone’ is set to off.

**You MUST:**

* You **MUST** tell us how you have used an LLM by specifying which model(s) you used, how you used the model, and which portion of your output it helped to generate.  You can include this in the references section and put citations into the body of your final report.

### Although I did use the validation_questions verbatim below, I moved them to a json file as it was too much noise to keep scrolling through them as I worked on / tweaked the pipeline.

In [1]:
validation_questions_answers = {
    0: {
        "question": "What pre-trained neural retriever model is used as the non-parametric memory component in RAG, providing latent documents conditioned on the input?",
        "gold_answer_research": "The pre-trained neural retriever model used as the non-parametric memory component in RAG is the Dense Passage Retriever (DPR). DPR provides latent documents conditioned on the input for the seq2seq model (BART) to generate the output. This retriever is initialized using retrieval supervision on Natural Questions and TriviaQA datasets, and it allows for efficient retrieval and incorporation of relevant information during the generation process.",
        "gold_answer_marketing": "The pre-trained neural retriever model used as the non-parametric memory component in RAG is the Dense Passage Retriever (DPR).",
    },
    4: {
        "question": "How does the BM25 technique determine which passages are most relevant to a given query?",
        "gold_answer_research": "The BM25 technique determines which passages are most relevant to a given query by calculating a relevance score based on the frequency of query terms in each passage and the inverse document frequency. By using gold passages from the same mini-batch and one negative passage with a high BM25 score in combination, the retrieval results can be significantly improved. Additionally, exploring a setting where BM25 score and dense embedding retrieval score are linearly combined can serve as a new ranking function to further enhance the retrieval process.",
        "gold_answer_marketing": "The BM25 technique determines the relevance of passages by combining a score based on BM25 with a dense embedding retrieval score. This new ranking function helps improve retrieval results by using gold passages from the same mini-batch along with one negatively scored passage.",
    },
    5: {
        "question": "How does the RAG (retrieval-augmented generation) model leverage neural retrievers and document representation techniques to enhance the retrieval and generation process compared to earlier word-similarity-based methods?",
        "gold_answer_research": "The RAG model leverages a Dense Passage Retriever (DPR) that is pre-trained to rank correct passages in various question-answering settings. This allows for more accurate retrieval of relevant document chunks. The bi/dual-encoder nature of the DPR model enables effective document representation, improving the retrieval process compared to earlier word-similarity-based methods. By combining neural retrievers with document representation techniques, RAG enhances the overall retrieval and generation process by providing contextually relevant and factually accurate responses.",
        "gold_answer_marketing": "The RAG model combines neural retrievers, like the Dense Passage Retriever (DPR), with document representation techniques to improve retrieval and generation. This integration allows for contextually relevant and factually accurate responses compared to earlier word-similarity-based methods. The bi/dual-encoder nature of the DPR model enables better matching of documents and queries, enhancing the overall performance of the RAG framework.",
    },
    11: {
        "question": "How does the introduction of rotary position encoding (RoPE) in RoFormer influence the training convergence and evaluation metrics when compared to traditional position encoding methods in transformer-based models?",
        "gold_answer_research": "The introduction of rotary position encoding (RoPE) in RoFormer may improve training convergence and evaluation metrics compared to traditional position encoding methods in transformer-based models. RoPE offers valuable properties such as sequence length flexibility, decaying inter-token dependency with increasing relative distances, and the capability of equipping linear self-attention with relative position encoding. This may lead to better performance in terms of loss, accuracy, and overall model efficacy. Additionally, RoPE's multiplicative nature and incorporation of relative position information through rotation matrix product could contribute to more efficient training convergence and improved evaluation metrics in comparison to traditional additive position encoding methods.",
        "gold_answer_marketing": "The introduction of rotary position encoding (RoPE) in RoFormer improves training convergence and evaluation metrics compared to traditional position encoding methods in transformer-based models. This is evidenced by better performance results in terms of loss and accuracy across different training stages and tasks.",
    },
    13: {
        "question": "Which characteristics or innovations distinguish Longformer from other transformer-based models when processing lengthy texts?",
        "gold_answer_research": "Longformer stands out from other transformer-based models by its ability to efficiently process input sequences that are thousands of tokens long, specifically supporting input sequence lengths of up to 16K tokens. This capability allows Longformer to encode 99% of full texts in the QASPER dataset without the need for truncation. Additionally, Longformer-Encoder-Decoder (LED) offers valuable properties such as sequence length flexibility, decaying inter-token dependency with increasing relative distances, and the ability to equip linear self-attention with relative position encoding. These characteristics make Longformer a standout choice for handling lengthy text processing tasks efficiently.",
        "gold_answer_marketing": "Longformer differentiates itself by its support for processing input sequences up to 16K tokens long without truncation, a capability that enables it to encode 99% of full-text papers in the QASPER dataset. This is made possible by its Longformer-Encoder-Decoder (LED) architecture, which efficiently handles long inputs through its specialized design.",
    },
    15: {
        "question": "How does LoRA enable efficient adaptation of large Transformer-based language models while minimizing the number of parameters that need to be trained for downstream tasks?",
        "gold_answer_research": "LoRA enables efficient adaptation of large Transformer-based language models by injecting trainable rank decomposition matrices into each layer of the Transformer architecture. This greatly reduces the number of trainable parameters required for downstream tasks, allowing for high model quality with minimal memory requirements. By optimizing the pre-trained model weights and utilizing additional factorized projections, LoRA ensures effective task-switching and performance improvement without introducing additional latency during inference. Additionally, the flexibility to apply LoRA to specific weight matrices in the neural network allows for targeted parameter reduction while maintaining model scalability and task performance.",
        "gold_answer_marketing": "LoRA reduces the number of trainable parameters in large language models like GPT-3 and RoBERTa by injecting trainable rank decomposition matrices into each layer of the Transformer architecture. This allows for efficient adaptation to specific tasks while maintaining model quality and reducing GPU memory requirements. It outperforms traditional fine-tuning methods in terms of parameter efficiency and performance on a variety of tasks.",
    },
    16: {
        "question": "How does the Low-Rank Adaptation (LoRA) technique enable efficient adaptation of large pre-trained neural networks for various downstream tasks while minimizing both storage requirements and inference latency?",
        "gold_answer_research": "The Low-Rank Adaptation (LoRA) technique allows for efficient adaptation of large pre-trained neural networks by reducing the number of trainable parameters through the use of rank decomposition matrices, while keeping the pre-trained weights fixed. This not only minimizes storage requirements but also enables quick task-switching without introducing inference latency. By optimizing the rank decomposition matrices of the dense layers' change during adaptation, LoRA provides a computationally efficient way to fine-tune models for different downstream tasks while maintaining high model quality.",
        "gold_answer_marketing": "LoRA technique reduces the number of trainable parameters and memory requirements by using low-rank adaptation matrices while keeping pre-trained weights fixed. This allows for efficient adaptation of large pre-trained neural networks for different tasks without introducing inference latency. Additionally, LoRA enables quick task-switching and better interpretability of weight correlations during adaptation.",
    },
    20: {
        "question": "How are hyperparameters such as learning rate, batch size, and maximum sequence length chosen or varied when applying LoRA to different model architectures on benchmark tasks?",
        "gold_answer_research": "When applying LoRA to different model architectures on benchmark tasks, hyperparameters such as learning rate, batch size, and maximum sequence length are chosen or varied through a systematic hyperparameter search. For example, a hyperparameter search may involve exploring different values for LoRA dropout, LoRA r, and LoRA layers to optimize performance. Additionally, the learning rate is adjusted based on the chosen LoRA configuration and the specific model architecture being used. The batch size is typically kept consistent across tasks to ensure fair comparisons, while the maximum sequence length may vary depending on the requirements of each individual task. Overall, these hyperparameters are carefully tuned to achieve the best performance when applying LoRA to different model architectures on benchmark tasks.",
        "gold_answer_marketing": "Hyperparameters like learning rate, batch size, and sequence length are determined through a hyperparameter search process to optimize LoRA performance across different model architectures and benchmark tasks. This search involves exploring variables such as LoRA dropout, LoRA multiplier, and the specific layers to apply LoRA to, while keeping other factors like learning rate proportional to LoRA for consistency and effectiveness.",
    },
    22: {
        "question": "How does fine-tuning large language models with human feedback impact their ability to generate responses that better reflect user instructions and reduce undesirable outputs?",
        "gold_answer_research": "Fine-tuning large language models with human feedback can significantly improve their ability to generate responses that better reflect user instructions. This process helps align the language models with human intent and can reduce undesirable outputs, such as toxic or biased content. By incorporating human feedback during the fine-tuning process, the models can better generalize to new instructions and increase their usability. Additionally, fine-tuning with human feedback has been shown to improve performance in specialized content generation, ensuring accuracy and tone consistency in responses.",
        "gold_answer_marketing": "Fine-tuning large language models with human feedback helps align them with user intent, resulting in better responses that reflect instructions accurately. This process also helps in reducing the generation of undesirable outputs such as toxic or biased content.",
    },
    23: {
        "question": "Which two compilations of public NLP tasks were used to fine-tune GPT-3 for comparison with InstructGPT, as mentioned in the evaluation of model performance on the API prompt distribution?",
        "gold_answer_research": "The two compilations of public NLP tasks used to fine-tune GPT-3 for comparison with InstructGPT are the GLUE benchmark and WikiSQL. These tasks cover a wide range of natural language understanding and generation tasks, providing a diverse set of challenges for the models to evaluate their performance on the API prompt distribution. Additionally, the models were also evaluated on other tasks such as NL to SQL queries and SAMSum to assess their capabilities beyond the fine-tuning distribution.",
        "gold_answer_marketing": "The two compilations of public NLP tasks used to fine-tune GPT-3 for comparison with InstructGPT are SQuAD and DROP as mentioned in the evaluation of model performance on the API prompt distribution.",
    },
    27: {
        "question": "How does the use of counterfactual evaluation contribute to reducing bias in language models?",
        "gold_answer_research": "Counterfactual evaluation helps in reducing bias in language models by testing the model's ability to recognize and disregard known inaccuracies within documents, even when informed about potential misinformation. This approach evaluates the model's performance based on context relevance and noise robustness for retrieval quality, as well as answer faithfulness, relevance, negative rejection, information integration, and counterfactual robustness for generation quality. By analyzing relative probabilities and entropy, models can be assessed for bias, and improvements can be made to align their behavior with societal expectations and reduce harmful outputs. Various methods, such as adversarial setups and additional labeling, can be explored to decrease the generation of toxic or biased content.",
        "gold_answer_marketing": "Counterfactual evaluation helps reduce bias in language models by testing their ability to recognize and ignore known inaccuracies in documents, even when informed about potential misinformation. This approach is crucial for ensuring context relevance, noise robustness, and overall quality in retrieval and generation processes. It also provides insights into improving models' behavior to align more closely with user expectations.",
    },
    28: {
        "question": "What are some common ways in which GPT-3 is prompted to perform summarization, brainstorming, and classification tasks, based on the examples provided?",
        "gold_answer_research": 'Some common ways in which GPT-3 is prompted to perform summarization tasks include instructions like "Please help me summarize this paragraph into one sentence." For brainstorming tasks, users may ask GPT-3 to generate creative ideas based on a given context, such as "Please give indie movie ideas like a guy traveling to South America to become a shaman." In classification tasks, GPT-3 may be tasked with determining sentiment from a tweet, for example, "This is a tweet sentiment classifier, is the sentiment positive or negative?" These prompts showcase the diverse range of tasks GPT-3 can perform, from summarization to brainstorming to classification.',
        "gold_answer_marketing": "GPT-3 is prompted for summarization tasks by asking it to condense lengthy texts into concise summaries. For brainstorming tasks, it generates creative ideas based on user instructions and context. In classification tasks, GPT-3 can be asked to classify sentiment or other attributes of text inputs.",
    },
    33: {
        "question": "How does adjusting the pretraining loss or KL reward coefficient affect the model’s performance on tasks such as DROP and SQuAD v2, and what trade-offs are observed in terms of validation reward?",
        "gold_answer_research": "Adjusting the pretraining loss coefficient has shown to be crucial in improving model performance on tasks like DROP and SQuAD v2. A value of 27.8 seems to work well across different model sizes, leading to significant improvements on these tasks without drastic drops in validation reward. On the other hand, increasing the KL reward coefficient can also improve performance, but it is essential to find the optimal balance, as values that are too low or too high can result in poor performance. Overall, there is a trade-off between task performance and validation reward when adjusting these coefficients, highlighting the need for careful tuning to achieve the best results.",
        "gold_answer_marketing": "Adjusting the pretraining loss coefficient can improve performance on tasks like DROP and SQuAD v2 with minimal impact on validation reward. Increasing the KL reward coefficient can also have an effect on performance, but finding the optimal balance is crucial as higher KL values may lead to performance regressions. Trade-offs between performance on specific tasks and overall validation reward need to be carefully considered when adjusting these coefficients.",
    },
    36: {
        "question": "How does the use of PPO-ptx and SFT compare in terms of their effectiveness at reducing undesired language generation when evaluated with RealToxicityPrompts?",
        "gold_answer_research": "Based on the human evaluation results, it appears that PPO with pretraining data mix is less sensitive to changes in learning rate. Therefore, the engineering group chose checkpoints with the highest likert scores as their final models. In terms of reducing undesired language generation when evaluated with RealToxicityPrompts, PPO-ptx and SFT were compared. PPO-ptx showed better performance in following explicit constraints, attempting correct instructions, and reducing 'hallucinations' compared to SFT. This indicates that PPO-ptx may be more effective at mitigating undesired language generation in this context.",
        "gold_answer_marketing": "Based on human evaluation results, PPO-ptx appears to be more effective at reducing undesired language generation compared to SFT when evaluated with RealToxicityPrompts. The choice of checkpoints with the highest likert scores determined PPO-ptx as the preferred model for this purpose.",
    },
    38: {
        "question": "How does the Sieve of Eratosthenes algorithm operate to efficiently generate a list of prime numbers up to a specified value, and what steps are taken to ensure only valid input is processed?",
        "gold_answer_research": "The Sieve of Eratosthenes algorithm efficiently generates a list of prime numbers up to a specified value by iteratively eliminating multiples of prime numbers. To ensure only valid input is processed, the algorithm first checks that the input is positive. It then declares a set of Boolean flags and initializes variables for storing primes and iterating through the sieve array. The algorithm marks non-prime numbers in the sieve array and appends prime numbers to the list, ensuring that only prime numbers are included in the final output.",
        "gold_answer_marketing": "The prime sieve function generates a list of prime numbers up to a specified value by eliminating multiples of primes. It ensures only valid input is processed by checking that the input is positive before creating a list of primes using Boolean flags.",
    },
    41: {
        "question": "How does the use of explicit natural language instructions alter the way a retrieval system determines which documents are relevant to a given query, compared to traditional retrieval methods that rely solely on queries or task identifiers?",
        "gold_answer_research": "The use of explicit natural language instructions in a retrieval system provides a more detailed and nuanced understanding of the user's search intent compared to traditional methods that rely solely on queries or task identifiers. By providing a natural language description of the search task, the retrieval system can better interpret and comprehend the user's information needs, leading to more accurate and relevant document retrieval. This approach allows for a more personalized and user-friendly retrieval process by explicitly modeling the user's search intent through instructions, ultimately enhancing the efficiency and effectiveness of the retrieval system.",
        "gold_answer_marketing": "Using explicit natural language instructions in retrieval systems helps define the relevance of documents to a query more precisely, considering diverse criteria beyond just the query itself. This method allows for a more general and task-aware approach to retrieval, enhancing the system's capability to match user expectations. Traditional methods that only rely on queries or task identifiers may not capture the full intent behind the user's search as effectively.",
    },
    44: {
        "question": "How have pretrained transformer models such as BERT influenced advancements in text ranking methods?",
        "gold_answer_research": "Pretrained transformer models like BERT have significantly advanced text ranking methods by incorporating additional knowledge through pre-training models. These models have enhanced language models by improving contextual representations, such as replacing original position encodings with RoPE during pre-training. Additionally, models like RoBERTa have optimized pre-training recipes and improved task performance without introducing many more trainable parameters, leading to better text ranking results. The use of transformers in text ranking has revolutionized NLP tasks and achieved state-of-the-art performance in various benchmarks.",
        "gold_answer_marketing": "Pretrained transformer models like BERT have revolutionized text ranking methods by enhancing language models with additional knowledge through pre-training techniques. They have improved performance in tasks such as reranking passages using rule-based or model-based approaches, resulting in more precise language model processing. The use of BERT and similar models has led to significant advancements in text ranking methods by optimizing dense retrieval model training with hard negatives and achieving high accuracy in identifying answer spans.",
    },
    54: {
        "question": "How does the Elo rating system contribute to the evaluation of chatbot models like those trained with QLORA, and what are its advantages compared to relying solely on performance scores or absolute scales?",
        "gold_answer_research": "The Elo rating system helps in evaluating chatbot models trained with QLORA by providing a measure of the expected win-rate relative to an opponent's win rate. This allows for a more nuanced comparison of model performance based on pairwise judgments from human annotators and GPT-4. The advantages of using Elo ratings include capturing the relative performance of chatbot models without the need for grounding an absolute scale, highlighting uncertainties in model-based evaluations, and enabling a more comprehensive ranking of chatbot performance based on tournament results.",
        "gold_answer_marketing": "The Elo rating system helps determine the ranking of chatbot models based on their expected win-rates against opponents. This system provides a relative measure of performance, allowing for comparisons between models regardless of the scale used for evaluation. This method offers a more nuanced and robust evaluation approach compared to simply looking at raw performance scores or traditional absolute scales.",
    },
    58: {
        "question": "How does the quality of instruction finetuning datasets affect the MMLU performance of language models compared to increasing the amount of training data or number of training epochs?",
        "gold_answer_research": "The quality of instruction finetuning datasets has a significant impact on MMLU performance compared to simply increasing the amount of training data or number of training epochs. Increasing dataset size and training for more epochs only marginally improves MMLU performance, while the difference between datasets can be up to 40 times larger in terms of MMLU. This indicates that dataset quality plays a crucial role in mean MMLU accuracy, highlighting the importance of selecting high-quality datasets for instruction finetuning.",
        "gold_answer_marketing": "The quality of the instruction finetuning datasets has a greater impact on MMLU performance than increasing the dataset size or training epochs. While more data and epochs marginally improve MMLU, the difference between datasets significantly affects accuracy. This highlights the critical role of dataset quality in achieving mean MMLU accuracy.",
    },
    72: {
        "question": "What is the name of the method of prompting the model that improves the ability of an LLM to respond to questions over structured documents?",
        "gold_answer_research": "The method of prompting the model that improves the ability of an LLM to respond to questions over structured documents is called PDFTriage. This method enhances the LLM's capability to provide accurate responses by treating documents as structured objects rather than plain text. By utilizing this method, the LLM is better equipped to understand and process information from structured documents, resulting in improved question-answering performance.",
        "gold_answer_marketing": "The method of prompting the model that improves the ability of an LLM to respond to questions over structured documents is called PDFTriage.",
    },
    73: {
        "question": "How does the PDFTriage technique utilize document structure to enhance the accuracy of answers provided by retrieval-augmented language models?",
        "gold_answer_research": "The PDFTriage technique utilizes the structured metadata of a PDF document to implement a more precise and accurate document question-answering approach. It generates a structured representation of the document by extracting information from section text, figure captions, headers, and tables. This structured metadata allows a retrieval-augmented language model to select the appropriate document frame needed to answer a query, enhancing the accuracy of the answers provided compared to existing approaches. By leveraging the document's structure, PDFTriage enables the model to retrieve context based on either structure or content, making it effective across different classes of questions where other retrieval-augmented models fail.",
        "gold_answer_marketing": "PDFTriage leverages a PDF's structured metadata to implement a more precise and accurate document question-answering approach by extracting information from section text, figure captions, headers, and tables. This structured metadata representation allows the model to select the appropriate document frame needed to answer queries, improving answer quality and accuracy.",
    },
    80: {
        "question": "How does the sliding window attention mechanism contribute to both efficiency and information propagation in the Mistral 7B transformer architecture?",
        "gold_answer_research": "The sliding window attention mechanism in Mistral 7B allows each token to attend to at most W tokens from the previous layer, even though tokens outside the sliding window still influence next word prediction. This mechanism helps improve efficiency by reducing the latency and smaller throughput due to reduced cache availability. Furthermore, the information can move forward by up to k x W tokens after k attention layers, contributing to enhanced information propagation within the transformer architecture.",
        "gold_answer_marketing": "The sliding window attention in Mistral 7B allows tokens to attend to a limited number of tokens from previous layers, improving efficiency. This mechanism also enables information to propagate forward by a certain number of tokens at each attention layer, enhancing information flow within the architecture. Ultimately, this helps improve performance and reduce computational costs in Mistral 7B.",
    },
    83: {
        "question": "How does Self-reflective Retrieval-Augmented Generation improve the reliability and verifiability of generated text compared to standard RAG approaches?",
        "gold_answer_research": "Self-Reflective Retrieval-Augmented Generation (SELF-RAG) enhances reliability and verifiability by training an arbitrary LM to generate text with reflection tokens for self-assessment. This allows the model to reflect on whether the output is supported by the retrieved passages, leading to easier fact verification. Unlike standard RAG approaches that may indiscriminately retrieve and incorporate irrelevant or unhelpful passages, SELF-RAG's self-reflective nature ensures that generated text is more aligned with the provided knowledge and avoids factual inaccuracies commonly seen in conventional approaches. Additionally, SELF-RAG provides citations for each segment, further improving the reliability and traceability of the generated text.",
        "gold_answer_marketing": "Self-reflective Retrieval-Augmented Generation (SELF-RAG) improves reliability and verifiability of generated text by training a single LM to adaptively retrieve and reflect on passages on-demand, ensuring factual accuracy and reducing inaccuracies. This approach enhances the generation quality by providing citations for each segment and self-assessment of output based on supported passages, aiding in easier fact verification.",
    },
    90: {
        "question": "Which named technique involves mapping words or phrases from the vocabulary to vectors of real numbers in Natural Language Processing (NLP)?",
        "gold_answer_research": "One named technique that involves mapping words or phrases from the vocabulary to vectors of real numbers in NLP is Word Embedding. Word embedding is a set of language modeling and feature learning techniques where words or phrases are represented as continuous vector spaces with a much lower dimension. This method helps capture similarities between words and their context in NLP tasks.",
        "gold_answer_marketing": "Word embedding involves mapping words or phrases from the vocabulary to vectors of real numbers in Natural Language Processing (NLP).",
    },
    91: {
        "question": "How has the architectural paradigm of RAG evolved from its earliest implementations to current state-of-the-art frameworks?",
        "gold_answer_research": 'The RAG architecture initially emerged as a "Naive RAG" paradigm consisting of a straightforward, linear sequence of indexing documents, retrieving relevant chunks, and generating text. Over time, this evolved into "Advanced" and "Modular RAG" systems that incorporated specialized components for pre-retrieval query rewriting, post-retrieval reranking, and flexible routing among multiple data sources. Most recently, the field has shifted toward "Agentic RAG," which replaces fixed pipelines with autonomous systems where an LLM orchestrates the entire process, deciding when to fetch tools, iteratively refining queries, and reflecting on its own generations.',
        "gold_answer_marketing": "RAG systems began as simple pipelines that retrieved relevant documents and used them to generate answers. Today’s systems are far more sophisticated, using multiple data sources and AI “agents” that can decide what information to retrieve and how to refine answers to produce more accurate and useful results.",
    },
    93: {
        "question": "How does the use of re-ranking methods such as LambdaMART influence the retrieval of relevant context for LLM-based planning, particularly in comparison to using off-the-shelf retrievers or query augmentation techniques?",
        "gold_answer_research": "The use of re-ranking methods like LambdaMART can significantly impact the retrieval of relevant context for LLM-based planning by improving the ranking of candidate documents according to their relevance to the user's query. This approach enhances contextual understanding of implicit and ambiguous queries, which is crucial for plan generation. Compared to off-the-shelf retrievers or query augmentation techniques, re-ranking methods like LambdaMART have been shown to outperform in terms of performance and efficiency, especially when dealing with complex queries that demand context-seeking capabilities. It provides a more targeted and accurate approach to document reranking, leading to better outcomes in LLM-based planning tasks.",
        "gold_answer_marketing": "The use of re-ranking methods like LambdaMART enhances the retrieval of relevant context for LLM-based planning by improving the ranking of candidate documents based on their relevance to the user's query. Compared to off-the-shelf retrievers or query augmentation techniques, re-ranking with LambdaMART has been shown to outperform in terms of performance and efficiency.",
    },
    94: {
        "question": "How does context tuning impact the effectiveness of RAG-based planning systems compared to traditional semantic search approaches, particularly in terms of plan accuracy and reduction of hallucinations?",
        "gold_answer_research": "Context tuning in RAG-based planning systems significantly enhances contextual understanding and improves tool retrieval compared to traditional semantic search approaches. This leads to higher plan accuracy as context tuning helps in providing relevant and accurate responses to complex requests. Additionally, context tuning reduces hallucinations by ensuring that plans are generated using real-world context and information, thereby improving the overall effectiveness of RAG-based planning systems.",
        "gold_answer_marketing": "Context tuning in RAG-based planning systems improves plan accuracy and reduces hallucinations compared to traditional semantic search approaches. It enhances contextual understanding and context seeking abilities, leading to more relevant tool retrieval and improved plan generation. This ultimately results in better performance and accuracy in knowledge-intensive tasks.",
    },
    95: {
        "question": "How can the use of context compression techniques benefit retrieval-augmented generation models, particularly in terms of balancing performance improvements with resource limitations?",
        "gold_answer_research": "Context compression techniques can benefit retrieval-augmented generation models by allowing for the reduction of unnecessary information, thus improving the efficiency of the generation process. By compressing context, models can focus on the most relevant and useful information, balancing performance improvements with resource limitations. This helps in mitigating challenges such as slow generation process due to lengthy context and trade-offs in accuracy or costs. Additionally, context compression techniques can optimize the model's ability to filter relevant content and generate output, ultimately improving the overall performance of the retrieval-augmented generation system.",
        "gold_answer_marketing": "Context compression techniques can benefit retrieval-augmented generation models by improving performance without requiring excessive computational resources. These techniques help balance the trade-off between accuracy and costs, allowing models to handle longer sequences efficiently. This results in faster generation processes and optimized resource usage for better overall performance.",
    },
    102: {
        "question": "What are the primary methodologies and potential pitfalls for evaluating RAG systems in scenarios where ground-truth reference answers are unavailable?",
        "gold_answer_research": 'In the absence of human-annotated ground truths, developers often employ reference-free evaluation frameworks like Ragas, which utilize LLMs to automatically measure metrics such as answer faithfulness, context relevance, and answer relevance. Alternatively, system evaluators can adopt an "LLM-as-a-judge" approach to assign continuous scores, rank candidate outputs, or verify the presence of hallucinations via automated comparisons. However, a major pitfall in relying exclusively on automated AI judges is that these models are not perfectly deterministic and can produce misleading evaluations, underscoring the critical need to continually validate automated scoring against systematic human reviews.',
        "gold_answer_marketing": "When there are no “correct” answers to compare against, teams often use AI tools to evaluate whether responses are relevant, accurate, and grounded in the retrieved information. However, because AI-based evaluation can sometimes be inconsistent or misleading, it’s important to periodically validate those results with human review.",
    },
    103: {
        "question": "How does query expansion help search engines improve the relevance of documents returned to users?",
        "gold_answer_research": "Query expansion helps search engines improve the relevance of documents returned to users by elaborating original queries into more detailed versions while preserving the search intent. This process enhances the search engine's understanding of the user's needs, leading to more accurate and relevant document retrieval. By adding more context and depth to the query, query expansion helps the search engine retrieve documents that align more closely with what the user is looking for, ultimately improving the overall search results and user experience.",
        "gold_answer_marketing": "Query expansion helps search engines by elaborating original queries into more detailed versions, preserving the search intent. This process enhances the search engine's understanding of user needs, leading to more accurate and relevant document retrieval.",
    },
    108: {
        "question": "What is the recommended strategy for training large autoregressive language models with limited compute resources, as contributed by the Chinchilla team?",
        "gold_answer_research": "The Chinchilla team recommends that the number of training tokens should be doubled for every model size doubling to achieve better results on downstream tasks. They also suggest using larger, higher-quality training datasets to improve performance. Additionally, they mention the importance of balancing model size and efficiency to address computational costs and inference latency limitations. It is advised to focus on Transformer language models and consider sharing model parameters for quick task-switching when deploying as a service.",
        "gold_answer_marketing": "The Chinchilla team recommends doubling the number of training tokens for every model size doubling and using larger, higher-quality training datasets to achieve better results on downstream tasks.",
    },
    111: {
        "question": "What optimizer and default learning rate are recommended for KTO in practice?",
        "gold_answer_research": "For KTO in practice, it is recommended to start with the optimizer AdamW and a default learning rate of 5e-6. This learning rate should be adjusted as needed based on the performance of the model. It is important to remember that the performance of the aligned model is highly sensitive to the learning rate, so experimentation may be necessary to find the optimal rate for your specific application.",
        "gold_answer_marketing": "For KTO in practice, it is recommended to use the AdamW optimizer with a starting learning rate of 5e-6. This learning rate can be adjusted as needed for optimal performance.",
    },
    112: {
        "question": "How does the technique of reinforcement learning from human feedback (RLHF) leverage collected human preferences to improve the behavior of language models?",
        "gold_answer_research": "Reinforcement learning from human feedback (RLHF) leverages collected human preferences by first fitting a reward model to reflect these preferences. The RLHF technique then optimizes a language model policy to produce responses that align with high-reward preferences without deviating too far from the original model. This process allows language models to better understand user intentions, align with human preferences, and reduce the overall cost of communication. Additionally, RLHF helps improve the model's conversational abilities, coding proficiency, factuality, and task alignment by learning from human or automated preference judgments.",
        "gold_answer_marketing": "RLHF leverages collected human preferences to improve language models by fitting a reward model to human preferences and using reinforcement learning to optimize the language model policy. This helps the language model produce responses aligned with human intentions while minimizing drift from the original model.",
    },
    118: {
        "question": "How is external knowledge or information from retrieved texts, captions, or demonstrations typically incorporated into vision-and-language or multi-modal generation models to enhance their outputs?",
        "gold_answer_research": "External knowledge or information from retrieved texts, captions, or demonstrations is typically incorporated into vision-and-language or multi-modal generation models by allowing the model to refer to relevant examples from an external memory when generating images or text. This augmentation helps reduce the need for storing all knowledge inside the model, resulting in a more efficient use of parameters and training data. Additionally, models can use in-context examples for controlled generation, providing valuable guidance for generating accurate and detailed outputs. By accessing external memory, models can accommodate the growth and update of knowledge over time, leading to improved outputs in tasks like image captioning and text-to-image generation.",
        "gold_answer_marketing": "External knowledge is typically incorporated into vision-and-language or multi-modal generation models by augmenting them with the ability to refer to relevant examples from an external memory. This allows the models to access additional knowledge beyond what is stored inside the model itself, improving the quality of outputs by incorporating multi-modal information and enhancing dialog generation with external knowledge.",
    },
    119: {
        "question": "How does Retrieval Augmented Generation (RAG) maintain its effectiveness in handling both recent and infrequently discussed knowledge, especially in comparison to long-context models?",
        "gold_answer_research": "Retrieval Augmented Generation (RAG) maintains its effectiveness in handling both recent and infrequently discussed knowledge by leveraging a flexible data repository that acts as a non-parametric memory, allowing for easy updates and accommodating extensive long-tail knowledge. This approach mitigates the lack of long-tail knowledge and can encode confidential data. Additionally, RAG's retrieval capabilities reduce generation costs, support long contexts, and provide opportunities for addressing complex problems and integrative or summary questions that require reading a large amount of material to answer.",
        "gold_answer_marketing": "Retrieval Augmented Generation (RAG) maintains effectiveness by leveraging a flexible data repository that can easily update and store extensive long-tail knowledge, including confidential data. This non-parametric memory allows RAG to address complex problems by retrieving relevant passages from a large corpus, supporting long contexts, and reducing generation costs.",
    },
    123: {
        "question": "How does the automatic evaluation process using ChatGPT and Llama 3 distinguish between partially correct, completely correct, and incorrect responses, and how are these classifications reflected in their accuracy and F1 scores?",
        "gold_answer_research": "The automatic evaluation process using ChatGPT and Llama 3 distinguishes between partially correct, completely correct, and incorrect responses by first checking if the answer matches the ground truth exactly. If it does, it is considered accurate. If not, the responses are further evaluated by the two LLM evaluators to determine if they are accurate, incorrect, or missing. These classifications are reflected in their accuracy and F1 scores by showing different performance metrics for accurate, incorrect, and missing answers in both models, with Llama 3 generally outperforming ChatGPT in terms of precision, recall, and F1 score for accurate responses.",
        "gold_answer_marketing": "The automatic evaluation process using ChatGPT and Llama 3 distinguishes between accurate, incorrect, and missing responses by comparing them to the ground truth. This classification is reflected in their accuracy and F1 scores, with ChatGPT showing an average F1 score of 94.7% and Llama 3 showing an average F1 score of 98.9% compared to human evaluation.",
    },
    124: {
        "question": "What are some of the main challenges that Retrieval-Augmented Generation aims to address when applied to large language models, and how does integrating external knowledge bases help overcome these obstacles?",
        "gold_answer_research": "Retrieval-Augmented Generation (RAG) aims to address challenges such as hallucination, outdated knowledge, and non-transparent reasoning processes in large language models. By incorporating knowledge from external databases, RAG enhances accuracy and credibility in generation tasks, particularly for knowledge-intensive tasks. The integration of external knowledge bases helps provide real-time, relevant information to the generative model, improving the quality of the outputs and mitigating issues related to outdated or erroneous information in the model itself.",
        "gold_answer_marketing": "Retrieval-Augmented Generation aims to address challenges like hallucination, outdated knowledge, and non-transparency in large language models. By incorporating external knowledge bases, RAG enhances accuracy, credibility, and the overall quality of generated outputs for knowledge-intensive tasks.",
    },
    126: {
        "question": "How do different Retrieval Augmented Generation (RAG) methods vary in the stage at which retrieval is integrated into the pipeline, and what are some examples of techniques that incorporate retrieval during model pre-training versus tuning or inference?",
        "gold_answer_research": "Different RAG methods vary in the stage at which retrieval is integrated into the pipeline. Some techniques incorporate retrieval during model pre-training, where the retrieval component is jointly trained with the generative model from scratch. An example of this approach is denoising objectives similar to BART. On the other hand, some methods incorporate retrieval during tuning or inference stages, where a pre-trained generative model is augmented with retrieval components. An example of this is query-based RAG, which allows for modular flexibility and quick integration of pre-trained components during deployment.",
        "gold_answer_marketing": "Different Retrieval Augmented Generation (RAG) methods vary in when retrieval is integrated into the pipeline, with some incorporating retrieval during model pre-training (e.g., for latent representation-based RAG) and others during tuning or inference (e.g., query-based RAG). Examples of techniques include iterative retrieval during generation for richer context, recursive retrieval for breaking down complex problems, and input enhancement by feeding retrieved content during the input phase.",
    },
    128: {
        "question": "What are the computational and practical trade-offs associated with deploying highly autonomous Agentic RAG systems compared to simpler, fixed-pipeline Enhanced RAG systems?",
        "gold_answer_research": "While Agentic RAG systems offer high flexibility by allowing the language model to autonomously orchestrate multiple retrieval and reasoning steps, this autonomy significantly increases monetary costs, token usage, and end-to-end latency. Empirical comparisons show that Agentic RAG can be several times more expensive and slower than Enhanced RAG pipelines, often without yielding universally superior retrieval performance in noisier domains. Consequently, experts warn against prematurely adopting complex agentic frameworks when simpler, highly optimized pipelines utilizing explicit re-rankers or straightforward API calls would adequately suffice for the specific product requirements.",
        "gold_answer_marketing": "Agentic RAG systems can be more flexible because they allow AI to decide how to search for and combine information, but that flexibility often comes with higher costs and slower response times. In many cases, simpler RAG pipelines can deliver similar results more efficiently, so organizations should weigh the added complexity against the actual benefits.",
    },
    129: {
        "question": "Which automated tool employs LLMs to adjudicate quality scores for the evaluation of RAG models alongside ARES and TruLens?",
        "gold_answer_research": "The automated tool RAGAS employs LLMs to adjudicate the quality scores for the evaluation of RAG models, in addition to ARES and TruLens. These tools, along with benchmarks, create a robust framework for systematic evaluation of RAG models, as shown in Table IV. This approach can enhance the evaluation process by utilizing LLMs as a critical sample selector based on specific criteria for human annotators to evaluate.",
        "gold_answer_marketing": "RAGAS is the automated tool that, alongside ARES and TruLens, uses LLMs to adjudicate quality scores for evaluating RAG models.",
    },
    130: {
        "question": "What are some important considerations and recent advancements involved in making Retrieval Augmented Generation (RAG) systems suitable for use in real-world, production environments?",
        "gold_answer_research": "Some important considerations for making RAG systems suitable for real-world production environments include ensuring that the systems are developed and managed independently without conflicts or dependency issues, maintaining cleaner and more manageable development workflows, updating knowledge, handling long-tail data, mitigating data leakage, managing high training and inference costs, and integrating RAG within Large Language Models (LLMs) to enhance accuracy. Recent advancements in RAG systems focus on integrating information retrieval processes to enhance generation processes, pulling in information from external data sources such as PDFs, databases, or websites to ground generated content in accurate and current data. Additionally, recent research is focusing on methods to enhance the factual grounding of RAG outputs and analyzing costs and computational time required by different systems under various scenarios to help researchers and practitioners select the most appropriate system for their needs.",
        "gold_answer_marketing": "Considerations for making RAG systems suitable for production include managing high training and inference costs, updating knowledge, handling long-tail data, and mitigating data leakage. Recent advancements include the integration of RAG within Large Language Models, resulting in higher accuracy, better decision making, and enhanced capabilities in knowledge-intensive tasks. RAG systems retrieve relevant information from external sources, such as PDFs and databases, to ground generated content in accurate and current data for real-time applications.",
    },
    133: {
        "question": "Which framework is described as An Introspection Platform for RAG Evaluation?",
        "gold_answer_research": "The framework described as an introspection platform for RAG evaluation is Self-Reflective Retrieval-Augmented Generation (SELF-RAG). It enhances the quality and factuality of a Language and Logic Model (LLM) through retrieval and self-reflection, while maintaining the original creativity and versatility of the LLM. The framework leverages LRMs within RAG to improve information synthesis and knowledge retrieval effectively, with the model's inherent reasoning capabilities driving the process.",
        "gold_answer_marketing": "The framework described as an Introspection Platform for RAG Evaluation is SELF-RAG.",
    },
    134: {
        "question": "What benefits does Retrieval Augmented Generation (RAG) offer over traditional language models with respect to providing reliable and up-to-date answers, and how does its approach contribute to these improvements?",
        "gold_answer_research": "Retrieval Augmented Generation (RAG) models offer benefits over traditional language models by enhancing the factual grounding of their outputs through the explicit retrieval of relevant passages from a large corpus. This approach ensures that the answers provided are based on up-to-date and accurate knowledge. By integrating information retrieval with natural language generation, RAG models can provide reliable answers by incorporating real-time information and reducing the risk of producing incorrect or outdated responses. This dual-component framework contributes to improving the accuracy and credibility of the generated answers, particularly in knowledge-intensive domains, making it a promising solution for QA tasks.",
        "gold_answer_marketing": "Retrieval Augmented Generation (RAG) improves on traditional language models by explicitly retrieving up-to-date information from large databases, enhancing the accuracy and reliability of answers. This approach ensures that responses are contextually relevant and factually accurate, making it a valuable tool for knowledge-intensive tasks like question answering.",
    },
    135: {
        "question": "Why are documents in PDF format considered particularly valuable when implementing Retrieval Augmented Generation (RAG) systems?",
        "gold_answer_research": "Documents in PDF format are considered particularly valuable when implementing Retrieval Augmented Generation (RAG) systems because they contain dense and detailed information essential for training RAG models. PDFs are widely used for distributing high-value content like research papers, legal documents, technical manuals, and financial reports. Moreover, PDFs come in various forms, allowing access to a wide range of data types, from scientific data and technical diagrams to textual information. The complex formatting of PDFs poses challenges for accurate text extraction, making it essential to use reliable tools and methods for converting the PDF content into usable text for effective retrieval and generation.",
        "gold_answer_marketing": "PDF documents are essential for RAG applications because they contain dense, detailed information necessary for training RAG models. They are widely used for distributing high-value content like research papers, legal documents, technical manuals, and financial reports, making them ideal for knowledge-intensive tasks. PDFs allow access to a wide range of data types, from scientific data to technical diagrams, enhancing the accuracy and effectiveness of retrieval and generation processes.",
    },
    136: {
        "question": "What are some ways in which a Retrieval Augmented Generation (RAG) system ensures that the responses it generates are both contextually relevant and based on up-to-date information, especially when integrating knowledge from PDF documents?",
        "gold_answer_research": "One way a Retrieval Augmented Generation (RAG) system ensures contextually relevant and up-to-date responses is by integrating query-based RAG, which combines the user's query with insights from retrieved information to create a response. Additionally, RAG systems use dense retrieval methods to explicitly retrieve relevant passages from a large corpus, ensuring that the generated content is grounded in accurate and current data. By combining information retrieval techniques with generative models, RAG systems can provide responses that are not only contextually appropriate but also up-to-date, particularly when pulling information from domain-specific PDF documents.",
        "gold_answer_marketing": "A Retrieval Augmented Generation (RAG) system ensures contextually relevant and up-to-date responses by pulling in information from external data sources like PDFs, databases, or websites. This grounding in accurate and current data makes RAG ideal for knowledge intensive tasks, ensuring that the generated content is both relevant and up-to-date.",
    },
    139: {
        "question": "Because initial user queries are often ambiguous or overly brief, what techniques have been developed to transform and optimize these queries before they are sent to the retriever?",
        "gold_answer_research": "To bridge the semantic gap between short user queries and extensive document text, RAG systems employ query transformation techniques that use language models to rewrite, expand, or clarify the original input. Methods like HyDE prompt the model to generate a hypothetical answer first, utilizing this pseudo-document's embedding to search for real, semantically similar documents in the database. Furthermore, advanced systems like DeepRetrieval utilize reinforcement learning to train models to iteratively rewrite queries based on the actual performance metrics of the downstream retrieval system, ensuring the search strings are highly optimized for fetching evidence.",
        "gold_answer_marketing": " Because users often ask short or unclear questions, modern RAG systems use AI to rewrite or expand the query so it better matches the information stored in the knowledge base. These techniques help the system retrieve more relevant content and produce more accurate answers.",
    },
    140: {
        "question": "How is the RAG architecture specifically adapted to support software engineering tasks such as code generation and automatic program repair?",
        "gold_answer_research": "In software engineering contexts, RAG systems augment code generation by retrieving relevant API documentations, similar code examples, and abstract syntax trees (ASTs) to construct highly contextualized prompts for the language model. For tasks like automatic program repair, hybrid retrieval methods combine sparse and dense searches to locate similar historical buggy codes and their corresponding patches, feeding this data into sequence-to-sequence models to synthesize functional fixes. Because natural language queries often differ structurally from programming languages, specialized adaptations like execution feedback loops, AST-based retrieval, and instruction-tuned code encoders are crucial for bridging the semantic gap in code-related RAG applications.",
        "gold_answer_marketing": "In software engineering, RAG systems improve code generation by retrieving relevant documentation, code examples, and other technical context to guide the AI’s output. They can also help fix bugs by finding similar past coding issues and solutions, giving the AI examples it can use to generate a working repair.",
    },
    143: {
        "question": "How do retrieval-augmented generation models handle information from multiple languages or different types of data modalities when providing responses?",
        "gold_answer_research": "Retrieval-augmented generation models handle information from multiple languages or different data modalities by utilizing a retriever to gather relevant documents from external memory, which are then used by a generator to create predictions based on the retrieved documents. While these methods were initially designed for text, extending them to a multimodal setting presents challenges that require designing a suitable retriever and generator architecture. Recent research has shown progress in applying retrieval-augmented generation to task-oriented dialogues and improving accuracy with semantic search and hybrid query-based retrievers. Further advancements in this area aim to enhance the model's ability to handle diverse linguistic and modal information for more robust and effective responses.",
        "gold_answer_marketing": "Retrieval-augmented generation models use a retriever to gather relevant information across languages or data types before generating responses. By combining retrieved documents with the original query, these models can provide more comprehensive and accurate outputs. This approach helps ensure that responses are informed by a diverse range of information sources.",
    },
    145: {
        "question": "Which technique proposed by Zheng et al. (2023) involves invoking the judge LLM twice and swapping the order of two candidates to mitigate positional bias in LLM-based evaluation systems?",
        "gold_answer_research": 'The technique proposed by Zheng et al. (2023) to mitigate positional bias in LLM-based evaluation systems involves a swapping operation. This operation includes invoking the judge LLM twice and swapping the order of the two candidates in each instance. If the results from the two invocations are inconsistent, it is labeled a "tie," indicating the LLM\'s inability to confidently distinguish the quality of the candidates. This swapping operation technique is widely adopted in pairwise feedback synthesis to improve the accuracy of reward signals.',
        "gold_answer_marketing": "The technique proposed by Zheng et al. (2023) is the swapping operation, which involves invoking the judge LLM twice and swapping the order of the two candidates to mitigate positional bias in LLM-based evaluation systems.",
    },
    146: {
        "question": "How can large language models be utilized to improve the process of selecting or filtering retrieved content in retrieval-augmented generation, and what specific benefits does this provide compared to traditional retrieval methods?",
        "gold_answer_research": "Large language models can be utilized in retrieval-augmented generation by using their advanced natural language processing capabilities to understand and interpret the retrieved content. This allows for more precise selection or filtering of relevant information, improving the quality and accuracy of the generated output. Compared to traditional retrieval methods, this approach provides the benefit of leveraging contextual understanding and semantic relationships, resulting in more informed predictions and better performance in domain-specific or knowledge-intensive tasks.",
        "gold_answer_marketing": "Large language models can be used in retrieval-augmented generation to enhance the selection or filtering of retrieved content by providing more relevant and current information. This approach offers benefits like improved accuracy, efficiency, and effectiveness compared to traditional retrieval methods.",
    },
    150: {
        "question": "How can the use of large language models as evaluators influence the assessment of natural language generation tasks, and what are some of the approaches used to ensure their judgments align with those of human annotators?",
        "gold_answer_research": "The use of large language models (LLMs) as evaluators can significantly impact the assessment of natural language generation tasks by providing automated scoring and ranking capabilities. To ensure that their judgments align with those of human annotators, approaches such as conducting human studies to justify the use of LLMs for evaluation, measuring performance on a range of language understanding tasks, and testing generative language capabilities through automated and human evaluations can be employed. Additionally, utilizing queries curated by humans and comparing inter-human annotator agreement with LLM judgments can help validate the effectiveness of LLMs in evaluating natural language generation tasks.",
        "gold_answer_marketing": "Large language models (LLMs) can provide automated evaluations for natural language generation tasks, but human validation is still necessary for accuracy. Approaches such as comparing LLM judgments with human agreement and using curated queries help align LLM assessments with human annotators.",
    },
    151: {
        "question": "Which benchmark is described as a hierarchical and comprehensive safety benchmark for large language models?",
        "gold_answer_research": "The hierarchical and comprehensive safety benchmark for large language models described in the given context is called WriteBench. It is designed to assess the writing capabilities of LLMs across multiple domains and tasks, ensuring a fair comparison between Weaver and other generalist LLMs. WriteBench will be publicly available for evaluation purposes on GitHub at https://github.com/aiwaves-cn/WriteBench.",
        "gold_answer_marketing": "The Massively Multitask Language Understanding (MMLU) benchmark is described as a hierarchical and comprehensive safety benchmark for large language models.",
    },
    154: {
        "question": "How does the Tree of Thoughts approach leverage large language models to enhance problem-solving capabilities compared to more straightforward reasoning techniques?",
        "gold_answer_research": "The Tree of Thoughts approach extends traditional reasoning methods by exploring multiple possibilities at each step, creating a tree structure that allows for branching logical pathways. This enables the model to consider multiple reasoning trajectories simultaneously, avoiding traps caused by early mistaken assumptions. By promoting a step-by-step thinking process, the Tree of Thoughts technique enhances the problem-solving capabilities of large language models, enabling them to deliberate and solve complex tasks more effectively than traditional, linear methods.",
        "gold_answer_marketing": "The Tree of Thoughts approach breaks down problems into multiple steps and generates multiple thoughts per step, allowing for exploration of different reasoning possibilities. By creating a tree structure and utilizing search algorithms like BFS or DFS, it enables more in-depth evaluation of problem-solving paths, enhancing the capabilities of large language models.",
    },
    155: {
        "question": "How does the self-discover approach utilize large language models to autonomously generate reasoning strategies?",
        "gold_answer_research": "The self-discover approach leverages large language models (LLMs) like SELF-RAG to autonomously generate reasoning strategies by incorporating self-reflection mechanisms. Through self-reflection, the LLM can assess its knowledge limitations and determine when to retrieve relevant information, enabling autonomous decision-making in generating responses. This approach eliminates the need for external models during inference, streamlining the decision-making process and improving the model's output quality, including factuality evaluation. Additionally, by integrating reasoning and tool use, the LLM can iteratively refine its responses based on newly retrieved information, enhancing its overall performance in complex natural language tasks.",
        "gold_answer_marketing": "The self-discover approach empowers large language models to introspectively evaluate their own knowledge gaps and retrieve information only when necessary. Unlike traditional approaches, this method does not rely on external models for inference, allowing the model to actively manage retrieval autonomously. This process enhances reasoning capabilities and enables the model to refine its responses iteratively based on newly retrieved information.",
    },
    157: {
        "question": "How do existing evaluation frameworks designed for LLM-as-a-judge differ in the types of human and automated metrics they utilize to assess general performance, bias, and robustness across conversation, alignment, and multimodal tasks?",
        "gold_answer_research": "Existing evaluation frameworks for LLM-as-a-judge differ in the types of metrics they use to assess general performance, bias, and robustness. Some frameworks focus on metrics like Cohen's kappa, Discernment Score, and normalized accuracy to evaluate alignment between LLM predictions and manual judgments in conversation and alignment tasks. Others, like ALLURE proposed by Hasanbeig et al., aim to enhance evaluator robustness by iteratively incorporating demonstrations of significant deviations. Additionally, frameworks like MLLM-as-a-judge by Dongping Chen et al. assess multimodal tasks using vision-language benchmarks, showcasing a diversity of metrics and approaches in LLM evaluation.",
        "gold_answer_marketing": "Existing evaluation frameworks for LLM-as-a-judge vary in the types of metrics used to assess general performance, bias, and robustness across conversation, alignment, and multimodal tasks. They may include automated metrics like Cohen's kappa, Discernment Score, and normalized accuracy, as well as human judgment-based metrics to evaluate the overall competence of LLMs in various tasks. Additionally, some approaches incorporate demonstrations of significant deviations to enhance evaluator robustness, while others leverage insights from many-shot in-context learning for more thorough and fair assessments.",
    },
    160: {
        "question": "When conducting demographic and technical assessments of teams or research subjects, what types of data categories are typically collected and analyzed to ensure a comprehensive understanding of the group's composition and the methods used?",
        "gold_answer_research": "When conducting demographic and technical assessments of teams or research subjects, it is important to collect and analyze data categories such as age, gender, education level, professional background, and expertise in specific areas. By gathering information on these categories, you can ensure a comprehensive understanding of the group's composition and the methods used in your assessments. Additionally, it may be helpful to consider factors like cultural background, language proficiency, and geographical location to capture a more nuanced picture of the group being assessed. This detailed approach to data collection and analysis can provide valuable insights for making informed decisions and recommendations based on the gathered information.",
        "gold_answer_marketing": "Demographic data such as age, gender, education level, and technical data related to skills and experience are typically collected and analyzed for comprehensive understanding.",
    },
    161: {
        "question": "How does the evaluation process determine the level of alignment in the models being tested?",
        "gold_answer_research": "The evaluation process determines the level of alignment in the models by comparing the system-level judgments made by the language model (GPT-4) with those made by human annotators, using metrics such as Kendall Tau and Spearman rank correlation. At the example level, the agreement between the model and human annotators is measured using Fleiss κ. These metrics provide insights into the alignment of the language model with human intentions and indicate the reliability of model-based evaluation as an alternative to human evaluation.",
        "gold_answer_marketing": "The evaluation process determines the level of alignment in the models being tested by comparing system-level judgments by the language model and human annotators, as well as examining agreement at the example level.",
    },
    162: {
        "question": "What approaches can be used to improve the performance of an AI model on various datasets, and how do they compare in terms of effectiveness?",
        "gold_answer_research": "To improve the performance of an AI model on various datasets, you can consider combining your method with ways to filter the pretraining data or training the initial pretrained models using human data. Additionally, you could explore methods that improve models' truthfulness, such as WebGPT. Comparing the effectiveness of these approaches, it may be beneficial to experiment with different adaptation approaches in the low-data regime and evaluate their performance on tasks like MNLI-n. Fine-tuning models using different training datasets and varying the number of fine-tuning steps can also impact performance on public NLP datasets.",
        "gold_answer_marketing": "Approaches such as fine-tuning with different datasets, filtering pretraining data, and combining methods to improve model truthfulness can be used to enhance the performance of an AI model on various datasets. However, the effectiveness of these approaches may vary depending on the specific task and dataset.",
    },
    165: {
        "question": "What are some common strategies for addressing the ethical and social risks associated with the deployment of language models, according to recent research findings?",
        "gold_answer_research": "Recent research findings suggest that common strategies for addressing the ethical and social risks associated with the deployment of language models include implementing alignment techniques to ensure that the models are helpful, honest, and harmless. These alignment techniques involve fine-tuning approaches such as reinforcement learning from human feedback to train the models to follow a broad class of written instructions. Additionally, it is important to consider the potential harms of language models in real-world applications and to evaluate how their outputs are used, especially in safety-critical situations. Furthermore, regulating access to large language models and incorporating diverse values-targeted datasets can help mitigate the risks of biased outputs, private data leaks, and misinformation generation.",
        "gold_answer_marketing": "Recent research findings suggest that common strategies for addressing ethical and social risks associated with the deployment of language models include mitigating biases, protecting private data, preventing the generation of misinformation, and ensuring alignment with human intentions to be helpful, honest, and harmless. These strategies aim to minimize the potential harms that language models may cause in various domains, such as medical diagnoses, employment, housing, and law enforcement.",
    },
    168: {
        "question": "What categories are the listed companies classified into, and what are some examples of tasks that can be performed in relation to text extraction, generation, rewriting, and chat services based on the given content?",
        "gold_answer_research": "The listed companies are classified as follows: Apple falls under the category of Technology, Facebook is categorized as Social Media, and Fedex's category is not specified. Some examples of tasks that can be performed in relation to text extraction include salient span masking, named entity identification, and adding an empty null document. For text generation, tasks can include natural language generation, speech recognition, and machine translation. For rewriting, tasks can involve summarization, paraphrasing, and producing rap lyrics based on a given article. Chat services can include customer assistance, complaint resolution, and information retrieval.",
        "gold_answer_marketing": "Apple is classified into the Technology category, Facebook is classified into the Social Media category, and Fedex is not classified. Tasks that can be performed in relation to text extraction include salient span masking and adding an empty null document. Tasks related to text generation include speech recognition, machine translation, and natural language generation. For rewriting, tasks can include summarization and rewriting rap lyrics. Chat services can involve customer assistance and complaints.",
    },
    171: {
        "question": "How does the use of retrieval-augmented generation methods contribute to improving reasoning or factual accuracy in large language models?",
        "gold_answer_research": "Retrieval augmented generation methods contribute to improving reasoning or factual accuracy in large language models by explicitly retrieving relevant passages from a large corpus and incorporating this information into the generation process. This enhances the factual grounding of outputs by providing up-to-date knowledge. By augmenting the input of LLMs with relevant passages, RAG methods reduce factual errors in knowledge-intensive tasks, improving the overall quality of generations and enhancing the versatility of LLMs. This approach combines the strengths of both factual-based and reasoning-oriented methods to address multi-step inference problems effectively.",
        "gold_answer_marketing": "Retrieval-augmented generation methods enhance the factual grounding of Large Language Models by explicitly retrieving relevant passages from a large corpus and incorporating this information into the generation process. This approach helps improve the reasoning and factual accuracy of the outputs by ensuring they are based on up-to-date knowledge and information.",
    },
    179: {
        "question": "Which prompt-based approach for agentic reasoning employs an interleaved sequence of Thought, Action, and Observation in its core mechanism, and is specifically mentioned as a foundational method to mitigate hallucination compared to Chain-of-Thought (CoT)?",
        "gold_answer_research": "The prompt-based approach for agentic reasoning that employs an interleaved sequence of Thought, Action, and Observation in its core mechanism, and is specifically mentioned as a foundational method to mitigate hallucination compared to Chain-of-Thought (CoT) is ReAct (Reason+Act) [Yao et al., 2023]. ReAct aims to create synergy between reasoning processes and action-taking capabilities within an LLM by prompting the model with examples that demonstrate this sequence. This method is designed to reduce hallucinations and improve decision-making transparency by incorporating external information via actions.",
        "gold_answer_marketing": "The prompt-based approach for agentic reasoning that employs an interleaved sequence of Thought, Action, and Observation in its core mechanism and is specifically mentioned as a foundational method to mitigate hallucination compared to Chain-of-Thought (CoT) is ReAct (Reason+Act) [Yao et al., 2023].",
    },
    183: {
        "question": "How do language model pre-training tasks contribute to the effectiveness of open-domain question answering systems?",
        "gold_answer_research": "Language model pre-training tasks play a crucial role in enhancing the effectiveness of open-domain question answering systems. By leveraging tasks such as Next Sentence Prediction (NSP) and domain-specific pre-training, models like BERT can better handle noisy and irrelevant contexts, leading to improved performance. Additionally, augmenting queries with relevant contexts can significantly enhance the unsupervised machine reading capabilities of pre-trained language models, ultimately improving their ability to provide accurate and up-to-date information for dynamic knowledge-intensive tasks.",
        "gold_answer_marketing": "Language model pre-training tasks contribute to the effectiveness of open-domain question answering systems by providing a foundation of knowledge and context for the model to build upon. This allows the model to better understand and generate answers to a wide range of questions. By fine-tuning the pre-trained model on specific tasks or domains, it can perform even better in answering questions accurately.",
    },
    186: {
        "question": "What roles do classic and neural information retrieval systems play in locating relevant context for answering questions?",
        "gold_answer_research": "Classic information retrieval systems focus on retrieving relevant documents based on keyword matching and other traditional techniques, while neural information retrieval systems utilize dense representations and neural networks to capture semantic relationships between queries and documents. Classic systems excel at efficiently retrieving relevant information based on exact matches, while neural systems are adept at understanding complex relationships and context within documents, thereby improving accuracy in answering questions that require deeper comprehension. Both systems play essential roles in locating relevant context for answering questions, with classic systems offering efficiency and neural systems providing enhanced understanding and accuracy in retrieving pertinent information.",
        "gold_answer_marketing": "Classic information retrieval systems focus on utilizing term-based vectors and contextual references through multiple retrieval iterations, while neural information retrieval systems involve neural network architectures to learn dense representations of text for enhanced retrieval capability. Neural IR is a new category of methods that aim to locate relevant context more efficiently, but it is not always necessary to outperform classic systems in order to be effective in answering questions.",
    },
    189: {
        "question": "How can instruction prompting improve model alignment and efficiency compared to few-shot learning?",
        "gold_answer_research": "Instruction prompting can improve model alignment and efficiency compared to few-shot learning by providing task-specific representations that can be used for multiple downstream language tasks without any additional training. By encoding inputs together with task instructions, the model can generate more accurate outputs based on the prompt provided, leading to improved performance on held-out tasks. Additionally, fine-tuning language models with instructions can enhance model alignment by optimizing input word embeddings instead of fine-tuning, resulting in better efficiency and scalability in handling larger sequence lengths and more complex tasks.",
        "gold_answer_marketing": "Instruction prompting can improve model alignment and efficiency by providing task-specific representations without needing additional training. This approach uses input-output pairs to fine-tune a pretrained language model to generate outputs based on provided prompts, which enhances performance on various tasks. This method contrasts with few-shot learning, where models are optimized on a range of tasks but instruction prompting focuses on improving performance on specific tasks with minimal additional training.",
    },
    193: {
        "question": "How can language models be augmented via external tools or APIs to extend their capabilities?",
        "gold_answer_research": "To augment language models with external tools or APIs, models like TALM and Toolformer fine-tune a language model to learn to use external tool APIs. The dataset is expanded based on whether an added API call annotation can enhance model outputs. This approach improves the generalization of language models by integrating parameterized knowledge from language models with non-parameterized data from external knowledge bases, as seen in the research on retrieval-augmented language models. This method significantly enhances the capabilities of language models by leveraging external tools and APIs to expand their functionality and improve performance in specialized tasks.",
        "gold_answer_marketing": "By fine-tuning language models with external tool APIs, such as TALM and Toolformer, their capabilities can be extended. This process involves expanding the dataset to assess if adding new API call annotations improves the model's output quality. This approach enhances generalization and effectiveness of language models.",
    },
    194: {
        "question": "What are some advantages of using attention mechanisms in neural network architectures?",
        "gold_answer_research": "Some advantages of using attention mechanisms in neural network architectures include the ability to relate different positions within a sequence, allowing for the computation of representations of the same sequence. This can be very useful for tasks such as machine reading, abstractive summarization, or image description generation. Attention mechanisms can also help in reducing memory and storage usage, which is beneficial for large Transformer models trained with algorithms like Adam. Additionally, attention mechanisms can address the issue of fixed-length context vectors, enabling neural networks to remember longer sentences and improve overall performance in various tasks.",
        "gold_answer_marketing": "Using attention mechanisms in neural network architectures can help improve memory and storage efficiency. Additionally, attention mechanisms can enhance the model's ability to relate different positions within a sequence, making it useful for tasks such as machine reading and image description generation.",
    },
    195: {
        "question": "How does self-attention differ from traditional attention mechanisms in sequence modeling?",
        "gold_answer_research": "Self-attention differs from traditional attention mechanisms in sequence modeling by focusing on relating different positions within a single sequence to compute a representation of that same sequence. Traditional attention mechanisms often involve aligning and weighting different parts of the input sequence to output a context vector. In contrast, self-attention directly looks at the relationships between all positions in the sequence simultaneously through the Key, Value, and Query mechanism, allowing for more comprehensive modeling of dependencies within the sequence. Additionally, self-attention has shown to be more effective in tasks such as machine reading, abstractive summarization, and image description generation compared to traditional attention mechanisms.",
        "gold_answer_marketing": "Self-attention differs from traditional attention mechanisms by focusing on different positions within the same sequence to compute a representation of that sequence, allowing for more efficient processing of information. This is in contrast to traditional attention mechanisms that typically focus on aligning different sequences or inputs in a modeling task.",
    },
    200: {
        "question": "What mechanisms can be used to enable agents to break down complex tasks into smaller, manageable steps?",
        "gold_answer_research": "One mechanism that can be used to enable agents to break down complex tasks into smaller, manageable steps is task decomposition. By breaking down large tasks into smaller subgoals, agents can efficiently handle complex tasks. Another mechanism is self-reflection and refinement, where agents can reflect on past actions, learn from mistakes, and refine their approach for future steps, improving the quality of final results. Additionally, utilizing advanced configurations offered by external APIs and tools can help agents understand and utilize options like result filtering, sorting criteria, specifying search domains, or interacting with structured databases, ultimately supporting more targeted and efficient task completion aligned with task demands.",
        "gold_answer_marketing": "Agents can use subgoal and decomposition techniques to break down large tasks into smaller, more manageable steps. By reflecting on past actions, learning from mistakes, and refining their approach, agents can improve the quality of their final results.",
    },
    201: {
        "question": "How do autonomous systems incorporate short-term and long-term memory, and what types of external storage or retrieval methods are leveraged?",
        "gold_answer_research": "Autonomous systems incorporate short-term memory through in-context learning, allowing the model to learn and retain information for immediate use. Long-term memory is utilized to store and recall extensive information over extended periods, often by utilizing an external vector store for fast retrieval. External storage and retrieval methods such as memory banks, document indexes, or memory streams are leveraged to provide a comprehensive repository of experiences and information for the autonomous systems to access and utilize in decision-making processes.",
        "gold_answer_marketing": "Autonomous systems utilize short-term memory for in-context learning and long-term memory for retaining and recalling vast amounts of information. External storage methods like memory banks and retrieval models are often used for fast data retrieval and processing.",
    },
    206: {
        "question": "What are the primary differences between white-box and black-box adversarial attacks?",
        "gold_answer_research": "White-box attacks involve attackers having full access to the model architecture, weights, and training pipeline, allowing them to obtain gradient signals for adversarial attacks. On the other hand, black-box attacks assume attackers only have access to an API-like service without detailed information about the model. White-box attacks typically require knowledge of the model's internal workings, while black-box attacks rely on external input-output interactions with the model, making them more challenging to execute. Additionally, white-box attacks often result in nonsensical prompts and can be detected by examining perplexity, whereas black-box attacks may use token manipulation or jailbreak prompting to trigger model failures while retaining semantic meanings.",
        "gold_answer_marketing": "White-box attacks have full access to model details like weights and architecture, while black-box attacks only have access to input-output interface like an API. White-box attacks are more powerful but black-box attacks are based on limited information.",
    },
    213: {
        "question": "How can external knowledge sources be leveraged to reduce or detect hallucinations in generated content?",
        "gold_answer_research": "External knowledge sources can be leveraged to reduce or detect hallucinations in generated content by integrating external or in-context knowledge during reasoning. By retrieving structured sources like databases or web content, models can provide factual grounding and reduce hallucinations. Additionally, utilizing internal contexts like prior interactions or training examples can enhance contextual coherence and help bridge logical gaps, ultimately improving the quality of the generated content. These strategies, such as IAG and RA-DT, aim to make the model less reliant on irrelevant passages and more accurate in its outputs.",
        "gold_answer_marketing": "External knowledge sources can be leveraged to reduce or detect hallucinations in generated content by integrating structured data from databases or web content, providing factual grounding. This can help bridge logical gaps and enhance contextual coherence in the generated output.",
    },
    215: {
        "question": "What are the effects of fine-tuning on new knowledge with respect to a model’s tendency to hallucinate?",
        "gold_answer_research": "Fine-tuning LLMs on new knowledge can lead to slower learning of examples with new knowledge compared to examples consistent with pre-existing knowledge. However, once the new knowledge examples are learned, it can increase the model's tendency to hallucinate. Using retrieval to ground model generation helps reduce hallucination, while error rates are higher for rarer entities and facts mentioned later in generation tasks. Platforms like FAVABench provide benchmarks for evaluating fine-grained hallucination errors in model responses.",
        "gold_answer_marketing": "Fine-tuning on new knowledge may initially slow down the learning process in LLMs compared to consistent knowledge. However, once the new knowledge is learned, it can actually reduce the model's tendency to hallucinate.",
    },
    217: {
        "question": "What approaches exist for calibrating models to better handle questions where the correct answer is unknown or unanswerable?",
        "gold_answer_research": "There are several approaches for calibrating models to handle questions with unknown or unanswerable correct answers. One approach is to measure the model's output uncertainty when faced with such questions. Another method is to prompt the model to generate responses to unanswerable questions, which may trigger hallucinations. Benchmarks like TruthfulQA and SelfAware are used to evaluate how well models can generate truthful responses in such cases. Additionally, converting claims into questions, sampling multiple times from the model, and computing aggregated scores can help improve the model's handling of unknown or unanswerable questions.",
        "gold_answer_marketing": "Approaches for calibrating models to better handle questions where the correct answer is unknown or unanswerable include using the model's own confidence level as a proxy for truthfulness and implementing reference-free methods that rely on the model's output probabilities. These methods help ensure that the model accurately assesses its own uncertainty when facing such questions.",
    },
    220: {
        "question": "What challenges can arise from relying solely on automated or AI-based evaluation methods?",
        "gold_answer_research": "Relying solely on automated or AI-based evaluation methods can lead to challenges such as biases in the outputs, irrelevance, toxicity, or bias in the responses, disjointed or incoherent outputs when integrating retrieved information with different tasks, redundancy in responses when similar information is retrieved from multiple sources, and subjective preferences impacting the evaluation process. Additionally, automated evaluation systems may have noticeable biases and may not always provide accurate assessments of the AI applications. It is important to supplement automated evaluation with human evaluation to ensure comprehensive and reliable feedback on the product's performance.",
        "gold_answer_marketing": "Relying solely on automated or AI-based evaluation methods can lead to biased, irrelevant, or toxic outputs, which can lower the quality and reliability of responses. Without human evaluation, integration of retrieved information can be challenging, resulting in disjointed or repetitive outputs. Additionally, subjective preferences may play a significant role, impacting the accuracy and relevance of the evaluations.",
    },
}


test_questions = {
    10: {
        "question": "Which method incorporates relative position information by rotating the affine-transformed word embedding vector according to its position index, as described in the context of rotary position embedding?"
    },
    12: {
        "question": "How are annotators instructed to determine which portions of a paper should be used to justify answers in the QASPER annotation process, and what considerations are involved when selecting evidence?"
    },
    17: {
        "question": "How does LoRA manage to minimize inference time overhead, and what is the role of its low-rank update structure in enabling efficient parameter adaptation compared to traditional adapter-based methods?"
    },
    24: {
        "question": "How is reward modeling applied to GPT-3 models to improve alignment with human preferences, and what are the key strategies used to collect and train on human comparison data for this technique?"
    },
    37: {
        "question": "How does InstructGPT 175B respond differently from GPT-3 175B when given a prompt in Swedish, particularly regarding the use of language and adherence to instructions?"
    },
    46: {
        "question": "How does retrieval augmentation enhance the capabilities of multimodal Transformer-based models in generating both text and images, and what architectural components are necessary to support handling sequences of multiple data types?"
    },
    53: {
        "question": "How does the use of QLoRA with different quantization schemes impact the performance of LLaMA models across various dataset types and model sizes, particularly when evaluated on a comprehensive language understanding benchmark?"
    },
    56: {
        "question": "How does the quantization process in large language models impact their ability to preserve model quality compared to alternative techniques, and what are some challenges or trade-offs associated with quantization methods such as SmoothQuant and LLM.int8()?"
    },
    59: {
        "question": "What is the name of the algorithm that optimizes language models from human preferences using a simple binary cross-entropy objective, avoiding explicit reward modeling or reinforcement learning, and is compared to PPO-based RLHF in effectiveness?"
    },
    61: {
        "question": "Which author derived the DPO objective, proved its theoretical properties, and contributed to the PPO and reward learning baselines?"
    },
    65: {
        "question": "How does the DPO approach address user requests that involve privacy concerns or potentially illegal activities, and how does this compare to responses that provide only background information about the subject?"
    },
    78: {
        "question": "How do annotation scores for informativeness, clarity, and readability vary depending on different types of questions?"
    },
    86: {
        "question": "Which inference-time algorithm causes a large drop in PopQA and ASQA performance by always retrieving and using the top one document only, similar to standard RAG approaches?"
    },
    114: {
        "question": "How does the performance of models trained with KTO compare to those aligned using SFT, DPO, and ORPO across different evaluation datasets, and what do the results suggest about the impact of different KTO variants and settings?"
    },
    117: {
        "question": "Which model for multi-hop question answering emulates mammalian brain knowledge storage with KG triples and employs a personalized PageRank algorithm for retrieval?"
    },
    120: {
        "question": "How do retrieval-augmented generation methods enhance question answering capabilities in contexts where both structured data, such as knowledge graphs or tables, and unstructured text are involved?"
    },
    121: {
        "question": "Which benchmark provides 4,409 question-answer pairs, mock APIs to simulate web and Knowledge Graph search, and was the basis for a KDD Cup 2024 challenge?"
    },
    158: {
        "question": "What is the definition of beamforming steering matrix and what key goal does it serve in relation to transmit antennas and signal-to-noise ratio (SNR)?"
    },
    164: {
        "question": "Which framework remains limited by the lack of iterative feedback or dynamic retrieval, and is described as having issues with retrieval adequacy, reasoning depth, and system adaptability?"
    },
    166: {
        "question": "Which approach in code generation tasks retrieves code documentation via OSCAT libraries to ensure syntactic accuracy and executable logic?"
    },
    169: {
        "question": "How does retrieval-augmented generation leverage external information sources to enhance the reasoning abilities of large language models during complex question answering tasks?"
    },
    173: {
        "question": "What are some of the unique retrieval and reasoning challenges that RAG-based systems encounter when applied to web-based tasks requiring agentic planning and dynamic tool use?"
    },
    185: {
        "question": "How can answer extraction models be jointly trained with retrieval models, and what are the benefits of end-to-end approaches?"
    },
    187: {
        "question": "In what ways can large pretrained language models be used for closed-book question answering?"
    },
    197: {
        "question": "What is the significance of the key, value, and query concepts in transformer models?"
    },
    205: {
        "question": "What are the main limitations or challenges faced by large language model-powered autonomous agents when executing real-world tasks?"
    },
    212: {
        "question": "What are some common causes leading to unfaithful or fabricated outputs in large language models?"
    },
    214: {
        "question": "Which types of evaluation metrics or benchmarks are used to assess factuality in language model outputs?"
    },
    216: {
        "question": "How do different sampling strategies during text generation impact factual accuracy and hallucination rates?"
    },
    225: {
        "question": "What actor plays the role of Thanos in the Marvel Universe and the role of Cable in Deadpool 2?"
    },
}

## 0s My RAG Pipeline

In [2]:
%%capture
%pip install -qU langchain langchain-community langchain-huggingface langchain-qdrant langchain-ollama langchain-classic
%pip install langgraph
%pip install -qU qdrant-client sentence-transformers arxiv pymupdf
%pip install -qU transformers accelerate bitsandbytes
# hf_transfer: chunked + resumable HF downloads. Avoids the silent-stall
# failure mode where a dropped TCP connection hangs the default downloader.
%pip install -qU hf_transfer

%pip install -q -U xmltodict

%pip install -q -U cohere

%pip install -q -U langchain-cohere

%pip install -q -U wikipedia

%pip install bert-score

%pip install -q rouge-score

In [3]:
# Optional quick package/version check (fails fast if a package is missing)
import importlib.metadata as md


for pkg in ["transformers", "accelerate", "langchain", "langchain-huggingface"]:
    print(f"{pkg}: {md.version(pkg)}")

transformers: 5.5.3
accelerate: 1.13.0
langchain: 1.2.15
langchain-huggingface: 1.2.1

In [5]:
# Authenticate to Hugging Face and Cohere locally if needed as well
import os

try:
    from IPython import get_ipython as _get_ipython

    IS_COLAB = "google.colab" in str(_get_ipython())
except Exception:
    IS_COLAB = False


def _load_secret(name: str, default: str = "") -> str:
    # Prefer existing env var; then Colab secrets if available.
    env_val = os.environ.get(name)
    if env_val:
        return env_val
    if IS_COLAB:
        try:
            from google.colab import userdata  # type: ignore

            value = userdata.get(name)
            if value:
                os.environ[name] = value
                return value
        except Exception as e:
            print(f"Could not load Colab secret {name}: {e}")
    return default


HF_TOKEN = _load_secret("HF_TOKEN")
COHERE_API_KEY = _load_secret("COHERE_API_KEY")
USER_AGENT = _load_secret("USER_AGENT", default="Colab-RAG-Assignment5/1.0")

print(f"Colab runtime: {IS_COLAB}")
print(f"HF token loaded: {bool(HF_TOKEN)}")
print(f"Cohere key loaded: {bool(COHERE_API_KEY)}")
print(f"User-Agent set: {bool(USER_AGENT)}")

Colab runtime: True
HF token loaded: True
Cohere key loaded: True
User-Agent set: True

In [6]:
import locale
import time
from typing import TypedDict

import bs4
import langchain
import numpy as np
import pandas as pd
import torch
from huggingface_hub import whoami
from IPython import display
from langchain_classic.retrievers.document_compressors import CrossEncoderReranker
from langchain_cohere import ChatCohere
from langchain_community.cross_encoders import HuggingFaceCrossEncoder
from langchain_community.document_loaders import (
    PyMuPDFLoader,
    WebBaseLoader,
    WikipediaLoader,
)
from langchain_huggingface import (
    ChatHuggingFace,
    HuggingFaceEmbeddings,
    HuggingFacePipeline,
)
from langchain_qdrant import QdrantVectorStore
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langgraph.graph import END, START, StateGraph
from sklearn.metrics.pairwise import cosine_similarity
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    GenerationConfig,
    pipeline,
)

import re

from bert_score import BERTScorer
from rouge_score import rouge_scorer

# Single instance reused across all eval calls
_rouge_scorer = rouge_scorer.RougeScorer(
    ["rouge1", "rouge2", "rougeL"], use_stemmer=True
)

COHERE_API_KEY = os.environ.get("COHERE_API_KEY")
HF_TOKEN = os.environ.get("HF_TOKEN")
USER_AGENT = os.environ.get("USER_AGENT")

if HF_TOKEN:
    try:
        user_info = whoami(token=HF_TOKEN)
        print(f"HF auth: {user_info.get('name', 'ok')}")
    except Exception as e:
        print(f"HF auth check skipped: {e}")
else:
    print("HF token not found. Cohere configs can still run.")

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

HF auth: cfrishberg65
Device: cuda

In [7]:
locale.getpreferredencoding = lambda: "UTF-8"

## 1s. Documents and Chunking

### ArXiv Docs

In [8]:
arxiv_ids = [
    "2005.11401",
    "2104.07567",
    "2104.09864",
    "2105.03011",
    "2106.09685",
    "2203.02155",
    "2203.15556",
    "2211.09260",
    "2211.12561",
    "2212.09741",
    "2305.14314",
    "2305.18290",
    "2306.15595",
    "2309.08872",
    "2309.15217",
    "2310.06825",
    "2310.11511",
    "2311.08377",
    "2312.05708",
    "2401.06532",
    "2401.17268",
    "2402.01306",
    "2402.19473",
    "2406.04744",
    "2312.10997",
    "2410.12812",
    "2410.15944",
    "2411.16594",
    "2404.00657",
    "2601.07711",
    "2507.09477",
    "2506.10408",
]

### Wikipedia Docs

In [9]:
wiki_docs = {
    "Generative Artificial Intelligence": 4,
    "Information Retrieval": 2,
    "Large Language Models": 2,
    "Retrieval Augmented Generation": 2,
}

### Blog Entries about Open Domain QA

In [10]:
blogs = [
    "https://lilianweng.github.io/posts/2020-10-29-odqa/",
    "https://lilianweng.github.io/posts/2023-03-15-prompt-engineering/",
    "https://lilianweng.github.io/posts/2018-06-24-attention/",
    "https://lilianweng.github.io/posts/2023-10-25-adv-attack-llm/",
    "https://lilianweng.github.io/posts/2024-07-07-hallucination/",
    "https://huyenchip.com/2025/01/16/ai-engineering-pitfalls.html",
    "https://blog.langchain.com/the-rise-of-context-engineering/",
]

### Text Splitter

In [11]:
# Text splitter function to experiment with different chunk sizes and overlaps


def create_text_splitter(
    chunk_size: int, chunk_overlap: int
) -> RecursiveCharacterTextSplitter:
    return RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
    )

### Doc loader functions

In [ ]:
# Document loaders for Arxiv, Wikipedia, and blogs.
#
# Each loader:
#   - prints per-item progress so a stall is visible in real time
#   - uses explicit HTTP timeouts so one dead URL can't hang the notebook
#   - isolates per-item failures (a bad PDF skips instead of killing the run)
#   - caches raw arxiv PDFs on disk so reruns skip the network entirely

# decided to organize them here instead of in a separate file to keep all the data loading logic in one place for easier debugging and modification during development.
import shutil
from pathlib import Path as _Path

import requests

ARXIV_PDF_CACHE = _Path("arxiv_pdfs")
HTTP_TIMEOUT = 30  # seconds per request


def _download_arxiv_pdf(
    arxiv_id: str, dest_dir: _Path, timeout: int = HTTP_TIMEOUT
) -> _Path | None:
    """Download an arxiv PDF to dest_dir; return the local path or None on failure."""
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest = dest_dir / f"{arxiv_id}.pdf"
    if dest.exists() and dest.stat().st_size > 0:
        return dest

    url = f"https://arxiv.org/pdf/{arxiv_id}.pdf"
    try:
        with requests.get(url, stream=True, timeout=timeout) as r:
            r.raise_for_status()
            tmp = dest.with_suffix(".pdf.part")
            with open(tmp, "wb") as f:
                shutil.copyfileobj(r.raw, f)
            tmp.rename(dest)
        return dest
    except Exception as e:
        print(f"! arxiv {arxiv_id} download failed: {e}")
        if dest.exists():
            dest.unlink()
        return None


def load_arxiv_documents(
    arxiv_ids: list,
    text_splitter: RecursiveCharacterTextSplitter,
    load_max_docs: int = 1,
    verbose: bool = True,
    cache_dir: _Path = ARXIV_PDF_CACHE,
) -> list:
    docs = []
    total = len(arxiv_ids)
    for i, arxiv_id in enumerate(arxiv_ids, start=1):
        if verbose:
            print(f"  [{i}/{total}] arxiv:{arxiv_id}", flush=True)
        pdf_path = _download_arxiv_pdf(arxiv_id, cache_dir)
        if pdf_path is None:
            continue
        try:
            loaded = PyMuPDFLoader(str(pdf_path)).load()
        except Exception as e:
            print(f"    ! arxiv {arxiv_id} parse failed: {e}")
            continue
        docs.extend(loaded[:load_max_docs] if load_max_docs else loaded)

    if not docs:
        if verbose:
            print("Arxiv: 0 docs loaded.")
        return []

    splits = text_splitter.split_documents(docs)
    for idx, chunk in enumerate(splits):
        chunk.metadata["split_id"] = idx

    if verbose:
        print(f"Arxiv docs={len(docs)} splits={len(splits)}")
    return splits


def load_wiki_documents(
    wiki_queries: dict,
    text_splitter: RecursiveCharacterTextSplitter,
    verbose: bool = True,
) -> list:
    docs = []
    total = len(wiki_queries)
    for i, (query, max_docs) in enumerate(wiki_queries.items(), start=1):
        if verbose:
            print(f"  [{i}/{total}] wiki:{query!r}", flush=True)
        try:
            loaded = WikipediaLoader(query=query, load_max_docs=max_docs).load()
        except Exception as e:
            print(f"    ! wiki {query!r} failed: {e}")
            continue
        docs.extend(loaded)

    if not docs:
        if verbose:
            print("Wiki: 0 docs loaded.")
        return []

    splits = text_splitter.split_documents(docs)
    for idx, split in enumerate(splits):
        split.metadata["split_id"] = idx

    if verbose:
        print(f"Wiki docs={len(docs)} splits={len(splits)}")
    return splits


def load_blog_documents(
    document_paths: list,
    text_splitter: RecursiveCharacterTextSplitter,
    user_agent: str | None = None,
    verbose: bool = True,
) -> list:
    docs = []
    total = len(document_paths)
    for i, path in enumerate(document_paths, start=1):
        if verbose:
            print(f"  [{i}/{total}] blog:{path}", flush=True)
        kwargs = {
            "web_path": path,
            "bs_kwargs": {
                "parse_only": bs4.SoupStrainer(
                    class_=("post-content", "post-title", "post-header")
                )
            },
            "requests_kwargs": {"timeout": HTTP_TIMEOUT},
        }
        if user_agent:
            kwargs["header_template"] = {"User-Agent": user_agent}
        try:
            loader = WebBaseLoader(**kwargs)
            loaded = loader.load()
        except Exception as e:
            print(f"    ! blog {path} failed: {e}")
            continue
        docs.extend(loaded)

    if not docs:
        if verbose:
            print("Blogs: 0 docs loaded.")
        return []

    for idx, doc in enumerate(docs):
        doc.metadata["doc_num"] = idx
        doc.metadata["doc_source"] = "WWW"

    splits = text_splitter.split_documents(docs)
    for idx, split in enumerate(splits):
        split.metadata["split_id"] = idx

    if verbose:
        print(f"Blogs docs={len(docs)} splits={len(splits)}")
    return splits

## 2s Embedding Model

In [ ]:
# given models we can use
embedding_models = [
    "all-MiniLM-L6-v2",
    "multi-qa-mpnet-base-dot-v1",
    "all-mpnet-base-v2",
    "all-distilroberta-v1",
    "multi-qa-distilbert-cos-v1",
]

# one of many functions I had to write to work around HF downloading issues in Colab + running locally.


def _ensure_hf_model(repo_id: str, max_retries: int = 4) -> None:
    """
    Pre-download a HuggingFace model with resume-on-failure.

    This runs before HuggingFaceEmbeddings() so the library loads from cache
    instead of doing its own (non-resumable) download path.
    """
    from huggingface_hub import snapshot_download
    from huggingface_hub.utils import HfHubHTTPError

    candidates = [repo_id]
    if "/" not in repo_id:
        candidates.append(f"sentence-transformers/{repo_id}")

    last_err = None
    for candidate in candidates:
        for attempt in range(1, max_retries + 1):
            try:
                snapshot_download(
                    repo_id=candidate,
                    max_workers=2,
                    # Skip duplicate format variants (TF, Flax, ONNX, .bin when
                    # safetensors exists). avoids
                    # the runtime-disconnect on long downloads which happened to me several times.
                    allow_patterns=[
                        "*.safetensors",
                        "*.json",
                        "*.txt",
                        "tokenizer*",
                        "vocab*",
                        "merges*",
                        "spiece*",
                        "sentence_bert_config*",
                        "modules.json",
                        "1_Pooling/*",
                        "2_Normalize/*",
                    ],
                )
                return
            except HfHubHTTPError as e:
                # 401/404 means wrong repo — try the next candidate
                last_err = e
                if getattr(e.response, "status_code", None) in (401, 404):
                    break
                print(f"  ! {candidate} attempt {attempt}/{max_retries} failed: {e}")
            except Exception as e:
                last_err = e
                print(f"  ! {candidate} attempt {attempt}/{max_retries} failed: {e}")
    raise RuntimeError(
        f"Could not download HF model {repo_id!r} after retries: {last_err}"
    )


def generate_embeddings(model_name: str) -> HuggingFaceEmbeddings:
    """Generate embeddings for a given sentence-transformers model name."""
    _ensure_hf_model(model_name)
    return HuggingFaceEmbeddings(model_name=model_name)


# function to compute cosine similarity between a query embedding and document embeddings
# will use this to rank our documents based on their relevance to the query
def compute_similarity(query_result, doc_result):
    """Compute cosine similarity between query and document embeddings."""
    query_array = np.array(query_result).reshape(1, -1)
    doc_array = np.array(doc_result)
    similarity = cosine_similarity(query_array, doc_array)[0]
    return similarity

## 3s Vector Store

In [ ]:
def load_and_prepare_documents(
    arxiv_ids: list[str],
    wiki_queries: dict,
    blogs: list,
    text_splitter: RecursiveCharacterTextSplitter,
    user_agent: str | None = None,
    verbose: bool = False,
) -> list:
    """Load and split documents from Arxiv, Wikipedia, and blog sources."""
    arxiv_docs = load_arxiv_documents(arxiv_ids, text_splitter, verbose=verbose)
    wiki_docs_list = load_wiki_documents(wiki_queries, text_splitter, verbose=verbose)
    blog_docs = load_blog_documents(
        blogs,
        text_splitter,
        user_agent=user_agent,
        verbose=verbose,
    )
    return arxiv_docs + wiki_docs_list + blog_docs


def prepare_vectorstore(
    documents: list,
    embedding_model: HuggingFaceEmbeddings,
) -> QdrantVectorStore:
    """Build in-memory Qdrant vector store from document chunks and embeddings."""
    return QdrantVectorStore.from_documents(
        documents=documents,
        embedding=embedding_model,
        location=":memory:",
        collection_name="rag_tech_db",
        force_recreate=True,
    )


def load_and_prepare_vectorstore(
    arxiv_ids: list[str],
    wiki_queries: dict,
    blogs: list,
    text_splitter: RecursiveCharacterTextSplitter,
    embedding_model: HuggingFaceEmbeddings,
    user_agent: str | None = None,
    verbose: bool = False,
) -> QdrantVectorStore:
    """Load docs, split, embed, then return a vector store ready for retrieval."""
    documents = load_and_prepare_documents(
        arxiv_ids,
        wiki_queries,
        blogs,
        text_splitter,
        user_agent=user_agent,
        verbose=verbose,
    )
    return prepare_vectorstore(documents, embedding_model)

### Load the Docs

In [ ]:
# Build/load document chunks with a Colab-friendly cache flow. Originally I was using this locally and it was working well, but when I moved to Colab I ran into issues with the default Hugging Face downloader hanging on large files due to network instability. This cache flow allowed me to pre-download the necessary files and load them from disk, avoiding the network issues during the main execution of the notebook. It also provides a way to upload cached files directly in Colab if they are not found.
import pickle
from pathlib import Path as _P

# Cache helper locations for local + Colab runtimes
DOC_CACHE_SEARCH_DIRS = [
    _P("."),
    _P("/content"),
    _P("/content/drive/MyDrive"),
    _P("/content/drive/MyDrive/Assignment_5"),
    _P.home(),
]


def resolve_doc_cache(filename: str, allow_upload: bool = True):
    """Return a Path to an existing cache file, or None if not found."""
    name = _P(filename).name
    for d in DOC_CACHE_SEARCH_DIRS:
        candidate = d / name
        if candidate.exists() and candidate.stat().st_size > 0:
            return candidate
    if allow_upload and IS_COLAB:
        try:
            from google.colab import files  # type: ignore

            print(f"Cache {name!r} not found. Upload it now (cancel to rebuild):")
            uploaded = files.upload()
            for uploaded_name in uploaded:
                if uploaded_name.endswith(name) or uploaded_name == name:
                    dest = _P("/content") / uploaded_name
                    if dest.exists():
                        return dest
        except Exception as e:
            print(f"Colab upload skipped: {e}")
    return None


def save_doc_cache(filename: str, obj) -> _P:
    """Write cache to cwd and return the path."""
    dest = _P(filename).name
    with open(dest, "wb") as f:
        pickle.dump(obj, f)
    return _P(dest)


text_splitter = create_text_splitter(chunk_size=1000, chunk_overlap=200)
embeddings = generate_embeddings("all-mpnet-base-v2")

CACHE_NAME = "cached_documents.pkl"
cache_path = resolve_doc_cache(CACHE_NAME)

if cache_path is not None:
    print(f"Loading documents from cache: {cache_path}")
    with open(cache_path, "rb") as f:
        all_docs = pickle.load(f)
    print(f"Loaded {len(all_docs)} cached chunks.")
else:
    print("No cache found. Downloading and chunking documents (first run)...")
    print("\n-- Arxiv --", flush=True)
    arxiv_chunks = load_arxiv_documents(arxiv_ids, text_splitter)
    print("\n-- Wikipedia --", flush=True)
    wiki_chunks = load_wiki_documents(wiki_docs, text_splitter)
    print("\n-- Blogs --", flush=True)
    blog_chunks = load_blog_documents(blogs, text_splitter, user_agent=USER_AGENT)
    all_docs = arxiv_chunks + wiki_chunks + blog_chunks
    saved = save_doc_cache(CACHE_NAME, all_docs)
    print(f"\nCached {len(all_docs)} chunks to {saved}")

# Note: build_rag_pipeline() creates per-config embeddings/vectorstores separately.
qdrant_vectorstore = prepare_vectorstore(all_docs, embeddings)

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 11 files:   0%|          | 0/11 [00:00<?, ?it/s]

README.md: 0.00B [00:00, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Cache 'cached_documents.pkl' not found. Upload it now (cancel to rebuild):

No cache found. Downloading and chunking documents (first run)...

-- Arxiv --
  [1/32] arxiv:2005.11401
  [2/32] arxiv:2104.07567
  [3/32] arxiv:2104.09864
  [4/32] arxiv:2105.03011
  [5/32] arxiv:2106.09685
  [6/32] arxiv:2203.02155
  [7/32] arxiv:2203.15556
  [8/32] arxiv:2211.09260
  [9/32] arxiv:2211.12561
  [10/32] arxiv:2212.09741
  [11/32] arxiv:2305.14314
  [12/32] arxiv:2305.18290
  [13/32] arxiv:2306.15595
  [14/32] arxiv:2309.08872
  [15/32] arxiv:2309.15217
  [16/32] arxiv:2310.06825
  [17/32] arxiv:2310.11511
  [18/32] arxiv:2311.08377
  [19/32] arxiv:2312.05708
  [20/32] arxiv:2401.06532
  [21/32] arxiv:2401.17268
  [22/32] arxiv:2402.01306
  [23/32] arxiv:2402.19473
  [24/32] arxiv:2406.04744
  [25/32] arxiv:2312.10997
  [26/32] arxiv:2410.12812
  [27/32] arxiv:2410.15944
  [28/32] arxiv:2411.16594
  [29/32] arxiv:2404.00657
  [30/32] arxiv:2601.07711
  [31/32] arxiv:2507.09477
  [32/32] arxiv:2506.10408
Arxiv docs=32 splits=165

-- Wikipedia --
  [1/4] wiki:'Generative Artificial Intelligence'
  [2/4] wiki:'Information Retrieval'
  [3/4] wiki:'Large Language Models'
  [4/4] wiki:'Retrieval Augmented Generation'
Wiki docs=10 splits=56

-- Blogs --
  [1/7] blog:https://lilianweng.github.io/posts/2020-10-29-odqa/
  [2/7] blog:https://lilianweng.github.io/posts/2023-03-15-prompt-engineering/
  [3/7] blog:https://lilianweng.github.io/posts/2018-06-24-attention/
  [4/7] blog:https://lilianweng.github.io/posts/2023-10-25-adv-attack-llm/
  [5/7] blog:https://lilianweng.github.io/posts/2024-07-07-hallucination/
  [6/7] blog:https://huyenchip.com/2025/01/16/ai-engineering-pitfalls.html
  [7/7] blog:https://blog.langchain.com/the-rise-of-context-engineering/
Blogs docs=7 splits=300

Cached 521 chunks to cached_documents.pkl

In [ ]:
# quick test query to verify the vector store is working and returning relevant results before we integrate it into the RAG pipeline.

results = qdrant_vectorstore.similarity_search(
    "How can we train a model for preferences?",
    k=2,
)

for i, doc in enumerate(results, start=1):
    preview = doc.page_content[:350].replace("\n", " ")
    print(f"Result {i}: {preview}...")
    print(f"Metadata: {doc.metadata}\n")

Result 1: prospect theory (Tversky & Kahneman, 1992). x). This is because preferences, despite being a kind of data that is relatively scarce and expensive to collect in practice (Casper et al., 2023), are required by the alignment methods shown to work best—RLHF (Christiano et al., 2017) and DPO (Rafailov et al., 2023). To understand why these methods work ...
Metadata: {'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2024-11-20T01:59:57+00:00', 'source': 'arxiv_pdfs/2402.01306.pdf', 'file_path': 'arxiv_pdfs/2402.01306.pdf', 'total_pages': 19, 'format': 'PDF 1.5', 'title': 'KTO: Model Alignment as Prospect Theoretic Optimization', 'author': 'Kawin Ethayarajh, Winnie Xu, Niklas Muennighoff, Dan Jurafsky, Douwe Kiela', 'subject': 'Proceedings of the International Conference on Machine Learning 2024', 'keywords': 'Machine Learning, ICML', 'moddate': '2024-11-20T01:59:57+00:00', 'trapped': '', 'modDate': 'D:20241120015957Z', 'creationDate': 'D:20241120015957Z', 'page': 0, 'split_id': 106, '_id': '078b0af4a7e54e118728017eb118733e', '_collection_name': 'rag_tech_db'}

Result 2: RLHF and DPO have consistently proven to be more benefi- cial than doing supervised finetuning (SFT) alone. However, human feedback is often discussed only in the context of preferences (e.g., output yw ≻yl for input x), even though it can take many forms (e.g., approval/disapproval of y given 1Stanford University (first author was an intern at Con...
Metadata: {'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2024-11-20T01:59:57+00:00', 'source': 'arxiv_pdfs/2402.01306.pdf', 'file_path': 'arxiv_pdfs/2402.01306.pdf', 'total_pages': 19, 'format': 'PDF 1.5', 'title': 'KTO: Model Alignment as Prospect Theoretic Optimization', 'author': 'Kawin Ethayarajh, Winnie Xu, Niklas Muennighoff, Dan Jurafsky, Douwe Kiela', 'subject': 'Proceedings of the International Conference on Machine Learning 2024', 'keywords': 'Machine Learning, ICML', 'moddate': '2024-11-20T01:59:57+00:00', 'trapped': '', 'modDate': 'D:20241120015957Z', 'creationDate': 'D:20241120015957Z', 'page': 0, 'split_id': 105, '_id': 'b7dffb174e0047058956e08805697ae8', '_collection_name': 'rag_tech_db'}

Documents look ok...

## 5s Pipeline

### 5s.2 Main Pipeline Class

In [ ]:
# Shared pipeline primitives: state schema, prompt templates, output helpers.
# The compiled graph is built per-config by build_rag_pipeline() later on,
# this cell only defines the pieces shared across every build and helped me to keep the overall structure organized and consistent as I iterated on the pipeline design.


class DualPersonaState(TypedDict, total=False):
    question: str
    rewritten_question: str
    retrieved_docs: list  # langchain Document objects (post-rerank)
    retrieved_context: str  # joined string form for prompt injection
    extracted_facts: str
    source_documents: list  # metadata list for display
    research_answer: str
    marketing_answer: str
    combined_output: dict


REWRITER_PROMPT = """[INST] You are a search optimization expert. Rewrite the following user question into a detailed, keyword-rich query optimized for relevant document retrieval.
Question: {question} [/INST]
Rewritten Query:"""


READER_PROMPT = """[INST] You are a meticulous researcher. Read the following context and extract only the factual, objective information that directly answers the question.

Question: {question}

Context:
{context} [/INST]

Extracted Facts:"""


SYSTEM_PROMPT_TEMPLATE = """You are a reliable assistant for a GenAI RAG Proof of Concept. Since this Proof of Concept is supported by the VP of engineering and will be presented to the CMO, it is imperative you put your best effort in answering the questions for the two audiences (Research/Engineers and Marketing).
Ground all claims in the provided context and avoid unsupported assertions.
If context is insufficient, state uncertainty clearly. Your answers should be between 3 and 5 sentences."""


RESEARCH_PROMPT_TEMPLATE = """[INST] User: You are answering for an engineering audience.
Use the context to provide a technical answer with concrete details and correct terminology. Consider that your answer may be evaluated by experts, so be precise and comprehensive in your response.

Question: {question}

Context:
{context}
[/INST] Assistant:"""


MARKETING_PROMPT_TEMPLATE = """[INST] User: You are answering for a marketing audience.
Use the context to provide an accurate, concise, non-technical summary with clear product/value framing. Consider that your marketing team will use this answer to create customer-facing content, so focus on clarity and relevance to customer benefits.

Question: {question}

Context:
{context}
[/INST] Assistant:"""


def _llm_text(resp) -> str:
    """Strip prompt echoes and chat-wrapper tokens from the LLM response."""
    text = resp.content if hasattr(resp, "content") else str(resp)
    if isinstance(text, list):
        text = "\n".join(str(t) for t in text)
    text = str(text).strip()
    for marker in [
        "[/INST] Assistant:",
        "Assistant:",
        "<|assistant|>",
        "### Assistant:",
    ]:
        if marker in text:
            text = text.split(marker)[-1].strip()
    text = re.sub(r"</?s>", "", text)
    text = re.sub(r"<\|/?(system|user|assistant)\|>", "", text)
    return text.strip()


def merge_outputs_node(state: DualPersonaState) -> DualPersonaState:
    return {
        "combined_output": {
            "question": state["question"],
            "rewritten_question": state.get("rewritten_question", ""),
            "extracted_facts": state.get("extracted_facts", ""),
            "research_response": state.get("research_answer", ""),
            "marketing_response": state.get("marketing_answer", ""),
            "context": state.get("retrieved_context", ""),
            "sources": state.get("source_documents", []),
        }
    }

## 6 Validation

--User Personas--

**Engineering use case**: Can RAG effectively answer technical questions about GenAI concepts, internal system architecture, and implementation details by retrieving from diverse documentation sources?

**Marketing use case**: Can RAG help marketing staff quickly find accurate, approved messaging about GenAI features, competitive positioning, and technical capabilities to accelerate content production?

**Practical viability**: What are the implementation complexities, accuracy levels, and user experience considerations? Is this worth a larger investment?

Success will be measured by demonstrated accuracy compared to ground truth answers and a clear recommendation on whether to proceed with a full implementation.  If recommended, then a qualitative test will be conducted to get feedback from a small pilot group (5 engineers, 3 marketers).

### Validation and Test QA

## 4. Tests & Evaluations

Here you should evaluate your results. First, you should implement your evaluation metrics and then you should run evaluation tests. This is really your area, but key results to show are:

1) Your metric(s) of choice  
2) How your various models compare to the labeled validation data.

Make sure you look at the results for the marketing team and the research team separately.

**Note:** When determining your best configurations, you do not need to run all models against all labeled questions, as that may take some time. Just do that for a few models/configs, and test a larger set with a smaller subset. But if you use a subset you must justify why you are using that specific subset of questions.

**This is free form so you will need to create your own cells, text documentation as you need, etc.**

After you have implemented you evaluation strategy please answer the questions below in sections 4.1 and 4.2.

Please feel free to add more text and code cells as needed.

Shared Metrics for Bert and Rouge

1. Precision TP / TP + FP
2. Recall TP / TP + FN
3. F1 2(Precision * Recall / Precision + Recall)

Definition: Faithfullness - how factually consistent response is with the retrieved content?
Metric: I use BERTScore of answer vs retrieved context


Length Ratio = length of retrieived documents to length of generated responses. Is model effectively utilizing the relevant context?

In [ ]:
print("Loading BERTScore model into memory...")
#  Pre-download BERTScore model via
# _ensure_hf_model (defined in the embeddings cell) so a flaky HF connection
# resumes instead of stalling silently (this was a problem when doing repeated runs in Colab with the default BERTScore download path).
_ensure_hf_model("roberta-large")
bert_scorer = BERTScorer(lang="en", rescale_with_baseline=False)
print("BERTScore model loaded successfully!")

Loading BERTScore model into memory...

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 6 files:   0%|          | 0/6 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

RobertaModel LOAD REPORT from: roberta-large
Key                             | Status     |
--------------------------------+------------+-
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
pooler.dense.bias               | MISSING    |
pooler.dense.weight             | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

BERTScore model loaded successfully!

In [ ]:
def evaluate_rag(dataset: dict, graph, scorer=None):
    """
    Evaluate a built RAG pipeline with BERTScore, ROUGE, faithfulness, and length ratio.

    Faithfulness is computed against `extracted_facts` (what the generators
    actually received), not the raw retrieved context. This makes the metric
    a better grounding check on the generator's input.

    Returns
    -------
    all_metrics : dict  {persona: {bertscore, rouge, length_ratio, faithfulness_f1}}
    raw_rows    : list[dict]  one entry per question with gold, generated, and
                              per-question bert_f1_research / bert_f1_marketing
    """
    preds_res, refs_res = [], []
    preds_mkt, refs_mkt = [], []
    facts, item_ids, questions = [], [], []

    def _scalar(t):
        if t is None:
            return None
        if hasattr(t, "mean"):
            t = t.mean()
        if hasattr(t, "item"):
            return float(t.item())
        return float(t)

    # 1. Single inference pass
    for item_id, item in dataset.items():
        query = item.get("question", "")
        refs_res.append(item.get("gold_answer_research") or "")
        refs_mkt.append(item.get("gold_answer_marketing") or "")
        item_ids.append(item_id)
        questions.append(query)

        result = graph.invoke({"question": query})
        preds_res.append(result.get("research_answer") or "")
        preds_mkt.append(result.get("marketing_answer") or "")
        facts.append(
            result.get("extracted_facts") or result.get("retrieved_context") or ""
        )

    def _rouge_avg(preds, refs):
        r1, r2, rl = [], [], []
        for p, r in zip(preds, refs):
            s = _rouge_scorer.score(r, p)
            r1.append(s["rouge1"].fmeasure)
            r2.append(s["rouge2"].fmeasure)
            rl.append(s["rougeL"].fmeasure)
        return float(np.mean(r1)), float(np.mean(r2)), float(np.mean(rl))

    def _length_ratio(preds, refs):
        ratios = [len(p.split()) / max(len(r.split()), 1) for p, r in zip(preds, refs)]
        return float(np.mean(ratios))

    def _bert(preds, refs):
        if scorer is not None:
            return scorer.score(preds, refs)
        from bert_score import score as bscore

        return bscore(preds, refs, lang="en", verbose=False)

    # 2. BERTScore vs gold responses (per persona) and vs extracted facts (faithfulness)
    p_res, r_res, f1_res = _bert(preds_res, refs_res)
    p_mkt, r_mkt, f1_mkt = _bert(preds_mkt, refs_mkt)

    if any(f for f in facts):
        _, _, ff1_res = _bert(preds_res, facts)
        _, _, ff1_mkt = _bert(preds_mkt, facts)
    else:
        ff1_res = ff1_mkt = None

    # 3. Per-question rows
    raw_rows = []
    for i, (item_id, question) in enumerate(zip(item_ids, questions)):
        raw_rows.append(
            {
                "id": item_id,
                "question": question,
                "gold_research": refs_res[i],
                "gold_marketing": refs_mkt[i],
                "gen_research": preds_res[i],
                "gen_marketing": preds_mkt[i],
                "extracted_facts": facts[i],
                "bert_f1_research": _scalar(f1_res[i]),
                "bert_f1_marketing": _scalar(f1_mkt[i]),
                "rouge_l_research": _rouge_scorer.score(refs_res[i], preds_res[i])[
                    "rougeL"
                ].fmeasure,
                "rouge_l_marketing": _rouge_scorer.score(refs_mkt[i], preds_mkt[i])[
                    "rougeL"
                ].fmeasure,
            }
        )

    # 4. Aggregate metrics
    all_metrics = {}
    for persona, preds, refs, p_t, r_t, f1_t, ff1_t in [
        ("Research", preds_res, refs_res, p_res, r_res, f1_res, ff1_res),
        ("Marketing", preds_mkt, refs_mkt, p_mkt, r_mkt, f1_mkt, ff1_mkt),
    ]:
        r1, r2, rl = _rouge_avg(preds, refs)
        all_metrics[persona] = {
            "bertscore": (_scalar(p_t), _scalar(r_t), _scalar(f1_t)),
            "rouge": (r1, r2, rl),
            "length_ratio": _length_ratio(preds, refs),
            "faithfulness_f1": _scalar(ff1_t),
        }

    return all_metrics, raw_rows

In [21]:
def run_test_qa(test_dataset: dict, graph):
    """
    Run inference on a test QA dataset (without gold answers).
    Pass a graph from build_rag_pipeline to test any config-specific pipeline.
    """
    test_results = {}
    for item_id, item in test_dataset.items():
        query = item.get("question", "")
        print(f"Running Test Question {item_id}:\n{query}")

        result = graph.invoke({"question": query})
        test_results[item_id] = {
            "question": query,
            "research_answer": result.get("research_answer") or "",
            "marketing_answer": result.get("marketing_answer") or "",
        }

    return test_results


# Example usage:
# graph, _ = build_rag_pipeline(OPTIMIZED_CONFIG)
# test_generations = run_test_qa(test_questions, graph=graph)

In [ ]:
import pandas as pd
from IPython.display import display, HTML


def _metrics_html(all_metrics: dict) -> str:
    """Render aggregate metrics as a compact HTML table."""
    rows = []
    for persona in ["Research", "Marketing"]:
        m = all_metrics[persona]
        bp, br, bf1 = m["bertscore"]
        r1, r2, rl = m["rouge"]
        faith = m["faithfulness_f1"]
        rows.append(
            {
                "Persona": persona,
                "BERT-P": f"{bp:.4f}",
                "BERT-R": f"{br:.4f}",
                "BERT-F1": f"{bf1:.4f}",
                "ROUGE-1": f"{r1:.4f}",
                "ROUGE-2": f"{r2:.4f}",
                "ROUGE-L": f"{rl:.4f}",
                "Faithfulness-F1": f"{faith:.4f}" if faith is not None else "N/A",
                "Len-Ratio": f"{m['length_ratio']:.2f}",
            }
        )
    return pd.DataFrame(rows).set_index("Persona").to_html()


def display_comparison(all_metrics: dict, raw_rows: list, max_chars: int = 400) -> None:
    """
    Display aggregate metric table followed by a per-question
    gold-vs-generated comparison with per-question BERT-F1 / ROUGE-L scores.
    """
    print("\n" + "=" * 72)
    print("AGGREGATE METRICS")
    print("=" * 72)
    display(HTML(_metrics_html(all_metrics)))

    def _trim(text: str) -> str:
        text = (text or "").strip()
        return text if len(text) <= max_chars else text[:max_chars] + " …"

    for row in raw_rows:
        print("\n" + "─" * 72)
        print(
            f"Q-ID {row['id']}  |  BERT-F1  research={row['bert_f1_research']:.4f}"
            f"  marketing={row['bert_f1_marketing']:.4f}"
            f"  |  ROUGE-L  research={row['rouge_l_research']:.4f}"
            f"  marketing={row['rouge_l_marketing']:.4f}"
        )
        print(f"\nQUESTION: {row['question']}")

        print("\n── RESEARCH ─────────────────────────────")
        print(f"  GOLD:      {_trim(row['gold_research'])}")
        print(f"  GENERATED: {_trim(row['gen_research'])}")

        print("\n── MARKETING ────────────────────────────")
        print(f"  GOLD:      {_trim(row['gold_marketing'])}")
        print(f"  GENERATED: {_trim(row['gen_marketing'])}")

    print("\n" + "=" * 72)

### 4.1. Metrics

Now we'd like to hear about your approach to evaluation.

**QUESTION:**

4.1. In 8 to 15 sentences, please define and defend your approach to evaluating your RAG model. Please fill in your answer in the text block below:

*Your 4.1 answer in this text box here.  Double click to open.*

In [23]:
### Q4-1 Grading Tag: Don't edit this line.

"""Since we have 'reference' answers to the questions, I decided to use traditional NLP evaluation metrics as was posited in our Week 9 lecture. I chose BERTScore as the primary evaluation metric, as it a well know evaulation metric and gives a token-level cosine similarity between contextual embeddings and then uses greedy mathching to align tokens. I also included another traditional word match metric, ROUGE score, to evaluate the n-gram overlap between the human response and the generated one. So having both BERT for semantic similarity and ROUGE for surface overlap gives as a more holistic eval. Additionally, I added a good ole fashioned length ratio to compare the length of generated answers to reference answers. Although this is far from scientific, it does help give an idea of if the model is being overly concise or verbose, which I can then adjust in the Prompts. Finally, I included a faithfulness metric similar to the RAGAS idea by comparing the generated answers to the retrieved context using BERTScore. My intuition was that this would act as second stage assessment to assess how well the model is grounding its responses in the retrieved context bundle after the answer itself was evaluated. Compared to the prior metrics, this gives us grounding in context vs. correctness against references which is an important point to cover.

A final reason I chose this combination of evaluation metrics as opposed to something like LLM as Judge or a manually defined set of eval Q&As I would create is that we were provided an already well structured Validation and Test set of Golden Responses which lends itself well to the more programmatic metrics I used."""

### ENTER NOTHING HERE. THIS IS A PLACE HOLDER

"Since we have 'reference' answers to the questions, I decided to use traditional NLP evaluation metrics as was posited in our Week 9 lecture. I chose BERTScore as the primary evaluation metric, as it a well know evaulation metric and gives a token-level cosine similarity between contextual embeddings and then uses greedy mathching to align tokens. I also included another traditional word match metric, ROUGE score, to evaluate the n-gram overlap between the human response and the generated one. So having both BERT for semantic similarity and ROUGE for surface overlap gives as a more holistic eval. Additionally, I added a good ole fashioned length ratio to compare the length of generated answers to reference answers. Although this is far from scientific, it does help give an idea of if the model is being overly concise or verbose, which I can then adjust in the Prompts. Finally, I included a faithfulness metric similar to the RAGAS idea by comparing the generated answers to the retrieved context using BERTScore. My intuition was that this would act as second stage assessment to assess how well the model is grounding its responses in the retrieved context bundle after the answer itself was evaluated. Compared to the prior metrics, this gives us grounding in context vs. correctness against references which is an important point to cover.\n\nA final reason I chose this combination of evaluation metrics as opposed to something like LLM as Judge or a manually defined set of eval Q&As I would create is that we were provided an already well structured Validation and Test set of Golden Responses which lends itself well to the more programmatic metrics I used."

### 4.2. Evaluation Comparisons

Document your key runs here. Feel free to add more text and code cells as needed.  Include at least one full run on all 75 validation examples for your best models/model configuration.

In [24]:
import hashlib
from dataclasses import dataclass, field, replace


DEFAULT_PROMPTS = {
    "rewriter": REWRITER_PROMPT,
    "reader": READER_PROMPT,
    "system": SYSTEM_PROMPT_TEMPLATE,
    "research": RESEARCH_PROMPT_TEMPLATE,
    "marketing": MARKETING_PROMPT_TEMPLATE,
}


@dataclass
class RAGConfig:
    """Core tunable settings for the RAG pipeline."""

    # Identity
    name: str = "default"

    # Embedding + chunking
    embedding_model: str = "all-mpnet-base-v2"
    chunk_size: int = 1000
    chunk_overlap: int = 200

    # LLM + quantization
    llm_provider: str = "huggingface"  # "huggingface" or "cohere"
    llm_model: str = "mistralai/Mistral-7B-Instruct-v0.3"
    cohere_model: str = "command-a-03-2025"
    load_in_4bit: bool = True
    load_in_8bit: bool = False
    bnb_4bit_quant_type: str = "nf4"
    bnb_4bit_use_double_quant: bool = True
    bnb_4bit_compute_dtype: str = "bfloat16"

    # Generation
    max_new_tokens: int = 384
    temperature: float = 0.1
    top_p: float = 0.95
    do_sample: bool = True
    repetition_penalty: float | None = None

    # Retrieval
    retriever_k: int = 5
    reranker_model: str = "BAAI/bge-reranker-v2-m3"
    reranker_top_n: int = 3
    use_rewriter: bool = True
    use_reranker: bool = True

    # Prompt tweaks
    prompt_overrides: dict[str, str] = field(default_factory=dict)

    # Data
    arxiv_ids: list = field(default_factory=lambda: arxiv_ids)
    wiki_queries: dict = field(default_factory=lambda: wiki_docs)
    blogs: list = field(default_factory=lambda: blogs)

    # Cache
    save_doc_cache: bool = True
    cache_prefix: str = "cached_docs"

    @property
    def cache_key(self) -> str:
        key_parts = (
            tuple(self.arxiv_ids),
            tuple(sorted(self.wiki_queries.items())),
            tuple(self.blogs),
            self.chunk_size,
            self.chunk_overlap,
        )
        key_hash = hashlib.md5(str(key_parts).encode()).hexdigest()[:10]
        return f"{self.cache_prefix}_{self.name}_{key_hash}.pkl"

    @property
    def compute_dtype(self):
        return (
            torch.bfloat16
            if self.bnb_4bit_compute_dtype == "bfloat16"
            else torch.float16
        )

    def validate(self):
        if self.llm_provider not in {"huggingface", "cohere"}:
            raise ValueError("llm_provider must be 'huggingface' or 'cohere'.")
        if self.load_in_4bit and self.load_in_8bit:
            raise ValueError("Only one quantization mode can be active at a time.")
        if self.reranker_top_n > self.retriever_k:
            raise ValueError("reranker_top_n cannot exceed retriever_k.")

    def resolved_prompts(self) -> dict[str, str]:
        prompts = dict(DEFAULT_PROMPTS)
        prompts.update(self.prompt_overrides)
        return prompts

    def with_updates(self, **kwargs):
        cfg = replace(self, **kwargs)
        if "prompt_overrides" in kwargs and kwargs["prompt_overrides"] is not None:
            cfg.prompt_overrides = dict(kwargs["prompt_overrides"])
        return cfg

    def summary(self) -> str:
        if self.llm_provider == "cohere":
            quant = "api"
            llm_label = self.cohere_model
        else:
            quant = (
                "4bit"
                if self.load_in_4bit
                else ("8bit" if self.load_in_8bit else "none")
            )
            llm_label = self.llm_model.split("/")[-1]
        return (
            f"{self.name}: embed={self.embedding_model}, "
            f"chunk={self.chunk_size}/{self.chunk_overlap}, "
            f"llm={self.llm_provider}:{llm_label}, "
            f"quant={quant}, temp={self.temperature}, "
            f"max_tok={self.max_new_tokens}, rewriter={self.use_rewriter}, "
            f"reranker={self.use_reranker}, k={self.retriever_k}"
        )

    def __repr__(self):
        return self.summary()


def make_config(name: str, base: RAGConfig | None = None, **overrides) -> RAGConfig:
    base_cfg = base if base is not None else RAGConfig()
    cfg = base_cfg.with_updates(name=name, **overrides)
    cfg.validate()
    return cfg

In [25]:
# ---- Predefined Configurations ----

OPTIMIZED_CONFIG = make_config(
    "optimized",
    embedding_model="all-mpnet-base-v2",
    chunk_size=1000,
    chunk_overlap=200,
    load_in_4bit=True,
    max_new_tokens=384,
    temperature=0.1,
    repetition_penalty=None,
    use_rewriter=True,
    use_reranker=True,
)

BASELINE_CONFIG = make_config(
    "baseline",
    embedding_model="multi-qa-mpnet-base-dot-v1",
    chunk_size=128,
    chunk_overlap=0,
    load_in_4bit=True,
    max_new_tokens=384,
    temperature=0.6,
    repetition_penalty=1.2,
    use_rewriter=False,
    use_reranker=False,
)

# Optional API-based Cohere variant
COHERE_CONFIG = make_config(
    "cohere_command_a",
    base=OPTIMIZED_CONFIG,
    llm_provider="cohere",
    cohere_model="command-a-03-2025",
    load_in_4bit=False,
    load_in_8bit=False,
)

# Manual ablation variants
NO_REWRITER_CONFIG = make_config(
    "no_rewriter", base=OPTIMIZED_CONFIG, use_rewriter=False
)
NO_RERANKER_CONFIG = make_config(
    "no_reranker", base=OPTIMIZED_CONFIG, use_reranker=False
)
SMALL_CHUNK_CONFIG = make_config(
    "chunk_512", base=OPTIMIZED_CONFIG, chunk_size=512, chunk_overlap=100
)
LARGE_CHUNK_CONFIG = make_config(
    "chunk_1500", base=OPTIMIZED_CONFIG, chunk_size=1500, chunk_overlap=300
)

# Embedding model variants
DISTIL_ROBERTA_CONFIG = make_config(
    "distil_roberta",
    base=OPTIMIZED_CONFIG,
    embedding_model="all-distilroberta-v1",
)

MINI_LM_CONFIG = make_config(
    "mini_lm",
    base=OPTIMIZED_CONFIG,
    embedding_model="all-MiniLM-L6-v2",
)

# Prompt variant via direct override (minimal, no prompt library switching)
CONCISE_PROMPT_CONFIG = make_config(
    "concise_prompt",
    base=OPTIMIZED_CONFIG,
    prompt_overrides={
        "research": RESEARCH_PROMPT_TEMPLATE
        + "\nKeep response concise and evidence-grounded, under 120 words.",
        "marketing": MARKETING_PROMPT_TEMPLATE
        + "\nKeep response concise, skimmable, and under 80 words.",
    },
)

# 8-bit quantization variant
EIGHT_BIT_CONFIG = make_config(
    "8bit_quant",
    base=OPTIMIZED_CONFIG,
    load_in_4bit=False,
    load_in_8bit=True,
)

# Main list for quick comparison
EXPERIMENT_CONFIGS = [
    OPTIMIZED_CONFIG,
    BASELINE_CONFIG,
    NO_REWRITER_CONFIG,
    NO_RERANKER_CONFIG,
    SMALL_CHUNK_CONFIG,
    LARGE_CHUNK_CONFIG,
    CONCISE_PROMPT_CONFIG,
    DISTIL_ROBERTA_CONFIG,
    MINI_LM_CONFIG,
    EIGHT_BIT_CONFIG,
]

print("Configs defined:")
for cfg in EXPERIMENT_CONFIGS:
    print(f"  {cfg.summary()}")
print(f"  {COHERE_CONFIG.summary()} (optional)")

Configs defined:
  optimized: embed=all-mpnet-base-v2, chunk=1000/200, llm=huggingface:Mistral-7B-Instruct-v0.3, quant=4bit, temp=0.1, max_tok=384, rewriter=True, reranker=True, k=5
  baseline: embed=multi-qa-mpnet-base-dot-v1, chunk=128/0, llm=huggingface:Mistral-7B-Instruct-v0.3, quant=4bit, temp=0.6, max_tok=384, rewriter=False, reranker=False, k=5
  no_rewriter: embed=all-mpnet-base-v2, chunk=1000/200, llm=huggingface:Mistral-7B-Instruct-v0.3, quant=4bit, temp=0.1, max_tok=384, rewriter=False, reranker=True, k=5
  no_reranker: embed=all-mpnet-base-v2, chunk=1000/200, llm=huggingface:Mistral-7B-Instruct-v0.3, quant=4bit, temp=0.1, max_tok=384, rewriter=True, reranker=False, k=5
  chunk_512: embed=all-mpnet-base-v2, chunk=512/100, llm=huggingface:Mistral-7B-Instruct-v0.3, quant=4bit, temp=0.1, max_tok=384, rewriter=True, reranker=True, k=5
  chunk_1500: embed=all-mpnet-base-v2, chunk=1500/300, llm=huggingface:Mistral-7B-Instruct-v0.3, quant=4bit, temp=0.1, max_tok=384, rewriter=True, reranker=True, k=5
  concise_prompt: embed=all-mpnet-base-v2, chunk=1000/200, llm=huggingface:Mistral-7B-Instruct-v0.3, quant=4bit, temp=0.1, max_tok=384, rewriter=True, reranker=True, k=5
  distil_roberta: embed=all-distilroberta-v1, chunk=1000/200, llm=huggingface:Mistral-7B-Instruct-v0.3, quant=4bit, temp=0.1, max_tok=384, rewriter=True, reranker=True, k=5
  mini_lm: embed=all-MiniLM-L6-v2, chunk=1000/200, llm=huggingface:Mistral-7B-Instruct-v0.3, quant=4bit, temp=0.1, max_tok=384, rewriter=True, reranker=True, k=5
  8bit_quant: embed=all-mpnet-base-v2, chunk=1000/200, llm=huggingface:Mistral-7B-Instruct-v0.3, quant=8bit, temp=0.1, max_tok=384, rewriter=True, reranker=True, k=5
  cohere_command_a: embed=all-mpnet-base-v2, chunk=1000/200, llm=cohere:command-a-03-2025, quant=api, temp=0.1, max_tok=384, rewriter=True, reranker=True, k=5 (optional)

In [ ]:
# ---- Cohere API Rate Limiting Wrapper ----
# Given my runs were taking SO long, getting a failure after 20 requests and losing progress was a real pain. This wrapper was my solution to that problem, allowing me to run the notebook end-to-end with the Cohere API without hitting silent stalls or losing progress due to rate limit errors. It implements a process-wide sliding window limiter to stay under the 20 req/min cap, and also includes an exponential backoff retry strategy if a 429 error does slip through.

# Rate-limited Cohere wrapper for the trial-key 20 req/min cap.
# Wraps ChatCohere with:
#   1. A process-wide sliding-window limiter (default 18 req/60s, leaves headroom)
#   2. Retry-with-backoff on TooManyRequestsError (429)
import threading
import time as _time
from collections import deque

try:
    from cohere.errors import TooManyRequestsError as _CohereRateLimit
except Exception:  # pragma: no cover - fallback if module path changes
    _CohereRateLimit = Exception


class _CohereRateLimiter:
    """Sliding-window limiter shared across every RateLimitedChatCohere instance."""

    def __init__(self, max_calls: int = 18, window_seconds: float = 60.0):
        self.max_calls = max_calls
        self.window = window_seconds
        self._calls: deque[float] = deque()
        self._lock = threading.Lock()

    def acquire(self) -> None:
        while True:
            with self._lock:
                now = _time.monotonic()
                while self._calls and now - self._calls[0] >= self.window:
                    self._calls.popleft()
                if len(self._calls) < self.max_calls:
                    self._calls.append(now)
                    return
                wait = self.window - (now - self._calls[0]) + 0.05
            print(f"  [cohere-limiter] sleeping {wait:.1f}s to respect rate limit")
            _time.sleep(max(wait, 0.1))


COHERE_LIMITER = _CohereRateLimiter(max_calls=18, window_seconds=60.0)


class RateLimitedChatCohere(ChatCohere):
    """ChatCohere subclass that throttles + retries the generate path."""

    def _generate(self, *args, **kwargs):
        max_attempts = 6
        for attempt in range(max_attempts):
            COHERE_LIMITER.acquire()
            try:
                return super()._generate(*args, **kwargs)
            except _CohereRateLimit as e:
                if attempt == max_attempts - 1:
                    raise
                backoff = min(60.0, 2**attempt + 1.0)
                print(
                    f"  [cohere-limiter] 429 on attempt {attempt + 1}; "
                    f"sleeping {backoff:.1f}s before retry"
                )
                _time.sleep(backoff)
        raise RuntimeError("RateLimitedChatCohere: exhausted retries")

###  Main "factory" function to build a RAG pipeline from a RAGConfig. This is where all the pieces come together: document loading (with cache), vectorstore prep, LLM loading (with quantization), optional reranker setup, and then graph compilation. The function returns both the compiled graph and a dict of the internal components for easy inspection and debugging.

In [ ]:
def build_rag_pipeline(config: RAGConfig):
    """
    Factory that builds a complete RAG pipeline from a RAGConfig.
    Returns (compiled_graph, components_dict) to easily inspect internals.
    """
    import pickle

    config.validate()
    prompts = config.resolved_prompts()

    print(f"Building pipeline: {config.summary()}")
    print("-" * 60)

    # 1. Embeddings & chunking
    print("  [1/6] Creating embeddings & text splitter...")
    cfg_embeddings = generate_embeddings(config.embedding_model)
    cfg_splitter = create_text_splitter(config.chunk_size, config.chunk_overlap)

    # 2. Documents (cached)
    print("  [2/6] Loading documents...")
    cache_name = config.cache_key
    cfg_docs = None
    cache_resolver = globals().get("resolve_doc_cache")
    cache_saver = globals().get("save_doc_cache")

    if config.save_doc_cache and callable(cache_resolver):
        found = cache_resolver(cache_name, allow_upload=False)
        if found is not None:
            with open(str(found), "rb") as f:
                cfg_docs = pickle.load(f)
            print(f"         Loaded {len(cfg_docs)} chunks from {found}.")

    if cfg_docs is None:
        cfg_docs = load_and_prepare_documents(
            config.arxiv_ids,
            config.wiki_queries,
            config.blogs,
            cfg_splitter,
            user_agent=USER_AGENT,
            verbose=True,
        )
        if config.save_doc_cache and callable(cache_saver):
            saved = cache_saver(cache_name, cfg_docs)
            print(f"         Cached {len(cfg_docs)} chunks to {saved}")

    # 3. Vectorstore
    print("  [3/6] Building vectorstore...")
    cfg_vectorstore = prepare_vectorstore(cfg_docs, cfg_embeddings)

    # 4. LLM
    print("  [4/6] Loading LLM...")
    cfg_model = None

    if config.llm_provider == "huggingface":
        if torch.cuda.is_available():
            if config.load_in_4bit:
                qconfig = BitsAndBytesConfig(
                    load_in_4bit=True,
                    bnb_4bit_quant_type=config.bnb_4bit_quant_type,
                    bnb_4bit_use_double_quant=config.bnb_4bit_use_double_quant,
                    bnb_4bit_compute_dtype=config.compute_dtype,
                )
            elif config.load_in_8bit:
                qconfig = BitsAndBytesConfig(load_in_8bit=True)
            else:
                qconfig = None
        else:
            qconfig = None

        _ensure_hf_model(config.llm_model)
        cfg_model = AutoModelForCausalLM.from_pretrained(
            config.llm_model,
            device_map="auto",
            dtype=config.compute_dtype,
            quantization_config=qconfig,
        )
        cfg_tokenizer = AutoTokenizer.from_pretrained(config.llm_model)

        if cfg_tokenizer.pad_token_id is None:
            cfg_tokenizer.pad_token = cfg_tokenizer.eos_token
        cfg_model.config.pad_token_id = cfg_tokenizer.pad_token_id

        cfg_generation_config = GenerationConfig.from_model_config(cfg_model.config)
        cfg_generation_config.max_new_tokens = config.max_new_tokens
        cfg_generation_config.temperature = config.temperature
        cfg_generation_config.top_p = config.top_p
        cfg_generation_config.do_sample = config.do_sample
        cfg_generation_config.pad_token_id = cfg_tokenizer.pad_token_id
        cfg_generation_config.eos_token_id = cfg_tokenizer.eos_token_id
        if config.repetition_penalty is not None:
            cfg_generation_config.repetition_penalty = config.repetition_penalty

        cfg_pipe = pipeline(
            task="text-generation",
            model=cfg_model,
            tokenizer=cfg_tokenizer,
            dtype="auto",
        )
        cfg_llm = HuggingFacePipeline(
            pipeline=cfg_pipe,
            pipeline_kwargs={
                "generation_config": cfg_generation_config,
                "return_full_text": False,
            },
        )
        mem_gb = round(cfg_model.get_memory_footprint() / (1024**3), 4)
        print(f"         Model memory: {mem_gb} GB")

    else:
        if not COHERE_API_KEY:
            raise ValueError(
                "COHERE_API_KEY is not set. Add it to your environment before running Cohere configs."
            )
        cfg_llm = RateLimitedChatCohere(
            model=config.cohere_model,
            cohere_api_key=COHERE_API_KEY,
            temperature=config.temperature,
            max_tokens=config.max_new_tokens,
        )
        print(f"         Cohere model: {config.cohere_model}")

    # 5. Reranker
    cfg_compressor = None
    if config.use_reranker:
        print("  [5/6] Setting up reranker...")
        _ensure_hf_model(config.reranker_model)
        cfg_reranker_model = HuggingFaceCrossEncoder(model_name=config.reranker_model)
        cfg_compressor = CrossEncoderReranker(
            model=cfg_reranker_model, top_n=config.reranker_top_n
        )
    else:
        print("  [5/6] Skipping reranker (use_reranker=False)...")

    # 6. Build graph
    print("  [6/6] Compiling graph...")

    def _join(docs):
        return "\n\n".join(d.page_content for d in docs)

    def _rewrite(state):
        prompt = prompts["rewriter"].format(question=state["question"])
        return {"rewritten_question": _llm_text(cfg_llm.invoke(prompt)).strip()}

    def _retrieve(state):
        retriever = cfg_vectorstore.as_retriever(
            search_kwargs={"k": config.retriever_k}
        )
        query = state.get("rewritten_question", state["question"])
        docs = retriever.invoke(query)
        return {
            "retrieved_docs": docs,
            "retrieved_context": _join(docs),
            "source_documents": [d.metadata for d in docs],
        }

    def _rerank(state):
        docs = state.get("retrieved_docs", [])
        if not docs or cfg_compressor is None:
            return {}
        reranked = list(
            cfg_compressor.compress_documents(docs, query=state["question"])
        )
        return {
            "retrieved_docs": reranked,
            "retrieved_context": _join(reranked),
            "source_documents": [d.metadata for d in reranked],
        }

    def _reader(state):
        prompt = prompts["reader"].format(
            question=state["question"], context=state.get("retrieved_context", "")
        )
        return {"extracted_facts": _llm_text(cfg_llm.invoke(prompt)).strip()}

    def _research(state):
        prompt = f"{prompts['system']}\n\n" + prompts["research"].format(
            question=state["question"], context=state.get("extracted_facts", "")
        )
        return {"research_answer": _llm_text(cfg_llm.invoke(prompt)).strip()}

    def _marketing(state):
        prompt = f"{prompts['system']}\n\n" + prompts["marketing"].format(
            question=state["question"], context=state.get("extracted_facts", "")
        )
        return {"marketing_answer": _llm_text(cfg_llm.invoke(prompt)).strip()}

    b = StateGraph(DualPersonaState)
    b.add_node("retrieve_context", _retrieve)
    b.add_node("reader", _reader)
    b.add_node("research", _research)
    b.add_node("marketing", _marketing)
    b.add_node("merge_outputs", merge_outputs_node)

    if config.use_rewriter:
        b.add_node("rewrite", _rewrite)
        b.add_edge(START, "rewrite")
        b.add_edge("rewrite", "retrieve_context")
    else:
        b.add_edge(START, "retrieve_context")

    if config.use_reranker:
        b.add_node("rerank_context", _rerank)
        b.add_edge("retrieve_context", "rerank_context")
        b.add_edge("rerank_context", "reader")
    else:
        b.add_edge("retrieve_context", "reader")

    b.add_edge("reader", "research")
    b.add_edge("reader", "marketing")
    b.add_edge("research", "merge_outputs")
    b.add_edge("marketing", "merge_outputs")
    b.add_edge("merge_outputs", END)

    compiled = b.compile()

    components = {
        "config": config,
        "prompts": prompts,
        "vectorstore": cfg_vectorstore,
        "llm": cfg_llm,
        "model": cfg_model,
        "compressor": cfg_compressor,
        "graph": compiled,
    }
    print(f'Pipeline "{config.name}" ready.\n')
    return compiled, components

### Main EVAL

In [ ]:
def run_full_evaluation(
    configs: list[RAGConfig],
    dataset: dict = None,
    scorer=None,
    verbose: bool = True,
) -> dict:
    """Build and evaluate one or more pipeline configs."""
    if dataset is None:
        dataset = validation_questions_answers
    if scorer is None:
        scorer = bert_scorer

    all_results = {}

    for config in configs:
        if verbose:
            print("\n" + "#" * 70)
            print(f"# EVALUATING: {config.summary()}")
            print("#" * 70)

        graph, components = build_rag_pipeline(config)

        t0 = time.time()
        metrics, raw_rows = evaluate_rag(dataset, scorer=scorer, graph=graph)
        elapsed = time.time() - t0
        n = max(len(dataset), 1)

        if verbose:
            print(
                f"\nTotal eval time: {elapsed:.1f}s ({n} questions, {elapsed / n:.1f}s/question)"
            )

        all_results[config.name] = {
            "metrics": metrics,
            "rows": raw_rows,
            "time": elapsed,
            "config": config,
        }

        # Free GPU memory between configs
        components.pop("model", None)
        components.pop("llm", None)
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    if len(configs) > 1 and verbose:
        print("\n\n" + "=" * 80)
        print("COMPARISON SUMMARY")
        print("=" * 80)
        header = f"{'Config':<24} {'Persona':<12} {'BERT-F1':>9} {'ROUGE-L':>9} {'Faith':>9} {'Len-R':>7} {'Time':>8}"
        print(header)
        print("-" * len(header))
        for config_name, res in all_results.items():
            t = f"{res['time']:.1f}s"
            for persona in ["Research", "Marketing"]:
                m = res["metrics"][persona]
                bf1 = f"{m['bertscore'][2]:.4f}"
                rl = f"{m['rouge'][2]:.4f}"
                faith = (
                    f"{m['faithfulness_f1']:.4f}"
                    if m["faithfulness_f1"] is not None
                    else "N/A"
                )
                lr = f"{m['length_ratio']:.2f}"
                print(
                    f"{config_name:<24} {persona:<12} {bf1:>9} {rl:>9} {faith:>9} {lr:>7} {t:>8}"
                )
                t = ""

    return all_results


def results_to_dataframe(all_results: dict, include_text: bool = False):
    """
    Convert evaluation results into a tidy DataFrame.

    Parameters
    ----------
    include_text : bool
        If True, add columns for each question's generated research/marketing
        answers alongside their per-question BERT-F1 and ROUGE-L scores.
    """
    # ── aggregate rows ────────────────────────────────────────────────────
    agg_rows = []
    for config_name, res in all_results.items():
        elapsed = res["time"]
        for persona, m in res["metrics"].items():
            agg_rows.append(
                {
                    "config": config_name,
                    "persona": persona,
                    "bertscore_f1": round(m["bertscore"][2], 4),
                    "rouge_l": round(m["rouge"][2], 4),
                    "faithfulness_f1": round(m["faithfulness_f1"], 4)
                    if m["faithfulness_f1"] is not None
                    else None,
                    "length_ratio": round(m["length_ratio"], 2),
                    "eval_time_sec": round(elapsed, 1),
                }
            )

    df_agg = pd.DataFrame(agg_rows).sort_values(
        by=["persona", "bertscore_f1", "rouge_l"], ascending=[True, False, False]
    )

    if not include_text:
        return df_agg

    # ── per-question text rows ────────────────────────────────────────────
    text_rows = []
    for config_name, res in all_results.items():
        for row in res.get("rows", []):
            text_rows.append(
                {
                    "config": config_name,
                    "q_id": row["id"],
                    "question": row["question"],
                    "gold_research": row["gold_research"],
                    "gen_research": row["gen_research"],
                    "bert_f1_research": round(row["bert_f1_research"], 4),
                    "rouge_l_research": round(row["rouge_l_research"], 4),
                    "gold_marketing": row["gold_marketing"],
                    "gen_marketing": row["gen_marketing"],
                    "bert_f1_marketing": round(row["bert_f1_marketing"], 4),
                    "rouge_l_marketing": round(row["rouge_l_marketing"], 4),
                }
            )

    df_text = pd.DataFrame(text_rows)

    pd.set_option("display.max_colwidth", 300)
    return df_agg, df_text

#### Run Evaluation Comparisons

Each config builds its own pipeline from scratch, so they can be run independently.

In [ ]:
# --- Quick validation subset ---
eval_subset = {
    0: validation_questions_answers[0],
    4: validation_questions_answers[4],
    126: validation_questions_answers[126],
    193: validation_questions_answers[193],
}

# --- Basic comparison: baseline vs optimized ---
# results = run_full_evaluation([BASELINE_CONFIG, OPTIMIZED_CONFIG], dataset=eval_subset)
# display(results_to_dataframe(results))

# --- Retrieval/Chunking ablations (manual list) ---
# compare_configs = [
#     OPTIMIZED_CONFIG,
#     NO_REWRITER_CONFIG,
#     NO_RERANKER_CONFIG,
#     SMALL_CHUNK_CONFIG,
#     LARGE_CHUNK_CONFIG,
# ]
# results = run_full_evaluation(compare_configs, dataset=eval_subset)
# display(results_to_dataframe(results))


# --- Run everything in EXPERIMENT_CONFIGS ---
# results = run_full_evaluation(EXPERIMENT_CONFIGS, dataset=eval_subset)
# display(results_to_dataframe(results))

In [ ]:
# --- Mistral vs Cohere (same retrieval setup, different generator) ---
# cohere_compare = [OPTIMIZED_CONFIG, COHERE_CONFIG]
# results = run_full_evaluation(cohere_compare, dataset=eval_subset)
# display(results_to_dataframe(results))

================================================================================
COMPARISON SUMMARY
================================================================================
Config                   Persona        BERT-F1   ROUGE-L     Faith   Len-R     Time
------------------------------------------------------------------------------------
optimized                Research        0.8413    0.1599    0.8214    1.16   250.6s
optimized                Marketing       0.8523    0.2123    0.8754    4.25         
cohere_command_a         Research        0.8723    0.2915    0.8977    1.48    76.7s
cohere_command_a         Marketing       0.8622    0.1956    0.8748    2.57

In [ ]:
# Full experimental evalacross EXPERIMENT_CONFIGS — DO NOT RE-RUN.
# Results from this run are saved to CSV. The sweep took me ~40 min on a Colab GPU
# and the winning baseline informed the finalists below.
# results = run_full_evaluation(EXPERIMENT_CONFIGS, dataset=eval_subset)
# display(results_to_dataframe(results))

Full EVAL 


| Config | Persona | BERT-F1 | ROUGE-L | Faith | Len-R | Time |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| optimized | Research | 0.8306 | 0.1522 | 0.8386 | 2.13 | 267.6s |
| optimized | Marketing | 0.8685 | 0.2317 | 0.8434 | 2.90 | |
| baseline | Research | 0.8663 | 0.2967 | 0.8784 | 1.13 | 131.6s |
| baseline | Marketing | 0.8621 | 0.2267 | 0.8744 | 3.66 | |
| no_rewriter | Research | 0.8313 | 0.1885 | 0.8529 | 1.68 | 185.0s |
| no_rewriter | Marketing | 0.8743 | 0.2418 | 0.8358 | 2.59 | |
| no_reranker | Research | 0.8565 | 0.2471 | 0.8408 | 2.10 | 233.4s |
| no_reranker | Marketing | 0.8624 | 0.2029 | 0.8278 | 2.94 | |
| chunk_512 | Research | 0.8486 | 0.1832 | 0.8334 | 0.69 | 199.4s |
| chunk_512 | Marketing | 0.8465 | 0.1913 | 0.8742 | 2.96 | |
| chunk_1500 | Research | 0.8453 | 0.2337 | 0.8477 | 1.63 | 265.1s |
| chunk_1500 | Marketing | 0.8615 | 0.2592 | 0.8401 | 2.96 | |
| concise_prompt | Research | 0.8669 | 0.2902 | 0.8439 | 1.18 | 184.1s |
| concise_prompt | Marketing | 0.8639 | 0.2265 | 0.8296 | 2.23 | |
| distil_roberta | Research | 0.8474 | 0.2124 | 0.8675 | 1.30 | 214.2s |
| distil_roberta | Marketing | 0.8595 | 0.1915 | 0.8435 | 2.84 | |
| mini_lm | Research | 0.8317 | 0.1551 | 0.8516 | 1.77 | 237.9s |
| mini_lm | Marketing | 0.8653 | 0.2267 | 0.8394 | 2.62 | |
| engineered_prompts | Research | 0.8515 | 0.2817 | 0.8825 | 1.89 | 334.2s |
| engineered_prompts | Marketing | 0.8394 | 0.1740 | 0.8814 | 6.06 | |
| 8bit_quant | Research | 0.8386 | 0.1503 | 0.8284 | 1.19 | 512.3s |
| 8bit_quant | Marketing | 0.8798 | 0.2624 | 0.8355 | 2.50 | |

Experimental Winner == Baseline Model.

  - Research: best BERT-F1 (0.8663) and ROUGE-L (0.2967) of different configs
  - Faithfulness: highest on both personas (0.8784 / 0.8744)
  - Speed: fastest at 131.6s — roughly 2× anything else of the Mistral Models
  - Length ratio: closest to 1.0 on research (1.13); marketing runs long (3.66) but that's consistent across configs

## Finalists

In [ ]:
# As a final test, I will incorporate the consice promand the Cohere Config wtih a few different eval questions.

# change to try cohere with baseling configs that worked well in the prior runs to see if cohere can match or beat them on the same eval questions

# Finalist 1: Current winner, untouched. Will use as control
BASELINE_FINALIST = BASELINE_CONFIG

# Finalist 2: baseline + concise_prompt (the only config that tied baseline
# on research metrics). Tests whether the concise prompt adds value on top of the baseline retrieval stack.
BASELINE_CONCISE = make_config(
    "baseline_concise",
    base=BASELINE_CONFIG,
    prompt_overrides={
        "research": RESEARCH_PROMPT_TEMPLATE
        + "\nKeep response concise and evidence-grounded, under 120 words.",
        "marketing": MARKETING_PROMPT_TEMPLATE
        + "\nKeep response concise, skimmable, and under 80 words.",
    },
)

# Finalist 3: Cohere version of the baseline — same retrieval stack,
# different generator. Should be an Apples-to-apples LLM swap.
COHERE_BASELINE = make_config(
    "cohere_baseline",
    base=BASELINE_CONFIG,
    llm_provider="cohere",
    cohere_model="command-a-03-2025",
    load_in_4bit=False,
    load_in_8bit=False,
)

In [ ]:
# --- Final comparison: 3 finalists over the labeled validation set ---
# Finalists:
#   1. BASELINE_FINALIST  — experiment winner, untouched
#   2. BASELINE_CONCISE   — baseline retrieval + "concise" prompt overrides
#   3. COHERE_BASELINE    — same retrieval as baseline, Cohere generator
#
# validation_questions_answers contains both labeled (gold answers present)
# and ad-hoc test questions. evaluate_rag needs gold answers to score, so
# we filter to the labeled subset here.
#
# Outputs:
#   full_results  — dict keyed by config name
#   df_full_agg   — aggregate metrics (one row per config x persona)
#   df_full_text  — per-question gold vs generated answers w/ per-q scores

final_configs = [BASELINE_FINALIST, BASELINE_CONCISE, COHERE_BASELINE]

labeled_validation = {
    k: v
    for k, v in validation_questions_answers.items()
    if v.get("gold_answer_research") and v.get("gold_answer_marketing")
}
print(f"Running final comparison on {len(labeled_validation)} labeled Q/A pairs.")

full_results = run_full_evaluation(
    final_configs,
    dataset=labeled_validation,
)

df_full_agg, df_full_text = results_to_dataframe(full_results, include_text=True)
print("\nAggregate metrics across full validation set:")
display(df_full_agg)
print("\nPer-question detail:")
display(df_full_text)

Running final comparison on 75 labeled Q/A pairs.

######################################################################
# EVALUATING: baseline: embed=multi-qa-mpnet-base-dot-v1, chunk=128/0, llm=huggingface:Mistral-7B-Instruct-v0.3, quant=4bit, temp=0.6, max_tok=384, rewriter=False, reranker=False, k=5
######################################################################
Building pipeline: baseline: embed=multi-qa-mpnet-base-dot-v1, chunk=128/0, llm=huggingface:Mistral-7B-Instruct-v0.3, quant=4bit, temp=0.6, max_tok=384, rewriter=False, reranker=False, k=5
------------------------------------------------------------
  [1/6] Creating embeddings & text splitter...

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 11 files:   0%|          | 0/11 [00:00<?, ?it/s]

README.md: 0.00B [00:00, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/multi-qa-mpnet-base-dot-v1
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

  [2/6] Loading documents...
  [1/32] arxiv:2005.11401
  [2/32] arxiv:2104.07567
  [3/32] arxiv:2104.09864
  [4/32] arxiv:2105.03011
  [5/32] arxiv:2106.09685
  [6/32] arxiv:2203.02155
  [7/32] arxiv:2203.15556
  [8/32] arxiv:2211.09260
  [9/32] arxiv:2211.12561
  [10/32] arxiv:2212.09741
  [11/32] arxiv:2305.14314
  [12/32] arxiv:2305.18290
  [13/32] arxiv:2306.15595
  [14/32] arxiv:2309.08872
  [15/32] arxiv:2309.15217
  [16/32] arxiv:2310.06825
  [17/32] arxiv:2310.11511
  [18/32] arxiv:2311.08377
  [19/32] arxiv:2312.05708
  [20/32] arxiv:2401.06532
  [21/32] arxiv:2401.17268
  [22/32] arxiv:2402.01306
  [23/32] arxiv:2402.19473
  [24/32] arxiv:2406.04744
  [25/32] arxiv:2312.10997
  [26/32] arxiv:2410.12812
  [27/32] arxiv:2410.15944
  [28/32] arxiv:2411.16594
  [29/32] arxiv:2404.00657
  [30/32] arxiv:2601.07711
  [31/32] arxiv:2507.09477
  [32/32] arxiv:2506.10408
Arxiv docs=32 splits=1289
  [1/4] wiki:'Generative Artificial Intelligence'
  [2/4] wiki:'Information Retrieval'
  [3/4] wiki:'Large Language Models'
  [4/4] wiki:'Retrieval Augmented Generation'
Wiki docs=10 splits=368
  [1/7] blog:https://lilianweng.github.io/posts/2020-10-29-odqa/
  [2/7] blog:https://lilianweng.github.io/posts/2023-03-15-prompt-engineering/
  [3/7] blog:https://lilianweng.github.io/posts/2018-06-24-attention/
  [4/7] blog:https://lilianweng.github.io/posts/2023-10-25-adv-attack-llm/
  [5/7] blog:https://lilianweng.github.io/posts/2024-07-07-hallucination/
  [6/7] blog:https://huyenchip.com/2025/01/16/ai-engineering-pitfalls.html
  [7/7] blog:https://blog.langchain.com/the-rise-of-context-engineering/
Blogs docs=7 splits=2216
         Cached 3873 chunks to cached_docs_baseline_ce49b47b38.pkl
  [3/6] Building vectorstore...
  [4/6] Loading LLM...

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 13 files:   0%|          | 0/13 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

         Model memory: 3.7505 GB
  [5/6] Skipping reranker (use_reranker=False)...
  [6/6] Compiling graph...
Pipeline "baseline" ready.

Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Total eval time: 2842.4s (75 questions, 37.9s/question)

######################################################################
# EVALUATING: baseline_concise: embed=multi-qa-mpnet-base-dot-v1, chunk=128/0, llm=huggingface:Mistral-7B-Instruct-v0.3, quant=4bit, temp=0.6, max_tok=384, rewriter=False, reranker=False, k=5
######################################################################
Building pipeline: baseline_concise: embed=multi-qa-mpnet-base-dot-v1, chunk=128/0, llm=huggingface:Mistral-7B-Instruct-v0.3, quant=4bit, temp=0.6, max_tok=384, rewriter=False, reranker=False, k=5
------------------------------------------------------------
  [1/6] Creating embeddings & text splitter...

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 11 files:   0%|          | 0/11 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/multi-qa-mpnet-base-dot-v1
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

  [2/6] Loading documents...
  [1/32] arxiv:2005.11401
  [2/32] arxiv:2104.07567
  [3/32] arxiv:2104.09864
  [4/32] arxiv:2105.03011
  [5/32] arxiv:2106.09685
  [6/32] arxiv:2203.02155
  [7/32] arxiv:2203.15556
  [8/32] arxiv:2211.09260
  [9/32] arxiv:2211.12561
  [10/32] arxiv:2212.09741
  [11/32] arxiv:2305.14314
  [12/32] arxiv:2305.18290
  [13/32] arxiv:2306.15595
  [14/32] arxiv:2309.08872
  [15/32] arxiv:2309.15217
  [16/32] arxiv:2310.06825
  [17/32] arxiv:2310.11511
  [18/32] arxiv:2311.08377
  [19/32] arxiv:2312.05708
  [20/32] arxiv:2401.06532
  [21/32] arxiv:2401.17268
  [22/32] arxiv:2402.01306
  [23/32] arxiv:2402.19473
  [24/32] arxiv:2406.04744
  [25/32] arxiv:2312.10997
  [26/32] arxiv:2410.12812
  [27/32] arxiv:2410.15944
  [28/32] arxiv:2411.16594
  [29/32] arxiv:2404.00657
  [30/32] arxiv:2601.07711
  [31/32] arxiv:2507.09477
  [32/32] arxiv:2506.10408
Arxiv docs=32 splits=1289
  [1/4] wiki:'Generative Artificial Intelligence'
  [2/4] wiki:'Information Retrieval'
  [3/4] wiki:'Large Language Models'
  [4/4] wiki:'Retrieval Augmented Generation'
Wiki docs=10 splits=368
  [1/7] blog:https://lilianweng.github.io/posts/2020-10-29-odqa/
  [2/7] blog:https://lilianweng.github.io/posts/2023-03-15-prompt-engineering/
  [3/7] blog:https://lilianweng.github.io/posts/2018-06-24-attention/
  [4/7] blog:https://lilianweng.github.io/posts/2023-10-25-adv-attack-llm/
  [5/7] blog:https://lilianweng.github.io/posts/2024-07-07-hallucination/
  [6/7] blog:https://huyenchip.com/2025/01/16/ai-engineering-pitfalls.html
  [7/7] blog:https://blog.langchain.com/the-rise-of-context-engineering/
Blogs docs=7 splits=2216
         Cached 3873 chunks to cached_docs_baseline_concise_ce49b47b38.pkl
  [3/6] Building vectorstore...
  [4/6] Loading LLM...

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 13 files:   0%|          | 0/13 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

         Model memory: 3.7505 GB
  [5/6] Skipping reranker (use_reranker=False)...
  [6/6] Compiling graph...
Pipeline "baseline_concise" ready.

Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Total eval time: 2378.7s (75 questions, 31.7s/question)

######################################################################
# EVALUATING: cohere_baseline: embed=multi-qa-mpnet-base-dot-v1, chunk=128/0, llm=cohere:command-a-03-2025, quant=api, temp=0.6, max_tok=384, rewriter=False, reranker=False, k=5
######################################################################
Building pipeline: cohere_baseline: embed=multi-qa-mpnet-base-dot-v1, chunk=128/0, llm=cohere:command-a-03-2025, quant=api, temp=0.6, max_tok=384, rewriter=False, reranker=False, k=5
------------------------------------------------------------
  [1/6] Creating embeddings & text splitter...

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 11 files:   0%|          | 0/11 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/multi-qa-mpnet-base-dot-v1
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

  [2/6] Loading documents...
  [1/32] arxiv:2005.11401
  [2/32] arxiv:2104.07567
  [3/32] arxiv:2104.09864
  [4/32] arxiv:2105.03011
  [5/32] arxiv:2106.09685
  [6/32] arxiv:2203.02155
  [7/32] arxiv:2203.15556
  [8/32] arxiv:2211.09260
  [9/32] arxiv:2211.12561
  [10/32] arxiv:2212.09741
  [11/32] arxiv:2305.14314
  [12/32] arxiv:2305.18290
  [13/32] arxiv:2306.15595
  [14/32] arxiv:2309.08872
  [15/32] arxiv:2309.15217
  [16/32] arxiv:2310.06825
  [17/32] arxiv:2310.11511
  [18/32] arxiv:2311.08377
  [19/32] arxiv:2312.05708
  [20/32] arxiv:2401.06532
  [21/32] arxiv:2401.17268
  [22/32] arxiv:2402.01306
  [23/32] arxiv:2402.19473
  [24/32] arxiv:2406.04744
  [25/32] arxiv:2312.10997
  [26/32] arxiv:2410.12812
  [27/32] arxiv:2410.15944
  [28/32] arxiv:2411.16594
  [29/32] arxiv:2404.00657
  [30/32] arxiv:2601.07711
  [31/32] arxiv:2507.09477
  [32/32] arxiv:2506.10408
Arxiv docs=32 splits=1289
  [1/4] wiki:'Generative Artificial Intelligence'
  [2/4] wiki:'Information Retrieval'
  [3/4] wiki:'Large Language Models'
  [4/4] wiki:'Retrieval Augmented Generation'
Wiki docs=10 splits=368
  [1/7] blog:https://lilianweng.github.io/posts/2020-10-29-odqa/
  [2/7] blog:https://lilianweng.github.io/posts/2023-03-15-prompt-engineering/
  [3/7] blog:https://lilianweng.github.io/posts/2018-06-24-attention/
  [4/7] blog:https://lilianweng.github.io/posts/2023-10-25-adv-attack-llm/
  [5/7] blog:https://lilianweng.github.io/posts/2024-07-07-hallucination/
  [6/7] blog:https://huyenchip.com/2025/01/16/ai-engineering-pitfalls.html
  [7/7] blog:https://blog.langchain.com/the-rise-of-context-engineering/
Blogs docs=7 splits=2216
         Cached 3873 chunks to cached_docs_cohere_baseline_ce49b47b38.pkl
  [3/6] Building vectorstore...
  [4/6] Loading LLM...
         Cohere model: command-a-03-2025
  [5/6] Skipping reranker (use_reranker=False)...
  [6/6] Compiling graph...
Pipeline "cohere_baseline" ready.

  [cohere-limiter] sleeping 20.3s to respect rate limit
  [cohere-limiter] sleeping 2.6s to respect rate limit
  [cohere-limiter] sleeping 1.5s to respect rate limit
  [cohere-limiter] sleeping 1.5s to respect rate limit
  [cohere-limiter] sleeping 0.5s to respect rate limit
  [cohere-limiter] sleeping 0.9s to respect rate limit
  [cohere-limiter] sleeping 0.9s to respect rate limit
  [cohere-limiter] sleeping 1.6s to respect rate limit
  [cohere-limiter] sleeping 0.8s to respect rate limit
  [cohere-limiter] sleeping 0.8s to respect rate limit
  [cohere-limiter] sleeping 14.2s to respect rate limit
  [cohere-limiter] sleeping 2.5s to respect rate limit
  [cohere-limiter] sleeping 0.2s to respect rate limit
  [cohere-limiter] sleeping 0.8s to respect rate limit
  [cohere-limiter] sleeping 0.8s to respect rate limit
  [cohere-limiter] sleeping 3.5s to respect rate limit
  [cohere-limiter] sleeping 9.9s to respect rate limit
  [cohere-limiter] sleeping 0.5s to respect rate limit
  [cohere-limiter] sleeping 1.7s to respect rate limit
  [cohere-limiter] sleeping 1.7s to respect rate limit
  [cohere-limiter] sleeping 0.5s to respect rate limit
  [cohere-limiter] sleeping 0.5s to respect rate limit
  [cohere-limiter] sleeping 1.4s to respect rate limit
  [cohere-limiter] sleeping 0.3s to respect rate limit
  [cohere-limiter] sleeping 3.5s to respect rate limit
  [cohere-limiter] sleeping 3.2s to respect rate limit
  [cohere-limiter] sleeping 3.2s to respect rate limit
  [cohere-limiter] sleeping 3.9s to respect rate limit
  [cohere-limiter] sleeping 2.2s to respect rate limit
  [cohere-limiter] sleeping 2.2s to respect rate limit
  [cohere-limiter] sleeping 0.9s to respect rate limit
  [cohere-limiter] sleeping 1.2s to respect rate limit
  [cohere-limiter] sleeping 1.2s to respect rate limit
  [cohere-limiter] sleeping 1.0s to respect rate limit
  [cohere-limiter] sleeping 2.0s to respect rate limit
  [cohere-limiter] sleeping 2.0s to respect rate limit
  [cohere-limiter] sleeping 6.0s to respect rate limit
  [cohere-limiter] sleeping 2.0s to respect rate limit
  [cohere-limiter] sleeping 2.0s to respect rate limit
  [cohere-limiter] sleeping 1.7s to respect rate limit
  [cohere-limiter] sleeping 1.3s to respect rate limit
  [cohere-limiter] sleeping 1.3s to respect rate limit
  [cohere-limiter] sleeping 4.0s to respect rate limit
  [cohere-limiter] sleeping 0.1s to respect rate limit
  [cohere-limiter] sleeping 0.1s to respect rate limit
  [cohere-limiter] sleeping 3.3s to respect rate limit
  [cohere-limiter] sleeping 1.6s to respect rate limit
  [cohere-limiter] sleeping 1.6s to respect rate limit
  [cohere-limiter] sleeping 1.6s to respect rate limit
  [cohere-limiter] sleeping 0.6s to respect rate limit
  [cohere-limiter] sleeping 3.9s to respect rate limit
  [cohere-limiter] sleeping 3.9s to respect rate limit
  [cohere-limiter] sleeping 2.6s to respect rate limit
  [cohere-limiter] sleeping 1.4s to respect rate limit
  [cohere-limiter] sleeping 1.4s to respect rate limit
  [cohere-limiter] sleeping 4.4s to respect rate limit
  [cohere-limiter] sleeping 5.9s to respect rate limit
  [cohere-limiter] sleeping 1.8s to respect rate limit
  [cohere-limiter] sleeping 1.8s to respect rate limit
  [cohere-limiter] sleeping 1.2s to respect rate limit
  [cohere-limiter] sleeping 0.2s to respect rate limit  [cohere-limiter] sleeping 0.2s to respect rate limit

  [cohere-limiter] sleeping 0.6s to respect rate limit
  [cohere-limiter] sleeping 0.6s to respect rate limit
  [cohere-limiter] sleeping 0.8s to respect rate limit
  [cohere-limiter] sleeping 4.3s to respect rate limit
  [cohere-limiter] sleeping 4.3s to respect rate limit
  [cohere-limiter] sleeping 0.2s to respect rate limit
  [cohere-limiter] sleeping 2.2s to respect rate limit  [cohere-limiter] sleeping 2.2s to respect rate limit

  [cohere-limiter] sleeping 4.8s to respect rate limit
  [cohere-limiter] sleeping 3.1s to respect rate limit
  [cohere-limiter] sleeping 3.1s to respect rate limit
  [cohere-limiter] sleeping 6.5s to respect rate limit
  [cohere-limiter] sleeping 0.5s to respect rate limit
  [cohere-limiter] sleeping 0.5s to respect rate limit
  [cohere-limiter] sleeping 1.9s to respect rate limit
  [cohere-limiter] sleeping 0.4s to respect rate limit
  [cohere-limiter] sleeping 0.4s to respect rate limit
  [cohere-limiter] sleeping 0.5s to respect rate limit
  [cohere-limiter] sleeping 0.3s to respect rate limit
  [cohere-limiter] sleeping 0.3s to respect rate limit
  [cohere-limiter] sleeping 3.8s to respect rate limit
  [cohere-limiter] sleeping 3.8s to respect rate limit

Total eval time: 816.6s (75 questions, 10.9s/question)


================================================================================
COMPARISON SUMMARY
================================================================================
Config                   Persona        BERT-F1   ROUGE-L     Faith   Len-R     Time
------------------------------------------------------------------------------------
baseline                 Research        0.8578    0.2136    0.8635    1.36  2842.4s
baseline                 Marketing       0.8693    0.2181    0.8649    2.57
baseline_concise         Research        0.8601    0.2481    0.8690    1.19  2378.7s
baseline_concise         Marketing       0.8683    0.2381    0.8543    1.93
cohere_baseline          Research        0.8758    0.2535    0.8943    1.24   816.6s
cohere_baseline          Marketing       0.8813    0.2253    0.8792    2.08

Aggregate metrics across full validation set:

,config,persona,bertscore_f1,rouge_l,faithfulness_f1,length_ratio,eval_time_sec
5,cohere_baseline,Marketing,0.8813,0.2253,0.8792,2.08,816.6
1,baseline,Marketing,0.8693,0.2181,0.8649,2.57,2842.4
3,baseline_concise,Marketing,0.8683,0.2381,0.8543,1.93,2378.7
4,cohere_baseline,Research,0.8758,0.2535,0.8943,1.24,816.6
2,baseline_concise,Research,0.8601,0.2481,0.8690,1.19,2378.7
0,baseline,Research,0.8578,0.2136,0.8635,1.36,2842.4

Per-question detail:

,config,q_id,question,gold_research,gen_research,bert_f1_research,rouge_l_research,gold_marketing,gen_marketing,bert_f1_marketing,rouge_l_marketing
0,baseline,0,"What pre-trained neural retriever model is used as the non-parametric memory component in RAG, providing latent documents conditioned on the input?",The pre-trained neural retriever model used as the non-parametric memory component in RAG is the Dense Passage Retriever (DPR). DPR provides latent documents conditioned on the input for the seq2seq model (BART) to generate the output. This retriever is initialized using retrieval supervision on...,"You are answering for a marketing audience. Use the context to provide a concise, persuasive, and easy-to-understand response that highlights the benefits and differentiating features of RAG.\n\nQuestion: How does RAG revolutionize the way businesses generate information, and why should they cho...",0.8296,0.1498,The pre-trained neural retriever model used as the non-parametric memory component in RAG is the Dense Passage Retriever (DPR).,"The pre-trained neural retriever model, a non-parametric memory component, is used in RAG (Retrieval-Augmented Generation) to provide relevant latent documents based on the given input query. This model is integral to RAG's architecture, aiming to deliver more accurate and contextually relevant ...",0.8942,0.3881
1,baseline,4,How does the BM25 technique determine which passages are most relevant to a given query?,The BM25 technique determines which passages are most relevant to a given query by calculating a relevance score based on the frequency of query terms in each passage and the inverse document frequency. By using gold passages from the same mini-batch and one negative passage with a high BM25 sco...,You are answering for a marketing audience. Craft a concise and clear response that highlights the benefits and applications of the BM25 technique for improving search results while still maintaining a general and approachable tone.\n\nQuestion: How does the BM25 technique improve search results...,0.8387,0.1514,The BM25 technique determines the relevance of passages by combining a score based on BM25 with a dense embedding retrieval score. This new ranking function helps improve retrieval results by using gold passages from the same mini-batch along with one negatively scored passage.,"When it comes to determining the most relevant passages for a given query, BM25 uses a ranking system based on the classic TF-IDF (Term Frequency-Inverse Document Frequency) method. This is achieved by treating the passages as a bag of words and scoring their relevance based on a dot-product of ...",0.8562,0.2290
2,baseline,5,How does the RAG (retrieval-augmented generation) model leverage neural retrievers and document representation techniques to enhance the retrieval and generation process compared to earlier word-similarity-based methods?,"The RAG model leverages a Dense Passage Retriever (DPR) that is pre-trained to rank correct passages in various question-answering settings. This allows for more accurate retrieval of relevant document chunks. The bi/dual-encoder nature of the DPR model enables effective document representation,...",Answer for a Marketing audience:\n\nQuestion: How does the RAG (retrieval-augmented generation) model revolutionize AI language models and make them more effective in understanding and responding to complex queries compared to traditional models?\n\nContext:\n\nQuestion: How does the RAG (retrie...,0.8489,0.1622,"The RAG model combines neural retrievers, like the Dense Passage Retriever (DPR), with document representation techniques to improve retrieval and generation. This integration allows for contextually relevant and factually accurate responses compared to earlier word-similarity-based methods. The...","For our marketing audience, we can simplify the above explanation to:\n\n""Our innovative Retrieval-Augmented Generation (RAG) model works alongside existing large language models (LLMs). Instead of relying solely on word similarity, RAG retrieves relevant information from vast databases, enhanci...",0.8682,0.1613
3,baseline,11,How does the introduction of rotary position encoding (RoPE) in RoFormer influence the training convergence and evaluation metrics when compared to traditional position encoding methods in transformer-based models?,"The introduction of rotary position encoding (RoPE) in RoFormer may improve training convergence and evaluation metrics compared to traditional position encoding methods in transformer-based models. RoPE offers valuable properties such as sequence length flexibility, decaying inter-token depende...","Given the context provided, it cannot be definitively stated how the introduction of rotary position encoding (RoPE) in RoFormer influences the training convergence and evaluation metrics when compared to traditional position encoding methods in transformer-based models. The context focuses on t...",0.8937,0.3478,The introduction of rotary position encoding (RoPE) in RoFormer improves training convergence and evaluation metrics compared to traditional position encoding methods in transformer-based models. This is evidenced by better performance results in terms of loss and accuracy across different train...,"As a reliable assistant, I am unable to provide a clear comparison between RoPE in RoFormer and traditional position encoding methods in transformer-based models based on the provided context. The context does mention the use of RoPE in RoFormer, but it does not provide any information about how...",0.8892,0.2810
4,baseline,13,Which characteristics or innovations distinguish Longformer from other transformer-based models when processing lengthy texts?,"Longformer stands out from other transformer-based models by its ability to efficiently process input sequences that are thousands of tokens long, specifically supporting input sequence lengths of up to 16K tokens. This capability allows Longformer to encode 99% of full texts in the QASPER datas...","You are answering for a marketing audience.\nUse the context to provide a compelling, easy-to-understand response that highlights the benefits of Longformer for lengthy text processing.\n\nQuestion: What makes Longformer the ideal solution for businesses that deal with lengthy text data?\n\nCont...",0.8322,0.1283,"Longformer differentiates itself by its support for processing input sequences up to 16K tokens long without truncation, a capability that enables it to encode 99% of full-text papers in the QASPER dataset. This is made possible by its Longformer-Encoder-Decoder (LED) architecture, which efficie...","For a marketing audience, here's a clear and concise summary:\n\n""Longformer, a transformer-based model, stands out in the field of processing lengthy texts. Unlike traditional models, it supports extensive contexts, making it ideal for handling data-heavy tasks. Under the hood, Longformer opera...",0.8563,0.1270
...,...,...,...,...,...,...,...,...,...,...,...
220,cohere_baseline,206,What are the primary differences between white-box and black-box adversarial attacks?,"White-box attacks involve attackers having full access to the model architecture, weights, and training pipeline, allowing them to obtain gradient signals for adversarial attacks. On the other hand, black-box attacks assume attackers only have access to an API-like service without detailed infor...","In white-box adversarial attacks, the attacker has complete knowledge of the model, including its weights, architecture, and training process, allowing them to craft highly targeted and effective perturbations by directly computing gradients or leveraging model-specific vulnerabilities. Converse...",0.8961,0.3150,"White-box attacks have full access to model details like weights and architecture, while black-box attacks only have access to input-output interface like an API. White-box attacks are more powerful but black-box attacks are based on limited information.","White-box and black-box adversarial attacks differ primarily in the level of access attackers have to the AI model. In **white-box attacks**, attackers have complete visibility into the model’s inner workings, including its architecture and training data, allowing them to craft highly targeted b...",0.8725,0.1988
221,cohere_baseline,213,How can external knowledge sources be leveraged to reduce or detect hallucinations in generated content?,"External knowledge sources can be leveraged to reduce or detect hallucinations in generated content by integrating external or in-context knowledge during reasoning. By retrieving structured sources like databases or web content, models can provide factual grounding and reduce hallucinations. Ad...","To reduce or detect hallucinations in generated content, **retrieval-augmented generation (RAG)** can be employed, where the model is grounded by external knowledge sources during the generation process. This approach ensures that the model's output is anchored to factual information retrieved f...",0.8698,0.2427,"External knowledge sources can be leveraged to reduce or detect hallucinations in generated content by integrating structured data from databases or web content, providing factual grounding. This can help bridge logical gaps and enhance contextual coherence in the generated output.","Leveraging external knowledge sources is a powerful way to enhance the accuracy and reliability of AI-generated content. By incorporating retrieval methods, the model can access and verify information from trusted sources, significantly reducing the occurrence of hallucinations—instances where t...",0.8736,0.1761
222,cohere_baseline,215,What are the effects of fine-tuning on new knowledge with respect to a model’s tendency to hallucinate?,"Fine-tuning LLMs on new knowledge can lead to slower learning of examples with new knowledge compared to examples consistent with pre-existing knowledge. However, once the new knowledge examples are learned, it can increase the model's tendency to hallucinate. Using retrieval to ground model gen...","Fine-tuning on new knowledge can exacerbate a model's tendency to hallucinate, as the process may introduce inconsistencies or inaccuracies present in the fine-tuning data. This occurs because LLMs learn fine-tuning examples with new knowledge at a slower rate compared to other examples, leading...",0.8754,0.2258,"Fine-tuning on new knowledge may initially slow down the learning process in LLMs compared to consistent knowledge. However, once the new knowledge is learned, it can actually reduce the model's tendency to hallucinate.","Fine-tuning large language models (LLMs) with new knowledge can inadvertently increase the likelihood of hallucinations, where the model generates incorrect or unsupported information. This happens because LLMs may struggle to integrate new knowledge as effectively as they handle existing data. ...",0.8732,0.2276
223,cohere_baseline,217,What approaches exist for calibrating models to better handle questions where the correct answer is unknown or unanswerable?,"There are several approaches for calibrating models to handle questions with unknown or unanswerable correct answers. One approach is to measure the model's output uncertainty when faced with such questions. Another method is to prompt the model to generate responses to unanswerable questions, w...","For calibrating models to handle questions with unknown or unanswerable answers, several technical approaches exist. **Output Uncertainty Measurement** involves quantifying the model's confidence in its predictions, allowing it to flag uncertain responses. A **Self-Verification Process** enables...",0.8764,0.3438,Approaches for calibrating models to better handle questions where the correct answer is unknown or unanswerable include using the model's own confidence level as a proxy for truthfulness and implementing reference-free methods that rely on the model's output probabilities. These methods help en...,"To ensure our AI models provide reliable answers, especially when the correct response is unclear, we employ several strategies. First, we measure the model’s confidence in its output, allowing it to flag uncertain answers. Second, the model undergoes a self-verification process to double-check ...",0.8773,0.2353
224,cohere_baseline,220,What challenges can arise from relying solely on automated or AI-based evaluation methods?,"Relying solely on automated or AI-based evaluation methods can lead to challenges such as biases in the outputs, irrelevance, toxicity, or bias in the responses, disjointed or incoherent outputs when integrating retrieved information with different tasks, redundancy in responses when similar inf...","Relying solely on automated or AI-based evaluation methods can introduce several technical challenges. First, **lack of validation** poses a significant risk, as AI models may produce inaccurate or unreliable results without systematic human evaluation to ensure correlation and accuracy. Second,...",0.8706,0.1946,"Relying solely on automated or AI-based evaluation methods can lead to biased, irrelevant, or toxic outputs, which can lower the quality and reliability of responses. Without human evaluation, integration of retrieved information can be challenging, resulting in disjointed or repetitive outputs....","Relying solely on automated or AI-based evaluation methods can lead to significant challenges that impact product quality and customer trust. Without validation through human evaluation, AI judgments may lack accuracy, potentially delivering unreliable results. Additionally, this approach often ...",0.8981,0.3066

## 5. Results

### 5.1 Model Specifications

Document the detailed specs of your choices. Also comment on how you valued the needs of the marketing team vs the needs of the researchers, in case you had to make a trade-off.

**QUESTION:**

5.1.a Provide the detailed specification of your pipelines.

**5.1.a Pipeline Specification**

My final chosen pipeline is `cohere_baseline`, which pairs a lightweight retrieval stack with the Cohere Command A (03-2025) LLM as the main generator.

| Component | Choice |
|---|---|
| **Embedding model** | `multi-qa-mpnet-base-dot-v1` (sentence-transformers, 768-dim) |
| **Chunk size / overlap** | 128 tokens / 0 overlap |
| **Vector store** | Qdrant (in-memory, cosine similarity) |
| **Retriever k** | 5 |
| **Rewriter** | Disabled |
| **Reranker** | Disabled |
| **LLM** | Cohere `command-a-03-2025` (API-based) |
| **Temperature** | 0.6 |
| **Max output tokens** | 384 |
| **Quantization** | N/A (API model) |

**Trade-off between audiences:** The same retrieval stack serves both personas; differentiation happens entirely at the prompt level. The engineering prompt asks for technical depth, terminology, and citations, while the marketing prompt asks for a value-proposition lead, no jargon, and a 4-sentence limit. I prioritized faithfulness (grounding in context) equally for both audiences, which is reflected in the high faithfulness scores (Research: 0.894, Marketing: 0.879). The marketing persona's slightly higher length ratio (2.08 vs 1.24) is an acceptable trade-off: marketing answers add framing language around core facts, inflating word count relative to the more concise gold references.

**Why this config won:** In the 11-config experimental runs, the baseline retrieval setup (no rewriter, no reranker, small chunks) outperformed the fully optimized pipeline and more complex variants. When I then tested three finalists on the full 75-question validation set -- the original Mistral-7B baseline, a concise-prompt variant (which performed well in experiments and included a few tweaks to the prompts), and this Cohere-backed variant -- the Cohere baseline dominated: highest BERT-F1 and faithfulness on both personas, 3.5x faster, and competitive ROUGE-L scores.

In [ ]:
### Q5-1-a Grading Tag: Don't edit this line.

"""
COHERE_BASELINE_CONFIG = make_config(
    "cohere_baseline",
    embedding_model="multi-qa-mpnet-base-dot-v1",
    chunk_size=128,
    chunk_overlap=0,
    load_in_4bit=True,
    max_new_tokens=368,
    temperature=0.6,
    repetition_penalty=1.2,
    use_rewriter=False,
    use_reranker=False,

    # LLM + quantization
    llm_provider: str = "cohere"
    llm_model: str = "command-a-03-2025"
    load_in_4bit: bool = True
    bnb_4bit_quant_type: str = "nf4"
    bnb_4bit_use_double_quant: bool = True
    bnb_4bit_compute_dtype: str = "bfloat16"

    # Generation
    top_p: float = 0.95
    do_sample: bool = True

    # Retrieval
    retriever_k: int = 5
)
"""

### ENTER NOTHING HERE. THIS IS A PLACE HOLDER

### Fresh Pipeline Rebuilt to answer the questions since my initial run did not provide this.

In [36]:
def run_test_question_report(
    test_dataset: dict,
    config,
    metric_ids: tuple = (),
    scorer=None,
):
    """
    Run each question in `test_dataset` through a fresh pipeline built from
    `config` and print the responses needed for the section 5 questions
        a) research + marketing responses
        b) context passed to the LLM
        c) doc_source for each context document
        d) per-persona BERTScore/ROUGE vs gold (only for item_ids in `metric_ids`)

    Pass the gold answers inside `test_dataset[item_id]` as
    `gold_answer_research` / `gold_answer_marketing` so (d) can score them.
    """
    from rouge_score import rouge_scorer as _rs

    _rouge = _rs.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=True)

    def _bert(pred, ref):
        if scorer is not None:
            p, r, f = scorer.score([pred], [ref])
        else:
            from bert_score import score as bscore

            p, r, f = bscore([pred], [ref], lang="en", verbose=False)
        return float(p.mean()), float(r.mean()), float(f.mean())

    print(f"Building pipeline from config: {config.name}")
    graph, _ = build_rag_pipeline(config)

    results = {}
    for item_id, item in test_dataset.items():
        question = item.get("question", "")
        print("\n" + "=" * 80)
        print(f"TEST QUESTION {item_id}: {question}")
        print("=" * 80)

        state = graph.invoke({"question": question})

        research = state.get("research_answer") or ""
        marketing = state.get("marketing_answer") or ""
        context = state.get("retrieved_context") or ""
        sources = state.get("source_documents") or []

        # (a) responses
        print("\n--- (a.i) RESEARCH RESPONSE ---")
        print(research)
        print("\n--- (a.ii) MARKETING RESPONSE ---")
        print(marketing)

        # (b) context
        print("\n--- (b) CONTEXT PASSED TO LLM ---")
        print(context)

        # (c) sources
        print("\n--- (c) DOCUMENT SOURCES ---")
        doc_sources = []
        for i, d in enumerate(sources):
            md = d if isinstance(d, dict) else (getattr(d, "metadata", {}) or {})
            src = (
                md.get("doc_source")
                or md.get("source")
                or md.get("title")
                or "<unknown>"
            )
            doc_sources.append(src)
            print(f"  [{i}] {src}")

        entry = {
            "question": question,
            "research_answer": research,
            "marketing_answer": marketing,
            "retrieved_context": context,
            "doc_sources": doc_sources,
        }

        # (d) metrics — only for the item_ids the caller asked for
        if item_id in metric_ids:
            gold_res = item.get("gold_answer_research", "")
            gold_mkt = item.get("gold_answer_marketing", "")

            print("\n--- (d.i) RESEARCH METRICS vs GOLD ---")
            br_p, br_r, br_f = _bert(research, gold_res)
            rs_res = _rouge.score(gold_res, research)
            research_metrics = [
                ("bertscore_precision", round(br_p, 4)),
                ("bertscore_recall", round(br_r, 4)),
                ("bertscore_f1", round(br_f, 4)),
                ("rouge1_f", round(rs_res["rouge1"].fmeasure, 4)),
                ("rouge2_f", round(rs_res["rouge2"].fmeasure, 4)),
                ("rougeL_f", round(rs_res["rougeL"].fmeasure, 4)),
            ]
            for name, val in research_metrics:
                print(f"  {name}: {val}")

            print("\n--- (d.ii) MARKETING METRICS vs GOLD ---")
            bm_p, bm_r, bm_f = _bert(marketing, gold_mkt)
            rs_mkt = _rouge.score(gold_mkt, marketing)
            marketing_metrics = [
                ("bertscore_precision", round(bm_p, 4)),
                ("bertscore_recall", round(bm_r, 4)),
                ("bertscore_f1", round(bm_f, 4)),
                ("rouge1_f", round(rs_mkt["rouge1"].fmeasure, 4)),
                ("rouge2_f", round(rs_mkt["rouge2"].fmeasure, 4)),
                ("rougeL_f", round(rs_mkt["rougeL"].fmeasure, 4)),
            ]
            for name, val in marketing_metrics:
                print(f"  {name}: {val}")

            entry["research_metrics"] = research_metrics
            entry["marketing_metrics"] = marketing_metrics

        results[item_id] = entry

    return results

In [ ]:
# --- Run the winning finalist against the 5.2 test questions ---
WINNER_CONFIG = COHERE_BASELINE  #

test_questions_5_2 = {
    0: validation_questions_answers[0],
    134: validation_questions_answers[134],
    225: test_questions[225],
}

# metric_ids restricts (d) scoring to Q1 and Q2 (0 and 134).
test_5_2_results = run_test_question_report(
    test_questions_5_2,
    WINNER_CONFIG,
    metric_ids=(0, 134),
    scorer=bert_scorer,
)

Building pipeline from config: cohere_baseline
Building pipeline: cohere_baseline: embed=multi-qa-mpnet-base-dot-v1, chunk=128/0, llm=cohere:command-a-03-2025, quant=api, temp=0.6, max_tok=384, rewriter=False, reranker=False, k=5
------------------------------------------------------------
  [1/6] Creating embeddings & text splitter...

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 11 files:   0%|          | 0/11 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/multi-qa-mpnet-base-dot-v1
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

  [2/6] Loading documents...
         Loaded 3873 chunks from cached_docs_cohere_baseline_ce49b47b38.pkl.
  [3/6] Building vectorstore...
  [4/6] Loading LLM...
         Cohere model: command-a-03-2025
  [5/6] Skipping reranker (use_reranker=False)...
  [6/6] Compiling graph...
Pipeline "cohere_baseline" ready.


================================================================================
TEST QUESTION 0: What pre-trained neural retriever model is used as the non-parametric memory component in RAG, providing latent documents conditioned on the input?
================================================================================

--- (a.i) RESEARCH RESPONSE ---
The context does not explicitly name the pre-trained neural retriever model used as the non-parametric memory component in RAG. It only states that RAG combines pre-trained parametric and non-parametric components, with the latter providing latent documents conditioned on the input. Without specific details, it’s uncertain which exact retriever model (e.g., Dense Passage Retrieval, BM25, or others) is employed. Further investigation into the implementation details or reference materials would be necessary to identify the specific model used.

--- (a.ii) MARKETING RESPONSE ---
The context does not specify the exact pre-trained neural retriever model used as the non-parametric memory component in RAG. However, this component plays a crucial role in enhancing the system’s ability to retrieve relevant information from a vast knowledge base, ensuring accurate and contextually appropriate responses. By leveraging such a model, the system can dynamically access latent documents based on user input, improving the overall reliability and relevance of the output for customers. For customer-facing content, this means more precise and informed interactions, delivering greater value in real-world applications.

--- (b) CONTEXT PASSED TO LLM ---
RAG (“Retrieval-Augmented Generation”; Lewis et al., 2020) combines pre-trained parametric (language model) and non-parametric

An illustration of retrieval-augmented generation (RAG) architecture. (Image source: Lewis et al., 2020)

(RAG) — models which combine pre-trained parametric and non-parametric mem-

training data [28]. Retrieval-Augmented Generation (RAG)
aims to mitigate these issues with its flexible data reposi-

A typical RAG process is depicted in Fig. 1. Given an input
query, the retriever identifies relevant data sources, and the re-

--- (c) DOCUMENT SOURCES ---
  [0] WWW
  [1] WWW
  [2] arxiv_pdfs/2005.11401.pdf
  [3] arxiv_pdfs/2402.19473.pdf
  [4] arxiv_pdfs/2402.19473.pdf

--- (d.i) RESEARCH METRICS vs GOLD ---
  bertscore_precision: 0.8774
  bertscore_recall: 0.8788
  bertscore_f1: 0.8781
  rouge1_f: 0.4865
  rouge2_f: 0.3014
  rougeL_f: 0.3649

--- (d.ii) MARKETING METRICS vs GOLD ---
  bertscore_precision: 0.8466
  bertscore_recall: 0.9052
  bertscore_f1: 0.8749
  rouge1_f: 0.2957
  rouge2_f: 0.2301
  rougeL_f: 0.2957

================================================================================
TEST QUESTION 134: What benefits does Retrieval Augmented Generation (RAG) offer over traditional language models with respect to providing reliable and up-to-date answers, and how does its approach contribute to these improvements?
================================================================================

--- (a.i) RESEARCH RESPONSE ---
Retrieval Augmented Generation (RAG) offers significant advantages over traditional language models by addressing the limitations of static, pre-trained knowledge. Firstly, RAG incorporates an information-retrieval mechanism, enabling the model to access and integrate up-to-date information from external sources. This dynamic knowledge access ensures that responses are based on the most current and relevant data, mitigating the risk of outdated or incomplete answers inherent in models relying solely on pre-trained knowledge. By combining retrieval with generation, RAG enhances reliability and accuracy, as it can ground its responses in recent, contextually appropriate information. This approach is particularly valuable in rapidly evolving domains where traditional models may struggle to provide timely and accurate insights.

--- (a.ii) MARKETING RESPONSE ---
Retrieval Augmented Generation (RAG) significantly enhances the reliability and timeliness of answers compared to traditional language models by dynamically accessing up-to-date information from external sources. Unlike models that rely solely on pre-trained knowledge, which can become outdated, RAG retrieves and incorporates the latest data, ensuring answers are both accurate and current. This approach is particularly valuable for industries where information changes rapidly, such as news, healthcare, or technology, as it provides customers with the most relevant and trustworthy responses. By combining retrieval with generation, RAG delivers a seamless user experience, fostering greater confidence in the information provided.

--- (b) CONTEXT PASSED TO LLM ---
Retrieval-augmented generation (RAG) enhances large language models (LLMs) by incorporating an information-retrieval mechanism

Retrieval-augmented generation (RAG) is an effective way to use
large language models (LLMs) to answer questions while avoiding

Retrieval-Augmented
Generation
(RAG)
has
emerged as a powerful framework to overcome the

Retrieval-augmented generation (RAG) is a technique that enables large language models (LLMs) to retrieve and incorporate new

Retrieval-Augmented Generation (RAG) has recently emerged as a promising solu-

--- (c) DOCUMENT SOURCES ---
  [0] https://en.wikipedia.org/wiki/Retrieval-augmented_generation
  [1] arxiv_pdfs/2410.12812.pdf
  [2] arxiv_pdfs/2506.10408.pdf
  [3] https://en.wikipedia.org/wiki/Retrieval-augmented_generation
  [4] arxiv_pdfs/2406.04744.pdf

--- (d.i) RESEARCH METRICS vs GOLD ---
  bertscore_precision: 0.909
  bertscore_recall: 0.9178
  bertscore_f1: 0.9134
  rouge1_f: 0.5872
  rouge2_f: 0.1852
  rougeL_f: 0.3119

--- (d.ii) MARKETING METRICS vs GOLD ---
  bertscore_precision: 0.8947
  bertscore_recall: 0.9287
  bertscore_f1: 0.9114
  rouge1_f: 0.4832
  rouge2_f: 0.1905
  rougeL_f: 0.2685

================================================================================
TEST QUESTION 225: What actor plays the role of Thanos in the Marvel Universe and the role of Cable in Deadpool 2?
================================================================================

--- (a.i) RESEARCH RESPONSE ---
The actor who portrays Thanos in the Marvel Cinematic Universe (MCU) and Cable in *Deadpool 2* is **Josh Brolin**. Brolin's performance as Thanos spans multiple MCU films, culminating in *Avengers: Infinity War* and *Avengers: Endgame*, where he is depicted through motion capture technology. In *Deadpool 2*, Brolin plays Cable, a time-traveling mutant, requiring both physical and emotional depth in his portrayal. His ability to embody these distinct characters showcases his versatility as an actor in both motion capture and traditional roles.

--- (a.ii) MARKETING RESPONSE ---
Josh Brolin is the talented actor behind two iconic Marvel characters: the formidable villain Thanos in the Marvel Cinematic Universe and the time-traveling Cable in *Deadpool 2*. His versatile performances bring these complex characters to life, captivating audiences with their depth and intensity. This dual role showcases Brolin's range and ability to embody both a universe-threatening titan and a grizzled, cybernetic warrior, making him a standout figure in the Marvel franchise.

--- (b) CONTEXT PASSED TO LLM ---
one out of these candidates.

Answer:

Diego de Las Casas, Lisa Anne Hendricks, Johannes Welbl, Aidan Clark, Tom Hennigan, Eric Noland,

co-stars.

the answer.

--- (c) DOCUMENT SOURCES ---
  [0] WWW
  [1] WWW
  [2] arxiv_pdfs/2203.15556.pdf
  [3] WWW
  [4] WWW



**QUESTION:**

5.1.b: What is the prompt you used for the engineering research group?

*Paste your 5.1.b answer in this text box here.  Double click to open.*

In [ ]:
### Q5-1-b Grading Tag: Don't edit this line.

"""[INST] User: You are answering for an engineering audience.
Use the context to provide a technical answer with concrete details and correct terminology. Consider that your answer may be evaluated by experts, so be precise and comprehensive in your response."""

### ENTER NOTHING HERE. THIS IS A PLACE HOLDER

:

**QUESTION:**

5.1.c.: What is the prompt you used for the marketing group??

*Paste your 5.1.c answer in this text box here.  Double click to open.*

In [ ]:
### Q5-1-c Grading Tag: Don't edit this line.

"""[INST] User: You are answering for a marketing audience.
Use the context to provide an accurate, concise, non-technical summary with clear product/value framing. Consider that your marketing team will use this answer to create customer-facing content, so focus on clarity and relevance to customer benefits."""

### ENTER NOTHING HERE. THIS IS A PLACE HOLDER


### 5.2 Some Test Questions


Please study the answers generated by your chosen setup for these specific test questions:

1. "What pre-trained neural retriever model is used as the non-parametric memory component in RAG, providing latent documents conditioned on the input?" (Question 0)

2. "What benefits does Retrieval Augmented Generation (RAG) offer over traditional language models with respect to providing reliable and up-to-date answers, and how does its approach contribute to these improvements?" (Question 134)

3. "What actor played the role of Thanos in the Marvel Universe and the role of Cable in Deadpool 2?" (Question 225, no labeled answers)

For each of the three questions above please provide:

a) The RAG results (research and marketing response)  
b) The context provided  
c) The document sources for the context  

Then, for questions 1 and 2,

d) Also discuss your metric(s) for the two examples (for both responses) compared to the gold responses and comment on how well you feel your metrics captured the differences and similarities between your answer and the gold answer?

Put your answers to these questions into the appropriate cells below.

#### 5.2.1 Test Question 1


Please run the test question 0 through your RAG pipeline show the results in the questions below:

**QUESTION:**

5.2.1.a.i. What is the engineering response for Test Question 1?

The context does not explicitly name the pre-trained neural retriever model used as the non-parametric memory component in RAG. It only states that RAG combines pre-trained parametric and non-parametric components, with the latter providing latent documents conditioned on the input. Without specific details, it's uncertain which exact retriever model (e.g., Dense Passage Retrieval, BM25, or others) is employed. Further investigation into the implementation details or reference materials would be necessary to identify the specific model used.

**QUESTION:**

5.2.1.a.ii. What is the marketing response for question 1?

The context does not specify the exact pre-trained neural retriever model used as the non-parametric memory component in RAG. However, this component plays a crucial role in enhancing the system's ability to retrieve relevant information from a vast knowledge base, ensuring accurate and contextually appropriate responses. By leveraging such a model, the system can dynamically access latent documents based on user input, improving the overall reliability and relevance of the output for customers. For customer-facing content, this means more precise and informed interactions, delivering greater value in real-world applications.

**Question:**
5.2.1.b: What is the context you passed to the LLM for question 1?


RAG ("Retrieval-Augmented Generation"; Lewis et al., 2020) combines pre-trained parametric (language model) and non-parametric

An illustration of retrieval-augmented generation (RAG) architecture. (Image source: Lewis et al., 2020)

(RAG) -- models which combine pre-trained parametric and non-parametric mem-

training data [28]. Retrieval-Augmented Generation (RAG) aims to mitigate these issues with its flexible data reposi-

A typical RAG process is depicted in Fig. 1. Given an input query, the retriever identifies relevant data sources, and the re-

**QUESTION:**

5.2.1.c: List the doc_source for each of the documents in the context for question 1

- [0] WWW (Wikipedia)
- [1] WWW (Wikipedia)
- [2] arxiv_pdfs/2005.11401.pdf
- [3] arxiv_pdfs/2402.19473.pdf
- [4] arxiv_pdfs/2402.19473.pdf

**QUESTION:**

5.2.1.d.i: How well does your model perform relative to the gold answer we provided for engineering on question 1?

**Research metrics vs gold (Question 0):**

| Metric | Score |
|---|---|
| bertscore_precision | 0.8774 |
| bertscore_recall | 0.8788 |
| bertscore_f1 | 0.8781 |
| rouge1_f | 0.4865 |
| rouge2_f | 0.3014 |
| rougeL_f | 0.3649 |

The BERT-F1 of 0.878 indicates strong semantic alignment with the gold answer. The ROUGE-L of 0.365 is moderate, which is expected: the gold answer explicitly names "DPR" (Dense Passage Retriever), but the 128-token max chunk config truncated the context before that detail appeared. The model correctly hedged ("the context does not explicitly name...") rather than hallucinating, which is faithful behavior that BERTScore rewards (semantic similarity to the topic) but ROUGE penalizes (missing the exact keyword).

In [ ]:
### Q5-2-1 Grading Tag: Don't edit this line.
"""
[(bertscore_precision, 0.8466),
 (bertscore_recall, 0.9052),
 (bertscore_f1, 0.8749),
 (rouge1_f, 0.2957),
 (rouge2_f, 0.2301),
 (rougeL_f, 0.2957)]
 
 """

### ENTER NOTHING HERE. THIS IS A PLACE HOLDER

#### 5.2.2 Test Question 2

Please run question 134 through your RAG pipeline:

**QUESTION:**

5.2.2.a.i: What is the engineering response for Test Question 2?

Retrieval Augmented Generation (RAG) offers significant advantages over traditional language models by addressing the limitations of static, pre-trained knowledge. Firstly, RAG incorporates an information-retrieval mechanism, enabling the model to access and integrate up-to-date information from external sources. This dynamic knowledge access ensures that responses are based on the most current and relevant data, mitigating the risk of outdated or incomplete answers inherent in models relying solely on pre-trained knowledge. By combining retrieval with generation, RAG enhances reliability and accuracy, as it can ground its responses in recent, contextually appropriate information. This approach is particularly valuable in rapidly evolving domains where traditional models may struggle to provide timely and accurate insights.

**QUESTION:**

5.2.2.a.ii: What is the marketing response for question 2?

Retrieval Augmented Generation (RAG) significantly enhances the reliability and timeliness of answers compared to traditional language models by dynamically accessing up-to-date information from external sources. Unlike models that rely solely on pre-trained knowledge, which can become outdated, RAG retrieves and incorporates the latest data, ensuring answers are both accurate and current. This approach is particularly valuable for industries where information changes rapidly, such as news, healthcare, or technology, as it provides customers with the most relevant and trustworthy responses. By combining retrieval with generation, RAG delivers a seamless user experience, fostering greater confidence in the information provided.

**QUESTION:**

5.2.2.b: What is the context you passed to the LLM for question 2?

Retrieval-augmented generation (RAG) enhances large language models (LLMs) by incorporating an information-retrieval mechanism

Retrieval-augmented generation (RAG) is an effective way to use large language models (LLMs) to answer questions while avoiding

Retrieval-Augmented Generation (RAG) has emerged as a powerful framework to overcome the

Retrieval-augmented generation (RAG) is a technique that enables large language models (LLMs) to retrieve and incorporate new

Retrieval-Augmented Generation (RAG) has recently emerged as a promising solu-

**QUESTION:**

5.2.2.c: List the doc_source for each of the documents in the context for question 2

- [0] https://en.wikipedia.org/wiki/Retrieval-augmented_generation
- [1] arxiv_pdfs/2410.12812.pdf
- [2] arxiv_pdfs/2506.10408.pdf
- [3] https://en.wikipedia.org/wiki/Retrieval-augmented_generation
- [4] arxiv_pdfs/2406.04744.pdf

**QUESTION:**

5.2.2.d.i: How well does your model perform relative to the gold answer we provided for engineering on question 2?

In [ ]:
### Q5-2-2 Grading Tag: Don't edit this line.
"""
[(bertscore_precision, 0.8123),
 (bertscore_recall, 0.8605),
 (bertscore_f1, 0.8352),
 (rouge1_f, 0.2568),
 (rouge2_f, 0.1984),
 (rougeL_f, 0.2568)]
"""

### ENTER NOTHING HERE. THIS IS A PLACE HOLDER

**QUESTION:**

5.2.2.d.ii:  How well does your model perform relative to the gold answer we provided for marketing on question 2?

**Marketing metrics vs gold (Question 134):**

| Metric | Score |
|---|---|
| bertscore_precision | 0.8947 |
| bertscore_recall | 0.9287 |
| bertscore_f1 | 0.9114 |
| rouge1_f | 0.4832 |
| rouge2_f | 0.1905 |
| rougeL_f | 0.2685 |

#### 5.2.3 Test Question 3

Please run question 225 through your RAG pipeline:

**QUESTION:**

5.2.3.a.i: What is the engineering response for Test Question 3?

The actor who portrays Thanos in the Marvel Cinematic Universe (MCU) and Cable in *Deadpool 2* is **Josh Brolin**. Brolin's performance as Thanos spans multiple MCU films, culminating in *Avengers: Infinity War* and *Avengers: Endgame*, where he is depicted through motion capture technology. In *Deadpool 2*, Brolin plays Cable, a time-traveling mutant, requiring both physical and emotional depth in his portrayal. His ability to embody these distinct characters showcases his versatility as an actor in both motion capture and traditional roles.

**QUESTION:**

5.2.3.a.ii: What is the marketing response for question 3?

Josh Brolin is the talented actor behind two iconic Marvel characters: the formidable villain Thanos in the Marvel Cinematic Universe and the time-traveling Cable in *Deadpool 2*. His versatile performances bring these complex characters to life, captivating audiences with their depth and intensity. This dual role showcases Brolin's range and ability to embody both a universe-threatening titan and a grizzled, cybernetic warrior, making him a standout figure in the Marvel franchise.

**QUESTION:**

5.2.3.b: What is the context you passed to the LLM for question 3?

one out of these candidates.

Answer:

Diego de Las Casas, Lisa Anne Hendricks, Johannes Welbl, Aidan Clark, Tom Hennigan, Eric Noland,

co-stars.

the answer.

**QUESTION:**

5.2.3.c: List the doc_source for each of the documents in the context for question 3

- [0] WWW (Wikipedia)
- [1] WWW (Wikipedia)
- [2] arxiv_pdfs/2203.15556.pdf
- [3] WWW (Wikipedia)
- [4] WWW (Wikipedia)

In [ ]:
### Q5-2-3 Grading Tag: Don't edit this line.

"""
['[0] WWW (Wikipedia)', '[1] WWW (Wikipedia)', '[2] arxiv_pdfs/2203.15556.pdf', '[3] WWW (Wikipedia)', '[4] WWW (Wikipedia)']

"""

### ENTER NOTHING HERE. THIS IS A PLACE HOLDER

**QUESTION:**

5.2.4.a: For questions 1 and 2, how well do you feel your metrics captured the differences and similarities between your answer and the gold answer?

In [ ]:
### Q5-2-4 Grading Tag: Don't edit this line.
"""BERTScore and ROUGE captured meaningfully different aspects of answer quality across questions 1 and 2. For question 1, BERT-F1 was strong (~0.878 both personas) while ROUGE-L was moderate (0.365 research, 0.296 marketing), exposing a case where the model conveyed the right concepts but missed the specific keyword "DPR" due to the truncated 128-token chunks as I previously mentioned. BERTScore correctly rewarded the semantic alignment; ROUGE correctly penalized the missing n-gram. For question 2, both metrics converged higher (BERT-F1 >0.91, ROUGE-1 >0.48). The divergence between personas was also informative: marketing ROUGE was consistently lower because the prompt deliberately reframes content for a non-technical audience, introducing vocabulary not present in the gold references. This confirms that BERTScore is the more robust primary metric for the dual-persona system I used where style-shifting is intentional, while ROUGE serves as a useful secondary signal for grounding.
"""
### THIS IS A PLACE HOLDER

### 5.3 Other Questions

Below are a few questions that you should think about. Please answer them in the text cells directly (in a short paragraph) and also see whether they may be relevant for your final write-up.

**QUESTION:**

5.3.a. How would you expect your response quality to change if you had a chunk size of 50?

In [ ]:
### Q5-3-a Grading Tag: Don't edit this line.
"""A chunk size of 50 tokens would likely produce a signficant decline in response quality. At that granularity, most chunks would contain sentence fragments or isolated tokens without enough surrounding context to convey a complete idea. The retriever would return five tiny snippets that individually lack coherent meaning, forcing the LLM to synthesize an answer from disconnected phrases. I observed this problem even at chunk_size=128, where context for question 0 was truncated mid-sentence and the model could not identify "DPR" as the specific retriever. At 50 tokens the problem would be far worse: higher retrieval recall (more chunks cover more of the corpus) but not a lot of precision per chunk, producing vague answers. BERTScore might remain moderate since the snippets would still cluster in the right topic neighborhood, but ROUGE and faithfulness would collapse.
"""
### ENTER NOTHING HERE. THIS IS A PLACE HOLDER

**QUESTION:**

5.3.b. How would you expect your response quality to change if you had a chunk size of 5000?

In [ ]:
### Q5-3-b Grading Tag: Don't edit this line.
"""A chunk size of 5000 tokens would likely swing the trade-off in the opposite direction. Each chunk would contain multiple pages of content, providing the LLM with a lot of rich context. We would likely improve performance on the detail-oriented questions like Q0, where the answer ("DPR") was lost in our 128-token chunks but would be captured in a 5000-token window. However, with only k=5 retrieved chunks, each chunk would be so large that the retriever covers fewer distinct documents, reducing diversity. The LLM would also face a much longer input context, increasing latency and the risk of "lost in the middle" effect we spoke about in class where relevant information buried in the center of a long passage is overlooked. Additionally, 5000-token chunks would dilute the vector embedding -- averaging over many topics within one chunk makes the embedding less usefulfor similarity search. Strangely enough, I saw better performance closer to 50 than I would expect. I think this is because the smaller chunks forced the model to rely more on the retrieved context and less on its parametric knowledge, which actually helped it avoid hallucinating and stay more grounded in the source material. 
"""

### ENTER NOTHING HERE. THIS IS A PLACE HOLDER

**QUESTION:**

5.3.c. If you had time, how do you think fine-tuning of the LLM could help?  What type of data would you want for that? And which training approach would you take?

In [ ]:
### Q5-3-c Grading Tag: Don't edit this line.
"""Fine-tuning the LLM could help in two key areas: persona adherence and domain-specific terminology. Currently, the marketing persona occasionally produces overly long responses (length ratio 2.08x) and the research persona sometimes hedges when the context is thin rather than synthesizing across chunks. A fine-tuned model could learn tighter output calibration for each persona.

For training data, I would curate a dataset of (question, context, gold_answer) triples for both personas, drawn from the existing 75 labeled validation pairs plus additional expert-written examples covering edge cases (out-of-domain queries, ambiguous context, multi-hop reasoning). The gold answers would enforce the target style and length for each persona.

I would use parameter-efficient fine-tuning (LoRA or QLoRA) on the base Mistral-7B model, since full fine-tuning is prohibitively expensive and LoRA adapters can be swapped per-persona at inference time. The training objective would be standard causal language modeling on the gold completions, with separate LoRA adapters for the research and marketing personas. This would preserve the model's general capabilities while specializing its output style for each audience.
"""

### ENTER NOTHING HERE. THIS IS A PLACE HOLDER

**QUESTION:**

5.3.d. What was your design philosophy  of the prompts? How did they differ between engineering and marketing support?

In [ ]:
### Q5-3-d Grading Tag: Don't edit this line.

""" My prompt design philosophy centered on three principles: faithfulness to context, audience-appropriate framing, and conciseness. Both prompts share the same system prompt emphasizing that all claims must be grounded in the provided context and I called out that uncertainty should be stated explicitly. This helps prevent the personas from hallucinates. 

The engineering prompt asks for "concrete details and correct terminology" and frames the audience as experts who will evaluate the response. This encourages the model to include specific metrics, algorithm names, and architectural details when available in the context. The marketing prompt leads with "a single clear value proposition sentence," avoids jargon, and caps the response at 4 sentences. This forces the model to distill technical content into customer-facing language.

The key difference is information density vs. accessibility. The engineering prompt maximizes information per sentence; the marketing prompt maximizes clarity per sentence. Both share the same faithfulness guardrail, which is why the Cohere baseline achieved high faithfulness scores on both personas (Research: 0.894, Marketing: 0.879) despite producing stylistically different outputs.
"""

### ENTER NOTHING HERE. THIS IS A PLACE HOLDER

**QUESTION:**

5.3.e. What are your average and peak load estimates for the system? Given that, would you suggest a pay-per-use deployment (e.g. per API call) or one that reserves instances of the LLM?

In [ ]:
### Q5-3-e Grading Tag: Don't edit this line.
"""Based on the evaluation runs, average inference time per question is approximately 3.3 seconds for the Cohere API path (816s / ~250 LLM calls across 75 questions x 3 calls each) and approximately 38 seconds for the Mistral-7B local path (2842s / 75 questions). Peak load during the evaluation was sustained sequential processing with no concurrency.

For a production deployment, I would estimate an average load of 50-100 queries/hour during business hours for the internal engineering + marketing team, with peaks of 200-300 queries/hour during product launches or research sprints.

Given these estimates, I would recommend a pay-per-use API deployment (Cohere or similar) rather than reserved GPU instances. The reasoning: 1) the Cohere path is ~3.5x faster and requires no GPU infrastructure; 2) at 100 queries/hour, a reserved A100 instance ($2-3/hour) would cost ~$1,500-2,000/month but sit idle most of the time; 3) Cohere API costs at ~$0.001/call would be under $100/month at this volume; 4) API scaling is automatic during demand spikes. Reserved instances only make sense if query volume exceeds ~10,000 queries/day sustained, or if data privacy requirements prohibit sending content to external APIs.
"""
### ENTER NOTHING HERE. THIS IS A PLACE HOLDER

**QUESTION:**

5.3.f. What type of limitations/risks would you see in using this system?

In [ ]:
### Q5-3-f Grading Tag: Don't edit this line.

"""
Several limitations and risks are evident from this proof of concept:

Retrieval limitations: The 128-token chunk size, while producing strong aggregate metrics, causes the system to miss specific details (as demonstrated with Q0's failure to surface "DPR"). Out-of-domain questions (Q225) return irrelevant context, and the system relies on the LLM's parametric knowledge to compensate -- which may not always produce correct answers.

Faithfulness risks: While faithfulness scores are high (0.87-0.89), the system can still produce plausible-sounding but unsupported statements, particularly when the retrieved context is full of fragments. The marketing persona is more susceptible to this because its framing language can mask thin evidence.

API dependency: The winning configuration depends on the Cohere API, introducing latency variability, rate limits (20 req/min on trial keys), and a single point of failure. Any API outage or model deprecation would break the system.

Evaluation gaps: BERTScore and ROUGE measure similarity to gold references but do not detect factual errors or hallucinations directly. A response that confidently states incorrect information could still score well if it uses the right vocabulary. Human evaluation or LLM-as-judge approaches would be needed for production-grade quality assurance.

Scalability: The in-memory Qdrant vector store works for this corpus size (~3,900 chunks) but would need to be replaced with a persistent, distributed store for larger document collections.
"""

### ENTER NOTHING HERE. THIS IS A PLACE HOLDER

### Your 4-5 page pdf report

You have two options:

1. Place a copy of your PDF report (not word, not openoffice) in the Gradescope folder where you put your Assignment_5.ipynb notebook.

2. Store your PDF file in a Google Drive Folder in your @berkeley.edu account.  Enter a link to your report that you've stored in your Google Drive.  Put it in a folder and give edit permissions to the following people:

    mhbutler@berkeley.edu

    peterg@berkeley.edu

    makahmad@berkeley.edu

    coyle@berkeley.edu

[Google Drive PDF Report Link](https://drive.google.com/file/d/1BXeGes-3vHe4Pkl4EYN7gAIysBxoDGzP/view?usp=drive_link)


# AI Citation Section

The following citations cover the automated metrics and LLMs used in this notebook.

## Metric Citations

1. BERTScore (semantic similarity metric)
   - Zhang, Tianyi, Varsha Kishore, Felix Wu, Kilian Q. Weinberger, and Yoav Artzi. "BERTScore: Evaluating Text Generation with BERT." arXiv:1904.09675, 2019. https://arxiv.org/abs/1904.09675

2. ROUGE (n-gram overlap metric family)
   - Lin, Chin-Yew. "ROUGE: A Package for Automatic Evaluation of Summaries." In Proceedings of the ACL Workshop: Text Summarization Branches Out, 74-81, 2004. https://aclanthology.org/W04-1013/

3. Faithfulness / groundedness (consistency with retrieved context)
   - Es, Shahul, et al. "RAGAS: Automated Evaluation of Retrieval Augmented Generation." arXiv:2309.15217, 2023. https://arxiv.org/abs/2309.15217

4. Length Ratio (response length alignment heuristic used in this notebook)
   - This notebook uses a custom Length Ratio metric (generated answer length divided by gold answer length) for calibration and style-fit analysis.
   - The use of length normalization as a scoring/decoding control is conceptually aligned with:
     Wu, Yonghui, et al. "Google's Neural Machine Translation System: Bridging the Gap between Human and Machine Translation." arXiv:1609.08144, 2016. https://arxiv.org/abs/1609.08144

## LLM Citations (Assignment Usage Format)

1. RAG answer generation, query rewriting, and persona-specific responses (engineering + marketing), Mistral-7B-Instruct-v0.3, Mistral AI, April 6, 2026, https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3

2. Comparative RAG generation run using the same retrieval pipeline (Cohere configuration), Command A, Cohere, April 6, 2026, https://docs.cohere.com/docs/models#command

3. Prompt Generations (in experiments) / Polish wording / Format code, Qwen3, Qwen Team, 4/5/26, [Qwen/Qwen3-8B](https://huggingface.co/Qwen/Qwen3-8B)